### PR TITLE
Fix scheduler sizes and shutdown

### LINKED ISSUE #934: OOM Crash - failed to store on BlockDropped in retainer
We have two nodes that crashed on out of memory.

It seems they started to log this error message:
```
Protocol.Engine0    	engine error (err=blockRetainer: failed to store on BlockDropped in retainer: cannot update block metadata for block BlockID(0xbc718142f4c3957f2e7484dec30b891a9edfc09b2d50c8faa8d753d09bb8dc12d4830000:33748) with state dropped as block is already committed)
```

About 50k times per hour.

Memory inflated at the time:
image

We have a log file when it started:
[faucet.h.iota2-alphanet_2024-04-24-09.log](https://github.com/iotaledger/iota-core/files/15106326/faucet.h.iota2-alphanet_2024-04-24-09.log)

Unfortunately it happened at night, so we have no memory profile of this node.

But we have profile of another node that started at the same time but "recovered" later on (while memory usage still is high)
image

[pprof.validator-2_20240425-075134_all.zip](https://github.com/iotaledger/iota-core/files/15106310/pprof.validator-2_20240425-075134_all.zip)

Maybe it shows something :see_no_evil:

### LINKED ISSUE #936: shutdown hanging, somehow prometheus related
(happened with iota-core alpha.18)

We monitor go metrics like heap and noticed that on some nodes prometheus is not accessible anymore, trying to `curl` the metrics leads to a timeout.

As expected, in this cases the nodes cannot be shutdown gracefully.

Node was healthy + network-healthy and other things like the `info` endpoint were working.

Here is a profile of iota-core while it is waiting for `Close p2p peer database, P2P, Protocol`.
[pprof.validator-11_20240425-125923_all.zip](https://github.com/iotaledger/iota-core/files/15110308/pprof.validator-11_20240425-125923_all.zip)

### PR DESCRIPTION
**Pull request by muXxer**

### CODE REVIEW

File: pkg/protocol/engine/congestioncontrol/scheduler/drr/issuerqueue.go [hunk 1]
```diff
@@ -18,19 +18,36 @@ import (
 
 // IssuerQueue keeps the submitted blocks of an issuer.
 type IssuerQueue struct {
-	issuerID    iotago.AccountID
-	nonReadyMap *shrinkingmap.ShrinkingMap[iotago.BlockID, *blocks.Block]
-	readyHeap   generalheap.Heap[timed.HeapKey, *blocks.Block]
-	size        atomic.Int64
-	work        atomic.Int64
+	issuerID        iotago.AccountID
```
Comment (cyberphysic4l) [inline pkg/protocol/engine/congestioncontrol/scheduler/drr/issuerqueue.go:21]: Why group them this way? It seems nices to group the readyHeap and the nonReadyMap, and then the size and work

File: pkg/protocol/engine/congestioncontrol/scheduler/drr/scheduler.go [hunk 2]
```diff
@@ -408,31 +387,11 @@ func (s *Scheduler) selectBlockToScheduleWithLocking() {
 	s.bufferMutex.Lock()
 	defer s.bufferMutex.Unlock()
 
-	s.validatorBuffer.buffer.ForEach(func(_ iotago.AccountID, validatorQueue *ValidatorQueue) bool {
-		if s.selectValidationBlockWithoutLocking(validatorQueue) {
-			s.validatorBuffer.size.Dec()
-		}
+	s.validatorBuffer.ScheduleNext()
```
Comment (cyberphysic4l) [inline pkg/protocol/engine/congestioncontrol/scheduler/drr/scheduler.go]: I think it's easier to understand that we are scheduling something from every validator's individual queue if you leave it as a loop here. The ScheduleNext() for the whole validator buffer is confusing.

**Review by cyberphysic4l — APPROVED** [review]
