### PR TITLE
Remove CausalOrderer dependency by making Booker and Solidifier reactive

### LINKED ISSUE #382: Nil pointer dereference in causal orderer
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xd6f06d]

goroutine 135 [running]:
github.com/iotaledger/hive.go/ds/shrinkingmap.(*ShrinkingMap[...]).Get(0x2b75de0?, {0x62, 0x60, 0x2e, 0x37, 0x9f, 0x19, 0x91, 0x4f, 0xc1, ...})
	/go/pkg/mod/github.com/iotaledger/hive.go/ds@v0.0.0-20230926122307-d671b36a4a65/shrinkingmap/shrinkingmap.go:92 +0x2d
github.com/iotaledger/hive.go/core/causalorder.(*CausalOrder[...]).decreaseUnorderedParentsCounter(0x2b75360, 0x31077236caecd7c2)
	/go/pkg/mod/github.com/iotaledger/hive.go/core@v1.0.0-rc.3.0.20230926122307-d671b36a4a65/causalorder/causalorder.go:187 +0x1b5
github.com/iotaledger/hive.go/core/causalorder.(*CausalOrder[...]).triggerChildIfReady(0x2b75360, 0x92a0f1)
	/go/pkg/mod/github.com/iotaledger/hive.go/core@v1.0.0-rc.3.0.20230926122307-d671b36a4a65/causalorder/causalorder.go:223 +0x1ca
github.com/iotaledger/hive.go/core/causalorder.(*CausalOrder[...]).propagateOrderToChildren.func1()
	/go/pkg/mod/github.com/iotaledger/hive.go/core@v1.0.0-rc.3.0.20230926122307-d671b36a4a65/causalorder/causalorder.go:250 +0x9e
github.com/iotaledger/hive.go/runtime/workerpool.(*Task).run(0xc065ec5890)
	/go/pkg/mod/github.com/iotaledger/hive.go/runtime@v0.0.0-20230926122307-d671b36a4a65/workerpool/task.go:48 +0x72
github.com/iotaledger/hive.go/runtime/workerpool.(*WorkerPool).workerReadLoop(0xc000213c00)
	/go/pkg/mod/github.com/iotaledger/hive.go/runtime@v0.0.0-20230926122307-d671b36a4a65/workerpool/workerpool.go:177 +0x25
github.com/iotaledger/hive.go/runtime/workerpool.(*WorkerPool).worker(0xc000213c00)
	/go/pkg/mod/github.com/iotaledger/hive.go/runtime@v0.0.0-20230926122307-d671b36a4a65/workerpool/workerpool.go:159 +0x50
created by github.com/iotaledger/hive.go/runtime/workerpool.(*WorkerPool).startWorkers in goroutine 1
	/go/pkg/mod/github.com/iotaledger/hive.go/runtime@v0.0.0-20230926122307-d671b36a4a65/workerpool/workerpool.go:151 +0x25
```

### PR DESCRIPTION
**Pull request by karimodm**
Fixes #382 by removing the dependency in favor of a reactive approach.

Based the PR on https://github.com/iotaledger/iota-core/pull/379 to avoid conflicts.

### CODE REVIEW

File: pkg/protocol/engine/blocks/block.go [hunk 1]
```diff
@@ -253,20 +258,33 @@ func (b *Block) IsMissing() (isMissing bool) {
 	return b.missing
 }
 
+// Solid returns a reactive variable that is true if the Block is solid (the entire causal history is known).
+func (b *Block) Solid() (solid reactive.Variable[bool]) {
+	b.mutex.RLock()
```
Comment (alexsporn) [inline pkg/protocol/engine/blocks/block.go:263]: why do we need locks here to protect these variables?

File: pkg/protocol/engine/blocks/block.go [hunk 2]
```diff
@@ -19,8 +19,8 @@ type Block struct {
 	// BlockDAG block
 	missing             bool
 	missingBlockID      iotago.BlockID
-	solid               bool
```
Comment (piotrm50) [inline pkg/protocol/engine/blocks/block.go:22]: if it's a bool variable it could be an event, then you can also call `Trigger` on it without having to pass value - that way you can get rid of the SetSolid methods I think

File: pkg/protocol/engine/booker/inmemorybooker/booker.go [hunk 3]
```diff
@@ -132,15 +115,38 @@ func (b *Booker) Queue(block *blocks.Block) error {
...
 func (b *Booker) Shutdown() {
 	b.TriggerStopped()
-	b.workers.Shutdown()
 }
 
-func (b *Booker) setRetainBlockFailureFunc(retainBlockFailure func(iotago.BlockID, apimodels.BlockFailureReason)) {
-	b.retainBlockFailure = retainBlockFailure
+func (b *Booker) setupBlock(block *blocks.Block) {
+	var unbookedParentsCount atomic.Int32
+	unbookedParentsCount.Store(int32(len(block.Parents())))
```
Comment (piotrm50) [inline pkg/protocol/engine/booker/inmemorybooker/booker.go:122]: Wouldn't it be better to use reactive.Counter here instead of having a separate variable?

Comment (karimodm) [reply pkg/protocol/engine/booker/inmemorybooker/booker.go:122]: Good idea, I didn't think about it! I've just tried to code a version with it and in my opinion is not very readable. I can show you and decide what version is best.

File: pkg/protocol/engine/blocks/block.go (hunk 2 above)
Comment (karimodm) [reply pkg/protocol/engine/blocks/block.go:22]: Considering that a reactive.Event is a more complex type, as it that enapsulates a readable.Variable, and considering that a block is so ubiquitous, I would like to keep a simpler API rather than having `b.Booked().WasTriggered()` and such. It seems less readable to me!

File: pkg/protocol/engine/blocks/block.go (hunk 1 above)
Comment (karimodm) [reply pkg/protocol/engine/blocks/block.go:263]: We don't on the reactive variables :+1:

File: pkg/protocol/engine/booker/inmemorybooker/booker.go [hunk 4]
```diff
@@ -132,15 +115,38 @@ func (b *Booker) Queue(block *blocks.Block) error {
...
+
+	block.ForEachParent(func(parent iotago.Parent) {
+		parentBlock, exists := b.blockCache.Block(parent.ID)
+		if !exists {
+			panic("cannot setup block without existing parent")
```
Comment (jonastheis) [inline pkg/protocol/engine/booker/inmemorybooker/booker.go:127]: We really need to start thinking about a proper way to log these things. Panicing everywhere will just increase the likelihood of the node going down even though it doesn't have to. Simply logging and ignoring this block should be enough

**Review by jonastheis — CHANGES_REQUESTED** [review]

File: pkg/protocol/engine/blockdag/inmemoryblockdag/blockdag.go [hunk 5]
```diff
@@ -83,6 +79,32 @@ func NewProvider(opts ...options.Option[BlockDAG]) module.Provider[*engine.Engin
...
+					b.events.BlockSolid.Trigger(block)
+				}
+			}
+		})
+
+		parentBlock.Invalid().OnUpdateOnce(func(_, _ bool) {
+			if block.SetInvalid() {
+				b.events.BlockInvalid.Trigger(block, ierrors.Errorf("parent block %s is marked as invalid", parent.ID))
+			}
+		})
```
[the remark this answers is not in the document]
Comment (alexsporn) [reply pkg/protocol/engine/blockdag/inmemoryblockdag/blockdag.go:104]: I agree, but that is a much bigger change than just replacing the inner workings. That is a separate PR imho.

**Review by alexsporn — APPROVED** [review]

File: pkg/protocol/engine/blockdag/inmemoryblockdag/blockdag.go [hunk 6]
```diff
@@ -26,9 +27,6 @@ type BlockDAG struct {
 	// evictionState contains information about the current eviction state.
 	evictionState *eviction.State
```
[the remark this answers is not in the document]
Comment (karimodm) [reply pkg/protocol/engine/blockdag/inmemoryblockdag/blockdag.go:28]: It is. In: shouldAttach, registerChild and canAttachToParents

File: pkg/protocol/engine/blockdag/inmemoryblockdag/blockdag.go [hunk 7]
```diff
@@ -38,9 +36,7 @@ type BlockDAG struct {
 
 	solidifierMutex syncutils.RWMutex
```
[the remark this answers is not in the document]
Comment (karimodm) [reply pkg/protocol/engine/blockdag/inmemoryblockdag/blockdag.go:37]: It is not needed anymore, it is currently only read-locked ;)

File: pkg/protocol/engine/blockdag/inmemoryblockdag/blockdag.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (karimodm) [reply pkg/protocol/engine/blockdag/inmemoryblockdag/blockdag.go:104]: Agree with you both!

File: pkg/protocol/engine/booker/inmemorybooker/booker.go [hunk 8]
```diff
@@ -132,15 +115,38 @@ func (b *Booker) Queue(block *blocks.Block) error {
...
+					}
+				}
+			}
+		})
+
+		parentBlock.Invalid().OnUpdateOnce(func(_, _ bool) {
+			if block.SetInvalid() {
+				b.events.BlockInvalid.Trigger(block, ierrors.New("block marked as invalid in Booker"))
+			}
+		})
```
[the remark this answers is not in the document]
Comment (karimodm) [reply pkg/protocol/engine/booker/inmemorybooker/booker.go:144]: See reply above.

File: pkg/protocol/engine/booker/inmemorybooker/booker.go (hunk 4 above)
Comment (karimodm) [reply pkg/protocol/engine/booker/inmemorybooker/booker.go]: Passing the error to the errorHandler and skipping this parent.
It would be better to bail the setup for the whole block and undo the hooking we did so far, but it is tricky and ugly; let's rely instead on the GC to eventually cleanup everything, as this block can never become solid.

**Review by jonastheis — APPROVED** [review]
