### PR TITLE
Implement a fix to avoid accessing shutdown DB after an engine Reset.

### LINKED ISSUE #521: KVStore value not found in end-to-end test
Randomly happened in CI and locally once.

```
2023-11-14T14:28:03.0103132Z node1 > [Main - 560fe0d4] NotarizationManager.SlotCommitted: CommitmentID(0x66a5597312e78462e17ef45b3bf5357c43789d530aa20921a3e8cf1340600e8a22000000:34) Commitment {
2023-11-14T14:28:03.0103763Z     ID: CommitmentID(0x66a5597312e78462e17ef45b3bf5357c43789d530aa20921a3e8cf1340600e8a22000000:34)
2023-11-14T14:28:03.0103926Z     Commitment: "{
2023-11-14T14:28:03.0104139Z       "protocolVersion": 3,
2023-11-14T14:28:03.0104308Z       "slot": 34,
2023-11-14T14:28:03.0105074Z       "previousCommitmentId": "0xf300bb0dce9ee00287a3037a270d1be52e838e1bdda08670b7edde08724cca6021000000",
2023-11-14T14:28:03.0105655Z       "rootsId": "0x8a5d53814b83d797d3de42b3836d0f4ff63a09a9674fd94c9958feaf7e85c562",
2023-11-14T14:28:03.0105872Z       "cumulativeWeight": "0",
2023-11-14T14:28:03.0106093Z       "referenceManaCost": "500"
2023-11-14T14:28:03.0106304Z     }"
2023-11-14T14:28:03.0106469Z } Accepted Blocks: []
2023-11-14T14:28:03.0111043Z  Roots(0x8a5d53814b83d797d3de42b3836d0f4ff63a09a9674fd94c9958feaf7e85c562): TangleRoot: 0x0000000000000000000000000000000000000000000000000000000000000000, StateMutationRoot: 0x0000000000000000000000000000000000000000000000000000000000000000, StateRoot: 0xa5f12ef1516e1bcc352189c1619fa8169b9456573cd32beef194f8c6820c084d, AccountRoot: 0x5bd39b83f52f61cebfc9beac5e83cdb908212e1ebe42c98ed862538f36ef2efe, AttestationsRoot: 0x0000000000000000000000000000000000000000000000000000000000000000, CommitteeRoot: 0x29f6a18e06c161e72cff7fee77be013fcae471e5bce29383281948d7cae87acb, RewardsRoot: 0x0000000000000000000000000000000000000000000000000000000000000000, ProtocolParametersHash: 0x010abf5b4192639f381060a7b8d3c78dc9ff89069a955903498568c53c9e82dc
2023-11-14T14:28:03.0111203Z  Attestations: []
2023-11-14T14:28:03.0112393Z node1 > [Main - 560fe0d4] NotarizationManager.LatestCommitmentUpdated: CommitmentID(0x66a5597312e78462e17ef45b3bf5357c43789d530aa20921a3e8cf1340600e8a22000000:34)
2023-11-14T14:28:03.0112996Z node1 > Protocol.Error: slot 35 is not committed yet: failed to get slot 35 (not committed yet)
2023-11-14T14:28:03.0114254Z node2 > Network.WarpSyncRequestReceived: from 12D3KooWPw1Vo9SDfkWJyAQp2NnpnwW5AgLF3w6d8jEqmMY8HvNg CommitmentID(0xd3286fed492fbbe098f8b7dfc8bf9ac9e7a07b19abea446e654221d469263b8923000000:35)
2023-11-14T14:28:03.0114796Z node2 > Protocol.Error: slot 35 is not committed yet: failed to get slot 35 (not committed yet)
2023-11-14T14:28:03.0115048Z node0 > Run finished with error: context canceled
2023-11-14T14:28:03.0115299Z node1 > Run finished with error: context canceled
2023-11-14T14:28:03.0115532Z node2 > Run finished with error: context canceled
2023-11-14T14:28:03.0115872Z --- FAIL: TestLossOfAcceptanceFromGenesis (8.76s)
2023-11-14T14:28:03.0116362Z     testsuite.go:542: 
2023-11-14T14:28:03.0117360Z         	Error Trace:	/actions-runner/_work/iota-core/iota-core/pkg/testsuite/testsuite.go:542
2023-11-14T14:28:03.0118753Z         	            				/actions-runner/_work/iota-core/iota-core/pkg/testsuite/storage_commitments.go:36
2023-11-14T14:28:03.0120079Z         	            				/actions-runner/_work/iota-core/iota-core/pkg/tests/loss_of_acceptance_test.go:63
2023-11-14T14:28:03.0120407Z         	Error:      	condition never satisfied
2023-11-14T14:28:03.0120782Z         	Test:       	TestLossOfAcceptanceFromGenesis
2023-11-14T14:28:03.0122027Z         	Messages:   	key not found: failed to retrieve from KV store: AssertEqualStoredCommitmentAtIndex: node1: error loading commitment for slot: 50 
```

### PR DESCRIPTION
**Pull request by piotrm50**

### CODE REVIEW

File: pkg/protocol/block_dispatcher.go [hunk 1]
```diff
@@ -78,18 +78,25 @@ func (b *BlockDispatcher) Dispatch(block *model.Block, src peer.ID) error {
...
 	for _, engine := range []*engine.Engine{b.protocol.MainEngineInstance(), b.protocol.CandidateEngineInstance()} {
-		if engine != nil && !engine.WasShutdown() && (engine.ChainID() == slotCommitment.Chain().ForkingPoint.ID() || engine.BlockRequester.HasTicker(block.ID())) {
-			if b.inSyncWindow(engine, block) {
-				engine.ProcessBlockFromPeer(block, src)
-			} else {
-				// Stick too new blocks into the unsolid commitment buffer so that they can be dispatched once the
-				// engine instance is in sync (mostly needed for tests).
-				if !b.unsolidCommitmentBlocks.Add(slotCommitment.ID(), types.NewTuple(block, src)) {
-					return ierrors.Errorf("failed to add block %s to unsolid commitment buffer", block.ID())
+		e := engine
```
Comment (jonastheis) [inline pkg/protocol/block_dispatcher.go]: Why not just assign in in the loop above? You assign it and keep using `engine` which shadows the package name

File: pkg/protocol/block_dispatcher.go [hunk 2]
```diff
@@ -78,18 +78,25 @@ func (b *BlockDispatcher) Dispatch(block *model.Block, src peer.ID) error {
...
+		if engine != nil && !engine.WasShutdown() {
+			// Lock access to the engine while it's being reset, so that no new blocks enter the dataflow.
```
Comment (jonastheis) [inline pkg/protocol/block_dispatcher.go]: The comment is a bit misleading. Shouldn't it be rather something like: "The engine is locked while it's being reset ..., here we make sure that this process is exclusive"

File: pkg/protocol/engine/engine.go [hunk 3]
```diff
@@ -223,26 +226,34 @@ func (e *Engine) ProcessBlockFromPeer(block *model.Block, source peer.ID) {
...
+	e.Ledger.Reset()
+	e.CommitmentFilter.Reset()
+	e.BlockDAG.Reset()
+	e.Filter.Reset()
+	e.Retainer.Reset()
+	e.EvictionState.Reset()
+	e.BlockCache.Reset()
+
+	// Waits for all pending tasks to be processed.
+	e.Workers.WaitChildren()
```
Comment (jonastheis) [inline pkg/protocol/engine/engine.go]: Why do you only wait for the tasks to be processed **after** resetting? Naively, I'd say we should wait before so that nothing is happening anymore and that we have a clean slate after the reset

File: pkg/protocol/block_dispatcher.go (hunk 1 above)
Comment (piotrm50) [reply pkg/protocol/block_dispatcher.go]: The pointer will be reused in subsequent loop iterations, and we want to bind the correct value of the pointer in the defer, not the last one.

File: pkg/protocol/block_dispatcher.go (hunk 2 above)
Comment (piotrm50) [reply pkg/protocol/block_dispatcher.go]:
```suggestion
			// The engine is locked while it's being reset, so that no new blocks enter the dataflow, here we make sure that this process is exclusive
```

File: pkg/protocol/engine/engine.go (hunk 3 above)
Comment (piotrm50) [reply pkg/protocol/engine/engine.go]: We figured that the order of events during Reset should match the order in Shutdown, and we just put it in the same place. Do you think we shoul move it in Shutdown method as well?

I think the most important thing is that it's done before we close the storage, so that if there were any pending tasks in the worker pools, they can finish (especially around acceptance/notarization).

File: pkg/protocol/block_dispatcher.go (hunk 1 above)
Comment (piotrm50) [reply pkg/protocol/block_dispatcher.go]:
```suggestion
		// Bind value of the pointer to a local variable, because the pointer in the loop will be reused and modified in the next iteration. That could be problematic with use of `defer`.
		e := engine
```

File: pkg/protocol/engine/engine.go (hunk 3 above)
Comment (piotrm50) [reply pkg/protocol/engine/engine.go]: Ok, moved it above.

File: pkg/protocol/block_dispatcher.go (hunk 2 above)
Comment (piotrm50) [reply pkg/protocol/block_dispatcher.go]: Removed the defer entirely.

**Review by alexsporn — APPROVED** [review]

**Review by jonastheis — APPROVED** [review]
