### PR TITLE
Store txConflicting reason correctly and rename ConflictDAG to SpendDAG

### LINKED ISSUE #462: REST-API sometimes returns conflicting transactions, but there are no conflicts
So I wrote a faucet spammer, forcing the spammer to do payouts in a loop. Works fine so far.
But from all the faucet TX, 79 are successful, and 5 failed. The reason is not the indexer code, nor the faucet code.
It's because the iota-core node API returns "transactionFailureReason=2" conflicting sometimes.
This happens when I query for the state of the transaction immediately after I issued the block to the node.
(that happens sometimes because I have an asynchonous cleanup thread in the faucet that waits on the "send lock")

```
2023-10-24T17:55:05Z    DEBUG   Faucet  collected 2 requests
2023-10-24T17:55:05Z    DEBUG   Faucet  determined 1 available unspent outputs and 2 processable requests
2023-10-24T17:55:05Z    DEBUG   Faucet          unspent output 0, outputID: 0xd45c6da5965033a1b344069b702d263cd4910d422b9aa9d94b4a6d484d4e831a140000000100, amount: 999951000000000, mana: 152439329442
2023-10-24T17:55:05Z    DEBUG   Faucet          processable request 0, address: rms1qpc7mcv4t270gyqnx2plltadxrm2dfcqj9k8ecpujqgzuz5257gkkej8c65, amount: 1000000000
2023-10-24T17:55:05Z    DEBUG   Faucet          processable request 1, address: rms1qzdppxfjs06seq3yarat3ucv2w04uq6an2p9yl290vqnmpzwh69262dm36n, amount: 1000000000
2023-10-24T17:55:05Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:55:05Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0x415737bec6ce2572d63a4e37a1167117ab2a4c99c9c1c21820bc1c67382589061c000000:28), txID: SignedTransactionID(0x73591246b918686bd62240a41a863ce7fc4c43a924010db7a00b0cf08bc9003c15000000:21)
2023-10-24T17:55:05Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:55:05Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x415737bec6ce2572d63a4e37a1167117ab2a4c99c9c1c21820bc1c67382589061c000000:28), txID: TransactionID(0xab3d9dc9670a98ef1e9cfb584d9947de496b377a3074e0546b441e0674739ab415000000:21)
2023-10-24T17:55:06Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:55:06Z    DEBUG   Faucet  entering checkPendingTransactionState...
2023-10-24T17:55:06Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:55:06Z    DEBUG   Faucet  checkPendingTransactionState: no pending transaction found
2023-10-24T17:55:06Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:55:08Z    DEBUG   Faucet  collected 1 requests
2023-10-24T17:55:08Z    DEBUG   Faucet  determined 1 available unspent outputs and 1 processable requests
2023-10-24T17:55:08Z    DEBUG   Faucet          unspent output 0, outputID: 0xab3d9dc9670a98ef1e9cfb584d9947de496b377a3074e0546b441e0674739ab4150000000200, amount: 999949000000000, mana: 160063480132
2023-10-24T17:55:08Z    DEBUG   Faucet          processable request 0, address: rms1qqj49hz7rtxacss5p98nzcjn4wkwq4h68sddu3n3dclttfh3cnslj76zz9s, amount: 1000000000
2023-10-24T17:55:08Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:55:08Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0xe39ae1e0085829cf7de3f3da736612fd7d75beebd91c992ac18e09a0ed256b351c000000:28), txID: SignedTransactionID(0x7edbc576acc04fa9c20937dc45ac7006a840f6d49e9a2f8e5b5e94e3ecafc22d15000000:21)
2023-10-24T17:55:08Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:55:08Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0xe39ae1e0085829cf7de3f3da736612fd7d75beebd91c992ac18e09a0ed256b351c000000:28), txID: TransactionID(0x70e43234b69878a2e08c6962f56ea12434adc06a61fd110826eb5104dab2ccd815000000:21)
2023-10-24T17:55:09Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:55:09Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:55:09Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:55:11Z    DEBUG   Faucet  collected 1 requests
2023-10-24T17:55:11Z    DEBUG   Faucet  determined 1 available unspent outputs and 1 processable requests
2023-10-24T17:55:11Z    DEBUG   Faucet          unspent output 0, outputID: 0x70e43234b69878a2e08c6962f56ea12434adc06a61fd110826eb5104dab2ccd8150000000100, amount: 999948000000000, mana: 160059273632
2023-10-24T17:55:11Z    DEBUG   Faucet          processable request 0, address: rms1qppat5t9dakvvp5hpwkkhmsny8pmwz44enmtj9dqjly0296hacllqsfzey2, amount: 1000000000
2023-10-24T17:55:11Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:55:11Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0xb31d32dedca964b8bf72a3c46b4ec794fda3fce44cc72f9d9b07f9ea470232d01c000000:28), txID: SignedTransactionID(0x4f26fcd741872a2f00dca339a66282602ab6ece71e3479cf78ecea087a8be9b015000000:21)
2023-10-24T17:55:11Z    DEBUG   Faucet  entering checkPendingTransactionState...
2023-10-24T17:55:11Z    WARN    Faucet  metadata of the pending transaction is no transaction, blockID: BlockID(0xb31d32dedca964b8bf72a3c46b4ec794fda3fce44cc72f9d9b07f9ea470232d01c000000:28), txID: TransactionID(0x919cccbace551b189c8a35c275b6dc9688e26417140d49e7f7280ce443f9f8bf15000000:21)
2023-10-24T17:55:11Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:55:12Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:55:13Z    DEBUG   Faucet  collected 2 requests
2023-10-24T17:55:13Z    DEBUG   Faucet  determined 1 available unspent outputs and 2 processable requests
2023-10-24T17:55:13Z    DEBUG   Faucet          unspent output 0, outputID: 0x919cccbace551b189c8a35c275b6dc9688e26417140d49e7f7280ce443f9f8bf150000000100, amount: 999947000000000, mana: 160055067132
2023-10-24T17:55:13Z    DEBUG   Faucet          processable request 0, address: rms1qppat5t9dakvvp5hpwkkhmsny8pmwz44enmtj9dqjly0296hacllqsfzey2, amount: 1000000000
2023-10-24T17:55:13Z    DEBUG   Faucet          processable request 1, address: rms1qpy47egq5r2c8fdleg8zjxur8z6ssurztwhzdzl6pss7ywytk8h7vuzyr5e, amount: 1000000000
2023-10-24T17:55:13Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:55:13Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0x3a7fb74a0db4ec7a13c76d88c8f48d5ec6357b33ffbc639486200e24ae046e6d1c000000:28), txID: SignedTransactionID(0xd16be81459cbb9bc171fbafbb5d2502b3aba6a052a26d90da9864da0f3d0f60b15000000:21)
2023-10-24T17:55:13Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:55:13Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x3a7fb74a0db4ec7a13c76d88c8f48d5ec6357b33ffbc639486200e24ae046e6d1c000000:28), txID: TransactionID(0x24da47e86fbc23bf64badb859b9a1614beab35449aa5ca056581c5ca4f45114515000000:21)
2023-10-24T17:55:14Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:55:14Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x3a7fb74a0db4ec7a13c76d88c8f48d5ec6357b33ffbc639486200e24ae046e6d1c000000:28), txID: TransactionID(0x24da47e86fbc23bf64badb859b9a1614beab35449aa5ca056581c5ca4f45114515000000:21)
2023-10-24T17:55:14Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:55:15Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:55:15Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x3a7fb74a0db4ec7a13c76d88c8f48d5ec6357b33ffbc639486200e24ae046e6d1c000000:28), txID: TransactionID(0x24da47e86fbc23bf64badb859b9a1614beab35449aa5ca056581c5ca4f45114515000000:21)
2023-10-24T17:55:16Z    DEBUG   Faucet  entering checkPendingTransactionState...
2023-10-24T17:55:16Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:55:16Z    DEBUG   Faucet  checkPendingTransactionState: no pending transaction found
2023-10-24T17:55:16Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:55:18Z    DEBUG   Faucet  collected 2 requests
2023-10-24T17:55:18Z    DEBUG   Faucet  determined 1 available unspent outputs and 2 processable requests
2023-10-24T17:55:18Z    DEBUG   Faucet          unspent output 0, outputID: 0x24da47e86fbc23bf64badb859b9a1614beab35449aa5ca056581c5ca4f451145150000000200, amount: 999945000000000, mana: 160050197132
2023-10-24T17:55:18Z    DEBUG   Faucet          processable request 0, address: rms1qqfkfcrhvx9vwxtnmwju285mrhw3v3kjs2gx9rrhn4qn9yjumjhj2zgzyy6, amount: 1000000000
2023-10-24T17:55:18Z    DEBUG   Faucet          processable request 1, address: rms1qq4gdvlacvkfkjk5730pk68z9zkm987xh9gjjquhqexxuqtdm2w6c7lulxt, amount: 1000000000
2023-10-24T17:55:18Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:55:18Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0x296f9c13b1f30c93afd05b843f75fe4d8d9c769fb2372c863f4322e632fce5eb1d000000:29), txID: SignedTransactionID(0x63e0675a34b79c07c9b3753007f5b35a772336a9b5696c5f0d9370f293882b4616000000:22)
2023-10-24T17:55:18Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:55:18Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x296f9c13b1f30c93afd05b843f75fe4d8d9c769fb2372c863f4322e632fce5eb1d000000:29), txID: TransactionID(0x826970f67688d5544a680d766105c74e4661f87a3733e23ef55d13b4034f6bc516000000:22)
2023-10-24T17:55:19Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:55:19Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:55:19Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:55:21Z    DEBUG   Faucet  collected 1 requests
2023-10-24T17:55:21Z    DEBUG   Faucet  determined 1 available unspent outputs and 1 processable requests
2023-10-24T17:55:21Z    DEBUG   Faucet          unspent output 0, outputID: 0x826970f67688d5544a680d766105c74e4661f87a3733e23ef55d13b4034f6bc5160000000200, amount: 999943000000000, mana: 167674302046
2023-10-24T17:55:21Z    DEBUG   Faucet          processable request 0, address: rms1qr63wwrs9ep3xf96p26vp2nkgyw80mv6l2nq24ltuwkl68rp7akggjzq72h, amount: 1000000000
2023-10-24T17:55:21Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:55:21Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0xbd3ffeafff96f706a1c1e16eee68d5eb9e23951e49e3735824f48024ae5bc6ca1d000000:29), txID: SignedTransactionID(0x07cf9fe62325ccd45cdab5d3893f2b103178299fa5d7e3b8c957b592d4a4297a16000000:22)
2023-10-24T17:55:21Z    DEBUG   Faucet  entering checkPendingTransactionState...
2023-10-24T17:55:21Z    DEBUG   Faucet  checkPendingTransactionState: transaction still pending, blockID: BlockID(0xbd3ffeafff96f706a1c1e16eee68d5eb9e23951e49e3735824f48024ae5bc6ca1d000000:29), txID: TransactionID(0x9eb2f2308414e8747f77eafc3a19136c15a2723ae8bf3c0d08871990a3bbbfec16000000:22)
2023-10-24T17:55:21Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:55:21Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0xbd3ffeafff96f706a1c1e16eee68d5eb9e23951e49e3735824f48024ae5bc6ca1d000000:29), txID: TransactionID(0x9eb2f2308414e8747f77eafc3a19136c15a2723ae8bf3c0d08871990a3bbbfec16000000:22)
2023-10-24T17:55:22Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:55:22Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:55:22Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0xbd3ffeafff96f706a1c1e16eee68d5eb9e23951e49e3735824f48024ae5bc6ca1d000000:29), txID: TransactionID(0x9eb2f2308414e8747f77eafc3a19136c15a2723ae8bf3c0d08871990a3bbbfec16000000:22)
2023-10-24T17:55:23Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:55:23Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:55:25Z    DEBUG   Faucet  collected 2 requests
2023-10-24T17:55:25Z    DEBUG   Faucet  determined 1 available unspent outputs and 2 processable requests
2023-10-24T17:55:25Z    DEBUG   Faucet          unspent output 0, outputID: 0x9eb2f2308414e8747f77eafc3a19136c15a2723ae8bf3c0d08871990a3bbbfec160000000100, amount: 999942000000000, mana: 167670095546
2023-10-24T17:55:25Z    DEBUG   Faucet          processable request 0, address: rms1qz9qsrpr045unt56u055h6klq5ssxn2nucsljsur0m6c2zwv72zw6kwcsrt, amount: 1000000000
2023-10-24T17:55:25Z    DEBUG   Faucet          processable request 1, address: rms1qreekkddfq80a7xn28ghdqh0t674xcetpcsj43p2l5zf3ek7hqj0xsmj9tp, amount: 1000000000
2023-10-24T17:55:25Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:55:25Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0x702ea6efafc1ffd39cf00778cec9314a064645c42d3ea89a8fd5b98f589d11c51e000000:30), txID: SignedTransactionID(0xada857b0b8dbcc76f18ba1ed921eee66403ea05e358d43cdf32c0ab33c0e605a17000000:23)
2023-10-24T17:55:25Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:55:25Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x702ea6efafc1ffd39cf00778cec9314a064645c42d3ea89a8fd5b98f589d11c51e000000:30), txID: TransactionID(0x477109b96226e96fab53a082c874d35fba5540efdfdfd2d2b8fe8b161b2230dd17000000:23)
2023-10-24T17:55:26Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:55:26Z    DEBUG   Faucet  entering checkPendingTransactionState...
2023-10-24T17:55:26Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:55:26Z    DEBUG   Faucet  checkPendingTransactionState: no pending transaction found
2023-10-24T17:55:26Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:55:28Z    DEBUG   Faucet  collected 1 requests
2023-10-24T17:55:28Z    DEBUG   Faucet  determined 1 available unspent outputs and 1 processable requests
2023-10-24T17:55:28Z    DEBUG   Faucet          unspent output 0, outputID: 0x477109b96226e96fab53a082c874d35fba5540efdfdfd2d2b8fe8b161b2230dd170000000200, amount: 999940000000000, mana: 175294177572
2023-10-24T17:55:28Z    DEBUG   Faucet          processable request 0, address: rms1qrpp0ehfzgwx9872ky3tfdym78kt4q8wxramj7r65n5d5mf8c8skwal7f3a, amount: 1000000000
2023-10-24T17:55:28Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:55:28Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0xa1a0b493ee9f3b23468d0f27d56dec03b43a8b80ba7dfc9f29c19fd08ca207bc1e000000:30), txID: SignedTransactionID(0xfbb8eb56b17a78ca0fe0d333b4a26dc6da313082958deb58c5a8068245ab0cc817000000:23)
2023-10-24T17:55:28Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:55:28Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0xa1a0b493ee9f3b23468d0f27d56dec03b43a8b80ba7dfc9f29c19fd08ca207bc1e000000:30), txID: TransactionID(0xa858312f72e42182d36916214d5c476e61f304c1f913bf530cf8bc8a9e9fbfab17000000:23)
2023-10-24T17:55:29Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:55:29Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:55:29Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:55:31Z    DEBUG   Faucet  collected 1 requests
2023-10-24T17:55:31Z    DEBUG   Faucet  determined 1 available unspent outputs and 1 processable requests
2023-10-24T17:55:31Z    DEBUG   Faucet          unspent output 0, outputID: 0xa858312f72e42182d36916214d5c476e61f304c1f913bf530cf8bc8a9e9fbfab170000000100, amount: 999939000000000, mana: 175289971072
2023-10-24T17:55:31Z    DEBUG   Faucet          processable request 0, address: rms1qq7gzcjymnc9uyljp006zx639haqtfjlj62kgd9758wue308t9lgsageymk, amount: 1000000000
2023-10-24T17:55:31Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:55:31Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0x9ca59ea3930fec7ff64a58058dbf2bb522ee13ab945232086d7c280d6c2c277e1e000000:30), txID: SignedTransactionID(0x3c3e24c6a6a90e9b064ba4bb8f1550cc87fdfa89d4d2e5a53fef6297e9e40a0417000000:23)
2023-10-24T17:55:31Z    DEBUG   Faucet  entering checkPendingTransactionState...
2023-10-24T17:55:31Z    DEBUG   Faucet  checkPendingTransactionState: transaction still pending, blockID: BlockID(0x9ca59ea3930fec7ff64a58058dbf2bb522ee13ab945232086d7c280d6c2c277e1e000000:30), txID: TransactionID(0xff5569bf338e57ad2c2bdc0fb3a14d709cc807a18da3496dc1fcec6ed5b02e7617000000:23)
2023-10-24T17:55:31Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:55:31Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x9ca59ea3930fec7ff64a58058dbf2bb522ee13ab945232086d7c280d6c2c277e1e000000:30), txID: TransactionID(0xff5569bf338e57ad2c2bdc0fb3a14d709cc807a18da3496dc1fcec6ed5b02e7617000000:23)
2023-10-24T17:55:32Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:55:32Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:55:32Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x9ca59ea3930fec7ff64a58058dbf2bb522ee13ab945232086d7c280d6c2c277e1e000000:30), txID: TransactionID(0xff5569bf338e57ad2c2bdc0fb3a14d709cc807a18da3496dc1fcec6ed5b02e7617000000:23)
2023-10-24T17:55:33Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:55:33Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:55:35Z    DEBUG   Faucet  collected 2 requests
2023-10-24T17:55:35Z    DEBUG   Faucet  determined 1 available unspent outputs and 2 processable requests
2023-10-24T17:55:35Z    DEBUG   Faucet          unspent output 0, outputID: 0xff5569bf338e57ad2c2bdc0fb3a14d709cc807a18da3496dc1fcec6ed5b02e76170000000100, amount: 999938000000000, mana: 175285764572
2023-10-24T17:55:35Z    DEBUG   Faucet          processable request 0, address: rms1qz7s7sum37tn78gwq0wg4cmrgzma5pp4v6e9jrmug6nmzt78ufydse37zxr, amount: 1000000000
2023-10-24T17:55:35Z    DEBUG   Faucet          processable request 1, address: rms1qqh08r6xtzhap8h8wu6czqtlmjs9t2jftse6u0e8r0pd6wqus0vuj6vewtv, amount: 1000000000
2023-10-24T17:55:35Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:55:35Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0x90a064be7e0f6490c50564e4bc65ffe03524a5063dde16a6c4889a15d288b7881f000000:31), txID: SignedTransactionID(0xc088b831598ffe79c3e7c5a5e8e50b7e2ed3ecf1db0f9c7bb23eb883c9b9528a18000000:24)
2023-10-24T17:55:35Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:55:35Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x90a064be7e0f6490c50564e4bc65ffe03524a5063dde16a6c4889a15d288b7881f000000:31), txID: TransactionID(0x27fcdb20a9eefd0579e92ca2a4f779b119fe7e8a157159d4d264bb55362b23cc18000000:24)
2023-10-24T17:55:36Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:55:36Z    DEBUG   Faucet  entering checkPendingTransactionState...
2023-10-24T17:55:36Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:55:36Z    DEBUG   Faucet  checkPendingTransactionState: no pending transaction found
2023-10-24T17:55:36Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:55:38Z    DEBUG   Faucet  collected 1 requests
2023-10-24T17:55:38Z    DEBUG   Faucet  determined 1 available unspent outputs and 1 processable requests
2023-10-24T17:55:38Z    DEBUG   Faucet          unspent output 0, outputID: 0x27fcdb20a9eefd0579e92ca2a4f779b119fe7e8a157159d4d264bb55362b23cc180000000200, amount: 999936000000000, mana: 182909816080
2023-10-24T17:55:38Z    DEBUG   Faucet          processable request 0, address: rms1qppjgdcjcvdhpptv3g3lqecmqz3nck7hllh3pxmeaz97qkprnm6wutm5pk5, amount: 1000000000
2023-10-24T17:55:38Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:55:38Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0xf5348ceeb52cad87521f218bc4bb5c9ac74e55cdf42d86f619566368d8ae0b251f000000:31), txID: SignedTransactionID(0x5b4b7b764e13d7f33c62652b85d394263a94bae24b857c1c596af2ffb9cdfecf18000000:24)
2023-10-24T17:55:38Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:55:38Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0xf5348ceeb52cad87521f218bc4bb5c9ac74e55cdf42d86f619566368d8ae0b251f000000:31), txID: TransactionID(0xb02902ed56955d151bc9ce41d475dcbc3c20cf4c45f601d754be25229878096918000000:24)
2023-10-24T17:55:39Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:55:39Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:55:39Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:55:41Z    DEBUG   Faucet  collected 1 requests
2023-10-24T17:55:41Z    DEBUG   Faucet  determined 1 available unspent outputs and 1 processable requests
2023-10-24T17:55:41Z    DEBUG   Faucet          unspent output 0, outputID: 0xb02902ed56955d151bc9ce41d475dcbc3c20cf4c45f601d754be252298780969180000000100, amount: 999935000000000, mana: 182905609580
2023-10-24T17:55:41Z    DEBUG   Faucet          processable request 0, address: rms1qrvkmjtf3rc2m2h7dr6tdjfr66uvrrag52rwgnr4nvm85hy5vrn6wf5x2dt, amount: 1000000000
2023-10-24T17:55:41Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:55:41Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0x2b6b9d757ca4b107e6d1e5d1dd0d076300983d79442b599d7472a92a8fbde5851f000000:31), txID: SignedTransactionID(0xee121a79a3e0b6ed1ab5fb4337b35769ef91674ce933b11cf68aef6e5891afba18000000:24)
2023-10-24T17:55:41Z    DEBUG   Faucet  entering checkPendingTransactionState...
2023-10-24T17:55:41Z    DEBUG   Faucet  checkPendingTransactionState: transaction still pending, blockID: BlockID(0x2b6b9d757ca4b107e6d1e5d1dd0d076300983d79442b599d7472a92a8fbde5851f000000:31), txID: TransactionID(0x86e1a94ad5a927b009e8e050ab1caf732e56ee5e169e521dcbc36338c71cbe4018000000:24)
2023-10-24T17:55:41Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:55:41Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x2b6b9d757ca4b107e6d1e5d1dd0d076300983d79442b599d7472a92a8fbde5851f000000:31), txID: TransactionID(0x86e1a94ad5a927b009e8e050ab1caf732e56ee5e169e521dcbc36338c71cbe4018000000:24)
2023-10-24T17:55:42Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:55:42Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:55:42Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x2b6b9d757ca4b107e6d1e5d1dd0d076300983d79442b599d7472a92a8fbde5851f000000:31), txID: TransactionID(0x86e1a94ad5a927b009e8e050ab1caf732e56ee5e169e521dcbc36338c71cbe4018000000:24)
2023-10-24T17:55:43Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:55:43Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:55:45Z    DEBUG   Faucet  collected 2 requests
2023-10-24T17:55:45Z    DEBUG   Faucet  determined 1 available unspent outputs and 2 processable requests
2023-10-24T17:55:45Z    DEBUG   Faucet          unspent output 0, outputID: 0x86e1a94ad5a927b009e8e050ab1caf732e56ee5e169e521dcbc36338c71cbe40180000000100, amount: 999934000000000, mana: 182901403080
2023-10-24T17:55:45Z    DEBUG   Faucet          processable request 0, address: rms1qrthxnnd2xk320y7e895en0scx60knp478wa7hgfa4l5n8h64e7m70uxwaf, amount: 1000000000
2023-10-24T17:55:45Z    DEBUG   Faucet          processable request 1, address: rms1qzrzkuqk9gpv5mwnfs5fs904tqlgwnrftxr96722tj7q4zgw5sg2263smhg, amount: 1000000000
2023-10-24T17:55:45Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:55:45Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0xf1df44d171dc1c41d2b8834d566a6f6e72f4a1c713dae3473354e38e04bb6c5220000000:32), txID: SignedTransactionID(0x8a7c6eaa4bc713583c86c1f2e2601400a4c68b04a82b50ae33195c3efd43c37319000000:25)
2023-10-24T17:55:45Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:55:45Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0xf1df44d171dc1c41d2b8834d566a6f6e72f4a1c713dae3473354e38e04bb6c5220000000:32), txID: TransactionID(0x75496f9497e2face11fa75c1b827a58ba7807d5ab814766dbe459b11a50a604f19000000:25)
2023-10-24T17:55:46Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:55:46Z    DEBUG   Faucet  entering checkPendingTransactionState...
2023-10-24T17:55:46Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:55:46Z    DEBUG   Faucet  checkPendingTransactionState: no pending transaction found
2023-10-24T17:55:46Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:55:48Z    DEBUG   Faucet  collected 1 requests
2023-10-24T17:55:48Z    DEBUG   Faucet  determined 1 available unspent outputs and 1 processable requests
2023-10-24T17:55:48Z    DEBUG   Faucet          unspent output 0, outputID: 0x75496f9497e2face11fa75c1b827a58ba7807d5ab814766dbe459b11a50a604f190000000200, amount: 999932000000000, mana: 190525424071
2023-10-24T17:55:48Z    DEBUG   Faucet          processable request 0, address: rms1qqekpmwrafhmnd4546nxrshpqume070l2n0l7lgw38e09pr48cv3uejuznc, amount: 1000000000
2023-10-24T17:55:48Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:55:48Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0xc5ef052fad4188a30f7a04050fd0bf0f7c9c798f0e0d979ef20c2ff0da3dfdb820000000:32), txID: SignedTransactionID(0x14791d416d4242f5a2ebf2d44bfae88c3798584dee46578f927e2d85d6e55e4a19000000:25)
2023-10-24T17:55:48Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:55:48Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0xc5ef052fad4188a30f7a04050fd0bf0f7c9c798f0e0d979ef20c2ff0da3dfdb820000000:32), txID: TransactionID(0xd440c3f4ab7109423bb93385b9d954db3db4da0941c95676035daf2fead5ed4219000000:25)
2023-10-24T17:55:49Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:55:49Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:55:49Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:55:51Z    DEBUG   Faucet  collected 1 requests
2023-10-24T17:55:51Z    DEBUG   Faucet  determined 1 available unspent outputs and 1 processable requests
2023-10-24T17:55:51Z    DEBUG   Faucet          unspent output 0, outputID: 0xd440c3f4ab7109423bb93385b9d954db3db4da0941c95676035daf2fead5ed42190000000100, amount: 999931000000000, mana: 190521217571
2023-10-24T17:55:51Z    DEBUG   Faucet          processable request 0, address: rms1qqth8s06dxu5t8lxns4nh2249wlmc6flch7mc24f72hhsdfxdmps2v20a3p, amount: 1000000000
2023-10-24T17:55:51Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:55:51Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0xd53be7fed3378beff21f3feefa48192d5685ce20e05b4c969ff26e5154c9b7e220000000:32), txID: SignedTransactionID(0x878d12747beac39631ed611111094938708083810d05ea1a144c673b0a2211aa19000000:25)
2023-10-24T17:55:51Z    DEBUG   Faucet  entering checkPendingTransactionState...
2023-10-24T17:55:51Z    DEBUG   Faucet  checkPendingTransactionState: transaction still pending, blockID: BlockID(0xd53be7fed3378beff21f3feefa48192d5685ce20e05b4c969ff26e5154c9b7e220000000:32), txID: TransactionID(0xe6256f61b70012feab104ca0fdc2d5e8be798033415de26512101833be99e7d019000000:25)
2023-10-24T17:55:51Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:55:51Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0xd53be7fed3378beff21f3feefa48192d5685ce20e05b4c969ff26e5154c9b7e220000000:32), txID: TransactionID(0xe6256f61b70012feab104ca0fdc2d5e8be798033415de26512101833be99e7d019000000:25)
2023-10-24T17:55:52Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:55:52Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:55:52Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0xd53be7fed3378beff21f3feefa48192d5685ce20e05b4c969ff26e5154c9b7e220000000:32), txID: TransactionID(0xe6256f61b70012feab104ca0fdc2d5e8be798033415de26512101833be99e7d019000000:25)
2023-10-24T17:55:53Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:55:53Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:55:55Z    DEBUG   Faucet  collected 2 requests
2023-10-24T17:55:55Z    DEBUG   Faucet  determined 1 available unspent outputs and 2 processable requests
2023-10-24T17:55:55Z    DEBUG   Faucet          unspent output 0, outputID: 0xe6256f61b70012feab104ca0fdc2d5e8be798033415de26512101833be99e7d0190000000100, amount: 999930000000000, mana: 190517011071
2023-10-24T17:55:55Z    DEBUG   Faucet          processable request 0, address: rms1qqazcep9rax0l3pa0pk0vkl9p26qztpsc0hg0r7srtpahm2efdmtus9frma, amount: 1000000000
2023-10-24T17:55:55Z    DEBUG   Faucet          processable request 1, address: rms1qz2z45wt8428wr8mnm9jf4v9jem5vf2439rua7uyg3v2zk8s7vz9saal25s, amount: 1000000000
2023-10-24T17:55:55Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:55:55Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0x3a0252e557f6c3b6b1e223feb96916c1bd709c78164dae849d1b4530dce6892621000000:33), txID: SignedTransactionID(0x0339454c2fc4c5160b0ed6e94fab3e1515f6120565f87b5cf2daa0975a5533fc1a000000:26)
2023-10-24T17:55:55Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:55:55Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x3a0252e557f6c3b6b1e223feb96916c1bd709c78164dae849d1b4530dce6892621000000:33), txID: TransactionID(0xe926f12862a9c610f214000c578835e64cc0c479b1da5b9d52be8668f56a0acf1a000000:26)
2023-10-24T17:55:56Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:55:56Z    DEBUG   Faucet  entering checkPendingTransactionState...
2023-10-24T17:55:56Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:55:56Z    DEBUG   Faucet  checkPendingTransactionState: no pending transaction found
2023-10-24T17:55:56Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:55:58Z    DEBUG   Faucet  collected 1 requests
2023-10-24T17:55:58Z    DEBUG   Faucet  determined 1 available unspent outputs and 1 processable requests
2023-10-24T17:55:58Z    DEBUG   Faucet          unspent output 0, outputID: 0xe926f12862a9c610f214000c578835e64cc0c479b1da5b9d52be8668f56a0acf1a0000000200, amount: 999928000000000, mana: 198141001544
2023-10-24T17:55:58Z    DEBUG   Faucet          processable request 0, address: rms1qzauw2vcgup99cxt6rymgy67z50ejs82s03lcx6cxhjpgq3ud78hynh5el9, amount: 1000000000
2023-10-24T17:55:58Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:55:58Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0xfd04c1b8f5426d43b8bf54656c0e09925d2af06587aa3e051300dfdaa9ad700721000000:33), txID: SignedTransactionID(0x89335c32b72fc5fc9362a370ef2097deb1d8e3abee36c885013dd48f7975833e1a000000:26)
2023-10-24T17:55:58Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:55:58Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0xfd04c1b8f5426d43b8bf54656c0e09925d2af06587aa3e051300dfdaa9ad700721000000:33), txID: TransactionID(0xa425b4c0c888383a8b4500208d91d469355b694ccfbfec7dfcc2e3b48ae648171a000000:26)
2023-10-24T17:55:59Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:55:59Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:55:59Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:56:01Z    DEBUG   Faucet  collected 1 requests
2023-10-24T17:56:01Z    DEBUG   Faucet  determined 1 available unspent outputs and 1 processable requests
2023-10-24T17:56:01Z    DEBUG   Faucet          unspent output 0, outputID: 0xa425b4c0c888383a8b4500208d91d469355b694ccfbfec7dfcc2e3b48ae648171a0000000100, amount: 999927000000000, mana: 198136795044
2023-10-24T17:56:01Z    DEBUG   Faucet          processable request 0, address: rms1qr862kxe8gfka7dv5mg0zs5uamm5fdn2gqajmvvc944lmrkleggl632xf8f, amount: 1000000000
2023-10-24T17:56:01Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:56:02Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0x875726b9ddcec9f60abb8ed2f86e7b9702ffbd52c79f3bf7a91c7aa38edd4e7b21000000:33), txID: SignedTransactionID(0xaa1f05984f006d17d731008fcc036a617bec4ee55389e361b034ddb3ef8502501a000000:26)
2023-10-24T17:56:02Z    DEBUG   Faucet  entering checkPendingTransactionState...
2023-10-24T17:56:02Z    WARN    Faucet  transaction failed, blockID: BlockID(0x875726b9ddcec9f60abb8ed2f86e7b9702ffbd52c79f3bf7a91c7aa38edd4e7b21000000:33), txID: TransactionID(0x9f95e853b9a719b757148fa7fe7dd65a12371d8d8191f5570dfbe3f057fe05a41a000000:26), reason: 2
2023-10-24T17:56:02Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:56:02Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:56:04Z    DEBUG   Faucet  collected 2 requests
2023-10-24T17:56:04Z    DEBUG   Faucet  determined 1 available unspent outputs and 2 processable requests
2023-10-24T17:56:04Z    DEBUG   Faucet          unspent output 0, outputID: 0x9f95e853b9a719b757148fa7fe7dd65a12371d8d8191f5570dfbe3f057fe05a41a0000000100, amount: 999926000000000, mana: 198132588544
2023-10-24T17:56:04Z    DEBUG   Faucet          processable request 0, address: rms1qr862kxe8gfka7dv5mg0zs5uamm5fdn2gqajmvvc944lmrkleggl632xf8f, amount: 1000000000
2023-10-24T17:56:04Z    DEBUG   Faucet          processable request 1, address: rms1qzvfsktwxdal3g8h3ecaqj6wv2vt3f9q4muam2ysm6axewyvzzgxcfjsytc, amount: 1000000000
2023-10-24T17:56:04Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:56:04Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0x9f9fa839660af1ff5aa1637ed4688703372ce8754952e2ba848fac40ef77723722000000:34), txID: SignedTransactionID(0x01cb902efa7c9bbcdf9545550d74cf8063d1629ec0dfff2568e1ca2007def2df1a000000:26)
2023-10-24T17:56:04Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:56:04Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x9f9fa839660af1ff5aa1637ed4688703372ce8754952e2ba848fac40ef77723722000000:34), txID: TransactionID(0x86a833f255e358c0b5a97081689d73364c324913e5f724e50f08e4f58de79f641a000000:26)
2023-10-24T17:56:05Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:56:05Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x9f9fa839660af1ff5aa1637ed4688703372ce8754952e2ba848fac40ef77723722000000:34), txID: TransactionID(0x86a833f255e358c0b5a97081689d73364c324913e5f724e50f08e4f58de79f641a000000:26)
2023-10-24T17:56:05Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:56:06Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:56:06Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x9f9fa839660af1ff5aa1637ed4688703372ce8754952e2ba848fac40ef77723722000000:34), txID: TransactionID(0x86a833f255e358c0b5a97081689d73364c324913e5f724e50f08e4f58de79f641a000000:26)
2023-10-24T17:56:07Z    DEBUG   Faucet  entering checkPendingTransactionState...
2023-10-24T17:56:07Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:56:07Z    DEBUG   Faucet  checkPendingTransactionState: no pending transaction found
2023-10-24T17:56:07Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:56:09Z    DEBUG   Faucet  collected 2 requests
2023-10-24T17:56:09Z    DEBUG   Faucet  determined 1 available unspent outputs and 2 processable requests
2023-10-24T17:56:09Z    DEBUG   Faucet          unspent output 0, outputID: 0x86a833f255e358c0b5a97081689d73364c324913e5f724e50f08e4f58de79f641a0000000200, amount: 999924000000000, mana: 198127718544
2023-10-24T17:56:09Z    DEBUG   Faucet          processable request 0, address: rms1qr5wp7x8j56kr0dl2cpr49zyc0fqqjjx7w2d7us947w7g9de4hlrush2xrh, amount: 1000000000
2023-10-24T17:56:09Z    DEBUG   Faucet          processable request 1, address: rms1qp5pmjjqde28tmx4pq6euxsjnjyu6lpamld92ez72azdj7amggmlshx2073, amount: 1000000000
2023-10-24T17:56:09Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:56:09Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0x5a0e155b5cbf74bfeb71e3f719924f21e6c201b89f71a2f138d7e5351a1e614522000000:34), txID: SignedTransactionID(0x18b174b8b2982d1d63240e3331ae21fce6cafab16b30207444ea7b7529f6eff61b000000:27)
2023-10-24T17:56:09Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:56:09Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x5a0e155b5cbf74bfeb71e3f719924f21e6c201b89f71a2f138d7e5351a1e614522000000:34), txID: TransactionID(0x997c85fa55a37c4ed56e4b5cb1545eb9510e2d02c2faecd4240556dddf5208ea1b000000:27)
2023-10-24T17:56:09Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:56:10Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:56:10Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:56:12Z    DEBUG   Faucet  collected 1 requests
2023-10-24T17:56:12Z    DEBUG   Faucet  determined 1 available unspent outputs and 1 processable requests
2023-10-24T17:56:12Z    DEBUG   Faucet          unspent output 0, outputID: 0x997c85fa55a37c4ed56e4b5cb1545eb9510e2d02c2faecd4240556dddf5208ea1b0000000200, amount: 999922000000000, mana: 205751663241
2023-10-24T17:56:12Z    DEBUG   Faucet          processable request 0, address: rms1qpsmjfc6vp4uhcv648rdm59v6jdgs3ns4wzklgzjrzka3nygvnmyz3zr9a9, amount: 1000000000
2023-10-24T17:56:12Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:56:12Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0x1f22c2ef2e1c81b9d5b804a117abcd7ad95c986df4d94fe010b97ac25b7b7da722000000:34), txID: SignedTransactionID(0x5b286923e0cb014b3d11343d267b91f87c5cc255fe617c24f94743dbdf00d4651b000000:27)
2023-10-24T17:56:12Z    DEBUG   Faucet  entering checkPendingTransactionState...
2023-10-24T17:56:12Z    WARN    Faucet  transaction failed, blockID: BlockID(0x1f22c2ef2e1c81b9d5b804a117abcd7ad95c986df4d94fe010b97ac25b7b7da722000000:34), txID: TransactionID(0xfa576627f9a387c6efa83d0a9057304f305c02bae22a53b58c2f8127b7700fb51b000000:27), reason: 2
2023-10-24T17:56:12Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:56:12Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:56:14Z    DEBUG   Faucet  collected 2 requests
2023-10-24T17:56:14Z    DEBUG   Faucet  determined 1 available unspent outputs and 2 processable requests
2023-10-24T17:56:14Z    DEBUG   Faucet          unspent output 0, outputID: 0xfa576627f9a387c6efa83d0a9057304f305c02bae22a53b58c2f8127b7700fb51b0000000100, amount: 999921000000000, mana: 205747456741
2023-10-24T17:56:14Z    DEBUG   Faucet          processable request 0, address: rms1qpsmjfc6vp4uhcv648rdm59v6jdgs3ns4wzklgzjrzka3nygvnmyz3zr9a9, amount: 1000000000
2023-10-24T17:56:14Z    DEBUG   Faucet          processable request 1, address: rms1qzturg99j2e97yuagdj3ewvvv2ysu5dummfjefl7k95hsjmkv7gtqh48zxp, amount: 1000000000
2023-10-24T17:56:14Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:56:14Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0x80721b9c6604229f6f3bc4b73a3c880a61f0e4faec1ca40de05271b218dcb32b23000000:35), txID: SignedTransactionID(0x3855a689adf269f1fa8f6fe33f7d66e397cbf1ab8549422ecca38836daabcb2b1b000000:27)
2023-10-24T17:56:14Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:56:14Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x80721b9c6604229f6f3bc4b73a3c880a61f0e4faec1ca40de05271b218dcb32b23000000:35), txID: TransactionID(0xa52e7972e54d4eaddd510b4dfebd964b21ae306f7861cb79e02c64bb9ece1f681b000000:27)
2023-10-24T17:56:15Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:56:15Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x80721b9c6604229f6f3bc4b73a3c880a61f0e4faec1ca40de05271b218dcb32b23000000:35), txID: TransactionID(0xa52e7972e54d4eaddd510b4dfebd964b21ae306f7861cb79e02c64bb9ece1f681b000000:27)
2023-10-24T17:56:15Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:56:16Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:56:16Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x80721b9c6604229f6f3bc4b73a3c880a61f0e4faec1ca40de05271b218dcb32b23000000:35), txID: TransactionID(0xa52e7972e54d4eaddd510b4dfebd964b21ae306f7861cb79e02c64bb9ece1f681b000000:27)
2023-10-24T17:56:17Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:56:17Z    DEBUG   Faucet  entering checkPendingTransactionState...
2023-10-24T17:56:17Z    DEBUG   Faucet  checkPendingTransactionState: no pending transaction found
2023-10-24T17:56:17Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:56:19Z    DEBUG   Faucet  collected 2 requests
2023-10-24T17:56:19Z    DEBUG   Faucet  determined 1 available unspent outputs and 2 processable requests
2023-10-24T17:56:19Z    DEBUG   Faucet          unspent output 0, outputID: 0xa52e7972e54d4eaddd510b4dfebd964b21ae306f7861cb79e02c64bb9ece1f681b0000000200, amount: 999919000000000, mana: 205742586741
2023-10-24T17:56:19Z    DEBUG   Faucet          processable request 0, address: rms1qq29ga42vqf2xtxn9epmhhcp3f90te29hpsax9cgwl4ms474dvq8kazqaz0, amount: 1000000000
2023-10-24T17:56:19Z    DEBUG   Faucet          processable request 1, address: rms1qza4ugtjthejdu8tn38dejtg23nc5wfumwtpu5gge4kxes7ecsw77gsckqj, amount: 1000000000
2023-10-24T17:56:19Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:56:19Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0x368374949f9b9f6f64f4ab0d43b2c101959d04ccf8c9ebd81099bba6ad0c520423000000:35), txID: SignedTransactionID(0xba094f0ac01ba4b393dcf9675bbd295f45298bddc67bd247fa87d4bb051f841e1c000000:28)
2023-10-24T17:56:19Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:56:19Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x368374949f9b9f6f64f4ab0d43b2c101959d04ccf8c9ebd81099bba6ad0c520423000000:35), txID: TransactionID(0x8fe7e10b3f1b306412631b788fb66c4e1398d9fdb07e5cca07f9e1be8e8d3a051c000000:28)
2023-10-24T17:56:19Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:56:20Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:56:20Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:56:22Z    DEBUG   Faucet  collected 1 requests
2023-10-24T17:56:22Z    DEBUG   Faucet  determined 1 available unspent outputs and 1 processable requests
2023-10-24T17:56:22Z    DEBUG   Faucet          unspent output 0, outputID: 0x8fe7e10b3f1b306412631b788fb66c4e1398d9fdb07e5cca07f9e1be8e8d3a051c0000000200, amount: 999917000000000, mana: 213366493291
2023-10-24T17:56:22Z    DEBUG   Faucet          processable request 0, address: rms1qrn7avskffdky6es4en8usjfrkkwdd5yvzlfgx9txdx266ql4ceaw4p7g37, amount: 1000000000
2023-10-24T17:56:22Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:56:22Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0x881d9aaf316dab6035ebbe0e9de899ca9828d7c39612cb7fd5ddf443464be7c723000000:35), txID: SignedTransactionID(0x790373d8d5a1270685b5271e71e8321affad8748119f4a9b2aaec5843045d61f1c000000:28)
2023-10-24T17:56:22Z    DEBUG   Faucet  entering checkPendingTransactionState...
2023-10-24T17:56:22Z    DEBUG   Faucet  checkPendingTransactionState: transaction still pending, blockID: BlockID(0x881d9aaf316dab6035ebbe0e9de899ca9828d7c39612cb7fd5ddf443464be7c723000000:35), txID: TransactionID(0x23cf89371bcd6957360c0c39b302955b8a2a084a3921dd4d63df92857d473b641c000000:28)
2023-10-24T17:56:22Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:56:22Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x881d9aaf316dab6035ebbe0e9de899ca9828d7c39612cb7fd5ddf443464be7c723000000:35), txID: TransactionID(0x23cf89371bcd6957360c0c39b302955b8a2a084a3921dd4d63df92857d473b641c000000:28)
2023-10-24T17:56:22Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:56:23Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:56:23Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x881d9aaf316dab6035ebbe0e9de899ca9828d7c39612cb7fd5ddf443464be7c723000000:35), txID: TransactionID(0x23cf89371bcd6957360c0c39b302955b8a2a084a3921dd4d63df92857d473b641c000000:28)
2023-10-24T17:56:24Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:56:24Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:56:26Z    DEBUG   Faucet  collected 2 requests
2023-10-24T17:56:26Z    DEBUG   Faucet  determined 1 available unspent outputs and 2 processable requests
2023-10-24T17:56:26Z    DEBUG   Faucet          unspent output 0, outputID: 0x23cf89371bcd6957360c0c39b302955b8a2a084a3921dd4d63df92857d473b641c0000000100, amount: 999916000000000, mana: 213362286791
2023-10-24T17:56:26Z    DEBUG   Faucet          processable request 0, address: rms1qrhwzwk6ackrd9sljc47ka7kq8499ckqzc9vwcjqguc6waa6m7yzctzs0q7, amount: 1000000000
2023-10-24T17:56:26Z    DEBUG   Faucet          processable request 1, address: rms1qr0vh9w84d0nxpq2pffmg8clqxdtqqys4h6jzuy5ht5zxht204j47tvefuc, amount: 1000000000
2023-10-24T17:56:26Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:56:26Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0x6b08b1da67ec9a93e1ed5da2ca038085b109fd3312ef291c0a78b620b411336024000000:36), txID: SignedTransactionID(0x5822a038c646d9f79e5a489743429390963e1e12fffa3f6ed138b97cbb1195361d000000:29)
2023-10-24T17:56:26Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:56:26Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x6b08b1da67ec9a93e1ed5da2ca038085b109fd3312ef291c0a78b620b411336024000000:36), txID: TransactionID(0x84adb4515d5f6bec657b5e8db58a979d8622d1723c9c58c7bee319b775a299891d000000:29)
2023-10-24T17:56:26Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:56:27Z    DEBUG   Faucet  entering checkPendingTransactionState...
2023-10-24T17:56:27Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:56:27Z    DEBUG   Faucet  checkPendingTransactionState: no pending transaction found
2023-10-24T17:56:27Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:56:29Z    DEBUG   Faucet  collected 1 requests
2023-10-24T17:56:29Z    DEBUG   Faucet  determined 1 available unspent outputs and 1 processable requests
2023-10-24T17:56:29Z    DEBUG   Faucet          unspent output 0, outputID: 0x84adb4515d5f6bec657b5e8db58a979d8622d1723c9c58c7bee319b775a299891d0000000200, amount: 999914000000000, mana: 220986170453
2023-10-24T17:56:29Z    DEBUG   Faucet          processable request 0, address: rms1qzwhchwx470e3e86te8nq73ksv4pwa3dqmm66kvpdtsmhntw466nc2nuwth, amount: 1000000000
2023-10-24T17:56:29Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:56:29Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0xb17c02b644270ad7da849749bc15883f1da9204f4aba0c24a68a35de3b9e7cfc24000000:36), txID: SignedTransactionID(0xf3b680a78241727bab8a718d2936afe347cba1f5af11dbbf482b10315021bf201d000000:29)
2023-10-24T17:56:29Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:56:29Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0xb17c02b644270ad7da849749bc15883f1da9204f4aba0c24a68a35de3b9e7cfc24000000:36), txID: TransactionID(0xeac62ddf47f92d19e638ba70bbb8f24a85d04126650d4ea3ee9756fda224b3ce1d000000:29)
2023-10-24T17:56:29Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:56:30Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:56:30Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:56:32Z    DEBUG   Faucet  collected 1 requests
2023-10-24T17:56:32Z    DEBUG   Faucet  determined 1 available unspent outputs and 1 processable requests
2023-10-24T17:56:32Z    DEBUG   Faucet          unspent output 0, outputID: 0xeac62ddf47f92d19e638ba70bbb8f24a85d04126650d4ea3ee9756fda224b3ce1d0000000100, amount: 999913000000000, mana: 220981963953
2023-10-24T17:56:32Z    DEBUG   Faucet          processable request 0, address: rms1qp6va005z722jw2uvt8jqc0msf6jr28nkv5wshpd36kjazdpqmagk2ukj5j, amount: 1000000000
2023-10-24T17:56:32Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:56:32Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0x5703ae4fc0a63171d316c527ea61a00e1d749aebb58d07d2ae2ecc9e12c5d6c924000000:36), txID: SignedTransactionID(0x6e0e83add3e5997481cbb6c843e680ee2cdd805480570061af049bccd6d351cc1d000000:29)
2023-10-24T17:56:32Z    DEBUG   Faucet  entering checkPendingTransactionState...
2023-10-24T17:56:32Z    WARN    Faucet  transaction failed, blockID: BlockID(0x5703ae4fc0a63171d316c527ea61a00e1d749aebb58d07d2ae2ecc9e12c5d6c924000000:36), txID: TransactionID(0x1f7a8d436405a7a37832742cdc6fff41ad9ac9a55566c649ba958a970b7926311d000000:29), reason: 2
2023-10-24T17:56:32Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:56:32Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:56:34Z    DEBUG   Faucet  collected 2 requests
2023-10-24T17:56:34Z    DEBUG   Faucet  determined 1 available unspent outputs and 2 processable requests
2023-10-24T17:56:34Z    DEBUG   Faucet          unspent output 0, outputID: 0x1f7a8d436405a7a37832742cdc6fff41ad9ac9a55566c649ba958a970b7926311d0000000100, amount: 999912000000000, mana: 220977757453
2023-10-24T17:56:34Z    DEBUG   Faucet          processable request 0, address: rms1qp6va005z722jw2uvt8jqc0msf6jr28nkv5wshpd36kjazdpqmagk2ukj5j, amount: 1000000000
2023-10-24T17:56:34Z    DEBUG   Faucet          processable request 1, address: rms1qrh2a48kyhsudglhr6958q5tc90c4qnksvzruqde92n2ua0594rk5n3ulhx, amount: 1000000000
2023-10-24T17:56:34Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:56:34Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0xef5f954f0059999562490f6dddc467225191923a6b7fb985f9fbe651d885c59b25000000:37), txID: SignedTransactionID(0x6a73cb2cd85b6567f433601d7f6a253f1481a7d750ed3fe8a09801face5f8cc61d000000:29)
2023-10-24T17:56:34Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:56:34Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0xef5f954f0059999562490f6dddc467225191923a6b7fb985f9fbe651d885c59b25000000:37), txID: TransactionID(0x1986a4f8726544cc098a1989581f31a374af72d272fbf210a9deaaede99763531d000000:29)
2023-10-24T17:56:35Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:56:35Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0xef5f954f0059999562490f6dddc467225191923a6b7fb985f9fbe651d885c59b25000000:37), txID: TransactionID(0x1986a4f8726544cc098a1989581f31a374af72d272fbf210a9deaaede99763531d000000:29)
2023-10-24T17:56:35Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:56:36Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:56:36Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0xef5f954f0059999562490f6dddc467225191923a6b7fb985f9fbe651d885c59b25000000:37), txID: TransactionID(0x1986a4f8726544cc098a1989581f31a374af72d272fbf210a9deaaede99763531d000000:29)
2023-10-24T17:56:37Z    DEBUG   Faucet  entering checkPendingTransactionState...
2023-10-24T17:56:37Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:56:37Z    DEBUG   Faucet  checkPendingTransactionState: no pending transaction found
2023-10-24T17:56:37Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:56:39Z    DEBUG   Faucet  collected 2 requests
2023-10-24T17:56:39Z    DEBUG   Faucet  determined 1 available unspent outputs and 2 processable requests
2023-10-24T17:56:39Z    DEBUG   Faucet          unspent output 0, outputID: 0x1986a4f8726544cc098a1989581f31a374af72d272fbf210a9deaaede99763531d0000000200, amount: 999910000000000, mana: 220972887453
2023-10-24T17:56:39Z    DEBUG   Faucet          processable request 0, address: rms1qqsl2fsr0xmnjcz0lvpy7qntvn825r2r3uqurvhfj9e8ctsmtl76xka8zvz, amount: 1000000000
2023-10-24T17:56:39Z    DEBUG   Faucet          processable request 1, address: rms1qrfrzxkjp6xqc9huzs0zy57kqpzg8j5wrm77g0pfh02kjuudfjqxvnd579z, amount: 1000000000
2023-10-24T17:56:39Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:56:39Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0xd9e60cfbdbeebd93f7d7021e202c7782cf9156276121bf334a5ba38dd203983425000000:37), txID: SignedTransactionID(0x6a6629a327927fb58e549b1053c966a3073a578a4bcfae40629c51525de0da751e000000:30)
2023-10-24T17:56:39Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:56:39Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0xd9e60cfbdbeebd93f7d7021e202c7782cf9156276121bf334a5ba38dd203983425000000:37), txID: TransactionID(0xad35efe15249bbd9445cf8bb5edc45e908359e7189e185f0ad77b6fc8f2cd3db1e000000:30)
2023-10-24T17:56:39Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:56:40Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:56:40Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:56:42Z    DEBUG   Faucet  collected 1 requests
2023-10-24T17:56:42Z    DEBUG   Faucet  determined 1 available unspent outputs and 1 processable requests
2023-10-24T17:56:42Z    DEBUG   Faucet          unspent output 0, outputID: 0xad35efe15249bbd9445cf8bb5edc45e908359e7189e185f0ad77b6fc8f2cd3db1e0000000200, amount: 999908000000000, mana: 228596725338
2023-10-24T17:56:42Z    DEBUG   Faucet          processable request 0, address: rms1qr2ms3xgwuxruz0t0hnmdqwwtjq9tnvqu0wwvmtefpn7gq6lc7ql5z9lpqg, amount: 1000000000
2023-10-24T17:56:42Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:56:42Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0x32a6e5a497133c1cbabc6c0744d425919cb10a873487156b42781f4afdcdfdd225000000:37), txID: SignedTransactionID(0xa2d61220adae9c54eb636575e0ada2a1fd6bc2145ad659e4e1a2fb545951a2601e000000:30)
2023-10-24T17:56:42Z    DEBUG   Faucet  entering checkPendingTransactionState...
2023-10-24T17:56:42Z    DEBUG   Faucet  checkPendingTransactionState: transaction still pending, blockID: BlockID(0x32a6e5a497133c1cbabc6c0744d425919cb10a873487156b42781f4afdcdfdd225000000:37), txID: TransactionID(0xffbffc40e0f591eaf1cd43d1b1a444d9cbb929e1fb4f8daf857e5a97900555141e000000:30)
2023-10-24T17:56:42Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:56:42Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x32a6e5a497133c1cbabc6c0744d425919cb10a873487156b42781f4afdcdfdd225000000:37), txID: TransactionID(0xffbffc40e0f591eaf1cd43d1b1a444d9cbb929e1fb4f8daf857e5a97900555141e000000:30)
2023-10-24T17:56:42Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:56:43Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:56:43Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x32a6e5a497133c1cbabc6c0744d425919cb10a873487156b42781f4afdcdfdd225000000:37), txID: TransactionID(0xffbffc40e0f591eaf1cd43d1b1a444d9cbb929e1fb4f8daf857e5a97900555141e000000:30)
2023-10-24T17:56:44Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:56:44Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:56:46Z    DEBUG   Faucet  collected 2 requests
2023-10-24T17:56:46Z    DEBUG   Faucet  determined 1 available unspent outputs and 2 processable requests
2023-10-24T17:56:46Z    DEBUG   Faucet          unspent output 0, outputID: 0xffbffc40e0f591eaf1cd43d1b1a444d9cbb929e1fb4f8daf857e5a97900555141e0000000100, amount: 999907000000000, mana: 228592518838
2023-10-24T17:56:46Z    DEBUG   Faucet          processable request 0, address: rms1qp7vjx5g8xqfsma253grtsc938zn2lm5rmxxhg09py6glkmmaayh270n4pz, amount: 1000000000
2023-10-24T17:56:46Z    DEBUG   Faucet          processable request 1, address: rms1qqjxwryak75et529e6skwrp7ktke8xek6dw7jl8v9jjl0nlqdndh6he7akz, amount: 1000000000
2023-10-24T17:56:46Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:56:46Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0x39f54aaafa647daf8d2f7945fa015bbcd659024a640b93c9625e242e49c501e626000000:38), txID: SignedTransactionID(0xc0ccd23b16915df9caa5456e2f478b82b0233718b5e10dd787dabf5ce23791401f000000:31)
2023-10-24T17:56:46Z    DEBUG   Faucet  entering checkPendingTransactionState...
2023-10-24T17:56:46Z    DEBUG   Faucet  checkPendingTransactionState: transaction still pending, blockID: BlockID(0x39f54aaafa647daf8d2f7945fa015bbcd659024a640b93c9625e242e49c501e626000000:38), txID: TransactionID(0xe4c4f0f644203686582e986715adb36f059cad4eb29c4290649a637c059a68d71f000000:31)
2023-10-24T17:56:46Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:56:46Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x39f54aaafa647daf8d2f7945fa015bbcd659024a640b93c9625e242e49c501e626000000:38), txID: TransactionID(0xe4c4f0f644203686582e986715adb36f059cad4eb29c4290649a637c059a68d71f000000:31)
2023-10-24T17:56:46Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:56:47Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:56:47Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x39f54aaafa647daf8d2f7945fa015bbcd659024a640b93c9625e242e49c501e626000000:38), txID: TransactionID(0xe4c4f0f644203686582e986715adb36f059cad4eb29c4290649a637c059a68d71f000000:31)
2023-10-24T17:56:48Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:56:48Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:56:50Z    DEBUG   Faucet  collected 2 requests
2023-10-24T17:56:50Z    DEBUG   Faucet  determined 1 available unspent outputs and 2 processable requests
2023-10-24T17:56:50Z    DEBUG   Faucet          unspent output 0, outputID: 0xe4c4f0f644203686582e986715adb36f059cad4eb29c4290649a637c059a68d71f0000000200, amount: 999905000000000, mana: 236216333835
2023-10-24T17:56:50Z    DEBUG   Faucet          processable request 0, address: rms1qqnvqfhctgsmtuudww4edvwlj3u00ghp3v5df9wpc664vdl6djte72mxf96, amount: 1000000000
2023-10-24T17:56:50Z    DEBUG   Faucet          processable request 1, address: rms1qr6dgc8vec0ps5jyva2fwk33wtxmdmeq285e4a8ljdgpdz6qwfq6wjcku6f, amount: 1000000000
2023-10-24T17:56:50Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:56:50Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0x843a375d994eacd0bb9e1844fc7f3b124bd8596c0fd57dcd70889d44101d02c826000000:38), txID: SignedTransactionID(0xc5e110da231293b558d18566bb7b24076ff0e627fb22179b4872fb101582399b1f000000:31)
2023-10-24T17:56:50Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:56:50Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x843a375d994eacd0bb9e1844fc7f3b124bd8596c0fd57dcd70889d44101d02c826000000:38), txID: TransactionID(0xbec6b17cd632faa626609359ac84a0fbd0b94cc3e2b0368f1861187ec5762dfb1f000000:31)
2023-10-24T17:56:50Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:56:51Z    DEBUG   Faucet  entering checkPendingTransactionState...
2023-10-24T17:56:51Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:56:51Z    DEBUG   Faucet  checkPendingTransactionState: no pending transaction found
2023-10-24T17:56:51Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:56:53Z    DEBUG   Faucet  collected 1 requests
2023-10-24T17:56:53Z    DEBUG   Faucet  determined 1 available unspent outputs and 1 processable requests
2023-10-24T17:56:53Z    DEBUG   Faucet          unspent output 0, outputID: 0xbec6b17cd632faa626609359ac84a0fbd0b94cc3e2b0368f1861187ec5762dfb1f0000000200, amount: 999903000000000, mana: 236211463835
2023-10-24T17:56:53Z    DEBUG   Faucet          processable request 0, address: rms1qzxx5gkxescysnt87rvnhhnakqe73ajuj7sqcg2rh3anky8kyreq2zuvtcm, amount: 1000000000
2023-10-24T17:56:53Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:56:53Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0xa3346387be42a00897bcb436fea1973dec08dd68c56f518cf4fc28444c70421226000000:38), txID: SignedTransactionID(0xb532647615f6c3e9fc3c3dff7136ebda54568a1ff537a658fc729b0374b23c711f000000:31)
2023-10-24T17:56:53Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:56:53Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0xa3346387be42a00897bcb436fea1973dec08dd68c56f518cf4fc28444c70421226000000:38), txID: TransactionID(0x1410b7fc7b5e1fd894465f7fb5b35817d8b09aa00ca3da1793706cf9f3c3a1131f000000:31)
2023-10-24T17:56:53Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:56:54Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:56:54Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:56:56Z    DEBUG   Faucet  collected 1 requests
2023-10-24T17:56:56Z    DEBUG   Faucet  determined 1 available unspent outputs and 1 processable requests
2023-10-24T17:56:56Z    DEBUG   Faucet          unspent output 0, outputID: 0x1410b7fc7b5e1fd894465f7fb5b35817d8b09aa00ca3da1793706cf9f3c3a1131f0000000100, amount: 999902000000000, mana: 236207257335
2023-10-24T17:56:56Z    DEBUG   Faucet          processable request 0, address: rms1qzu8kn6rtl0xkd4wnmqjn7srs4ry6tk9hsdkckhrcwfpg3kdfnwn6a0llyg, amount: 1000000000
2023-10-24T17:56:56Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:56:56Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0x86b89588fe1bb294759f0d0ddfc68ef6412ce40e7d706938e346f7d217acf15d27000000:39), txID: SignedTransactionID(0xcbba8a6cdc7144944eab1fcca81c5a8f9e2da8ee8ec946e4a1191d39e7eb014b20000000:32)
2023-10-24T17:56:56Z    DEBUG   Faucet  entering checkPendingTransactionState...
2023-10-24T17:56:56Z    DEBUG   Faucet  checkPendingTransactionState: transaction still pending, blockID: BlockID(0x86b89588fe1bb294759f0d0ddfc68ef6412ce40e7d706938e346f7d217acf15d27000000:39), txID: TransactionID(0x5a231dbb1f6984d09df606082914c0a97e741de4e3f9e28154a7ac742e2f69cb20000000:32)
2023-10-24T17:56:56Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:56:56Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x86b89588fe1bb294759f0d0ddfc68ef6412ce40e7d706938e346f7d217acf15d27000000:39), txID: TransactionID(0x5a231dbb1f6984d09df606082914c0a97e741de4e3f9e28154a7ac742e2f69cb20000000:32)
2023-10-24T17:56:56Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:56:57Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:56:57Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x86b89588fe1bb294759f0d0ddfc68ef6412ce40e7d706938e346f7d217acf15d27000000:39), txID: TransactionID(0x5a231dbb1f6984d09df606082914c0a97e741de4e3f9e28154a7ac742e2f69cb20000000:32)
2023-10-24T17:56:58Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:56:58Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:57:00Z    DEBUG   Faucet  collected 2 requests
2023-10-24T17:57:00Z    DEBUG   Faucet  determined 1 available unspent outputs and 2 processable requests
2023-10-24T17:57:00Z    DEBUG   Faucet          unspent output 0, outputID: 0x5a231dbb1f6984d09df606082914c0a97e741de4e3f9e28154a7ac742e2f69cb200000000100, amount: 999901000000000, mana: 243831697685
2023-10-24T17:57:00Z    DEBUG   Faucet          processable request 0, address: rms1qrwlyhttkp6vqfd0arq9l4lnsmgn84u5jzs069f9q9mfkwga56hv2qesd05, amount: 1000000000
2023-10-24T17:57:00Z    DEBUG   Faucet          processable request 1, address: rms1qzajklg802ssl6l0t5t0fxjtwjm4mj5a58ne7w0jlm69ku5zf6vdjrlj8le, amount: 1000000000
2023-10-24T17:57:00Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:57:00Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0x7a2f27339896b78a645e653ad6a0d664253fad75aaa0fa64232d6f4e0614d5e427000000:39), txID: SignedTransactionID(0x698f9d2aa7d5eaefc07510c82b335695417aaa23750858548dbc598412fd2ce420000000:32)
2023-10-24T17:57:00Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:57:00Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x7a2f27339896b78a645e653ad6a0d664253fad75aaa0fa64232d6f4e0614d5e427000000:39), txID: TransactionID(0xd0cd35e1fc3f8998da4920a11f277a0ca65fe11840d3f3b4f68e3e9654cdff1d20000000:32)
2023-10-24T17:57:00Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:57:01Z    DEBUG   Faucet  entering checkPendingTransactionState...
2023-10-24T17:57:01Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:57:01Z    DEBUG   Faucet  checkPendingTransactionState: no pending transaction found
2023-10-24T17:57:01Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:57:03Z    DEBUG   Faucet  collected 1 requests
2023-10-24T17:57:03Z    DEBUG   Faucet  determined 1 available unspent outputs and 1 processable requests
2023-10-24T17:57:03Z    DEBUG   Faucet          unspent output 0, outputID: 0xd0cd35e1fc3f8998da4920a11f277a0ca65fe11840d3f3b4f68e3e9654cdff1d200000000200, amount: 999899000000000, mana: 243826827685
2023-10-24T17:57:03Z    DEBUG   Faucet          processable request 0, address: rms1qqawnhp6dazh3tpycd0xu0t94svs23zdqsqe8qzhxx5lu4ee79sqkha209k, amount: 1000000000
2023-10-24T17:57:03Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:57:03Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0x403761befb20df221c79a7c98a367c665edd210a4845161e1b85e5aacb7424c027000000:39), txID: SignedTransactionID(0x155aaa3fca6129e7bc258c1bd2e44454cb10f45341e8bc0215a9e1b95e95f3ab20000000:32)
2023-10-24T17:57:03Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:57:03Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x403761befb20df221c79a7c98a367c665edd210a4845161e1b85e5aacb7424c027000000:39), txID: TransactionID(0xca01e279d77bb6450bdea08c0171ce830c4f04774ecee2a2b2573078e3359a0920000000:32)
2023-10-24T17:57:03Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:57:04Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:57:04Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:57:06Z    DEBUG   Faucet  collected 1 requests
2023-10-24T17:57:06Z    DEBUG   Faucet  determined 1 available unspent outputs and 1 processable requests
2023-10-24T17:57:06Z    DEBUG   Faucet          unspent output 0, outputID: 0xca01e279d77bb6450bdea08c0171ce830c4f04774ecee2a2b2573078e3359a09200000000100, amount: 999898000000000, mana: 243822621185
2023-10-24T17:57:06Z    DEBUG   Faucet          processable request 0, address: rms1qrdm74z0n49cmk0pu52xhlgz6yxzyz2rlerltqf8h7vrd97luw2p2w9y9u8, amount: 1000000000
2023-10-24T17:57:06Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:57:06Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0x21281596f10024f781e4efb8ba1628f9fbba694d8b5356cb15a777d54f3eee4b28000000:40), txID: SignedTransactionID(0x9269d0b38e9242c34eae9fe317d15941f03dfdecd01ef29b8d9c91acc5c3f2e321000000:33)
2023-10-24T17:57:06Z    DEBUG   Faucet  entering checkPendingTransactionState...
2023-10-24T17:57:06Z    DEBUG   Faucet  checkPendingTransactionState: transaction still pending, blockID: BlockID(0x21281596f10024f781e4efb8ba1628f9fbba694d8b5356cb15a777d54f3eee4b28000000:40), txID: TransactionID(0xc2e4529cb5fed9c2476e1391cc528d1e9a4fdde909bf32c05b4349d9ef30e0a421000000:33)
2023-10-24T17:57:06Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:57:06Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x21281596f10024f781e4efb8ba1628f9fbba694d8b5356cb15a777d54f3eee4b28000000:40), txID: TransactionID(0xc2e4529cb5fed9c2476e1391cc528d1e9a4fdde909bf32c05b4349d9ef30e0a421000000:33)
2023-10-24T17:57:06Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:57:07Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:57:07Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x21281596f10024f781e4efb8ba1628f9fbba694d8b5356cb15a777d54f3eee4b28000000:40), txID: TransactionID(0xc2e4529cb5fed9c2476e1391cc528d1e9a4fdde909bf32c05b4349d9ef30e0a421000000:33)
2023-10-24T17:57:08Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:57:08Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:57:10Z    DEBUG   Faucet  collected 2 requests
2023-10-24T17:57:10Z    DEBUG   Faucet  determined 1 available unspent outputs and 2 processable requests
2023-10-24T17:57:10Z    DEBUG   Faucet          unspent output 0, outputID: 0xc2e4529cb5fed9c2476e1391cc528d1e9a4fdde909bf32c05b4349d9ef30e0a4210000000100, amount: 999897000000000, mana: 251447031018
2023-10-24T17:57:10Z    DEBUG   Faucet          processable request 0, address: rms1qzdl7a9yu7ry40xfm9lgttsxedhrdnnkfzs88kylv2e6w0zdc5a3uunwmxr, amount: 1000000000
2023-10-24T17:57:10Z    DEBUG   Faucet          processable request 1, address: rms1qpl0xdxe2n78xkt7prutw764cxtsycg62vcf0aqraj3qsqt03nwd7grfmue, amount: 1000000000
2023-10-24T17:57:10Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:57:10Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0xf208d3a59a7905195b6d11b6a622f0251ad516e49c9ee759c44e29057e1ae9e628000000:40), txID: SignedTransactionID(0x5f72fe004946aa6dac7983c81c7ef2609ca3d814bb53537ebaba835544f3075321000000:33)
2023-10-24T17:57:10Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:57:10Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0xf208d3a59a7905195b6d11b6a622f0251ad516e49c9ee759c44e29057e1ae9e628000000:40), txID: TransactionID(0x9c183e4f6f508dfb009e1a4fc6c7ec1ed9c67a71b3252ffa5358fcbc1afab69f21000000:33)
2023-10-24T17:57:10Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:57:11Z    DEBUG   Faucet  entering checkPendingTransactionState...
2023-10-24T17:57:11Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:57:11Z    DEBUG   Faucet  checkPendingTransactionState: no pending transaction found
2023-10-24T17:57:11Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:57:13Z    DEBUG   Faucet  collected 1 requests
2023-10-24T17:57:13Z    DEBUG   Faucet  determined 1 available unspent outputs and 1 processable requests
2023-10-24T17:57:13Z    DEBUG   Faucet          unspent output 0, outputID: 0x9c183e4f6f508dfb009e1a4fc6c7ec1ed9c67a71b3252ffa5358fcbc1afab69f210000000200, amount: 999895000000000, mana: 251442161018
2023-10-24T17:57:13Z    DEBUG   Faucet          processable request 0, address: rms1qr60phrzter022jwwdxk0xmufxumhwupn6xafwn4skp7ea6tpt2swty0l9d, amount: 1000000000
2023-10-24T17:57:13Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:57:13Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0xd40ce072d240f0b9856c6f35e670a532c17696118103b393e1132745ba41260028000000:40), txID: SignedTransactionID(0xbc0f421223c247b5ad01a6bd03d5d645901edaea6aeb2ea0d7d150b86de733d621000000:33)
2023-10-24T17:57:13Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:57:13Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0xd40ce072d240f0b9856c6f35e670a532c17696118103b393e1132745ba41260028000000:40), txID: TransactionID(0x2c4d77e2da212cc78d900f3300345d259a053d75374bcfdb5b2c51e91b76464c21000000:33)
2023-10-24T17:57:13Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:57:14Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:57:14Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:57:16Z    DEBUG   Faucet  collected 1 requests
2023-10-24T17:57:16Z    DEBUG   Faucet  determined 1 available unspent outputs and 1 processable requests
2023-10-24T17:57:16Z    DEBUG   Faucet          unspent output 0, outputID: 0x2c4d77e2da212cc78d900f3300345d259a053d75374bcfdb5b2c51e91b76464c210000000100, amount: 999894000000000, mana: 251437954518
2023-10-24T17:57:16Z    DEBUG   Faucet          processable request 0, address: rms1qphx8mn2ede3qm69mp9kf5vm4y7h88r82qhs7vq2804a7fxaq53s53y3245, amount: 1000000000
2023-10-24T17:57:16Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:57:16Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0xd18283e4b4aa1cb7285ec88fe5ee2ed5a0cb7a838704a487c395b5d70f3080ee29000000:41), txID: SignedTransactionID(0xe0316679e8a52540a32fee19959e334ef470841a900e6958b773ddcdaa13859b22000000:34)
2023-10-24T17:57:16Z    DEBUG   Faucet  entering checkPendingTransactionState...
2023-10-24T17:57:16Z    DEBUG   Faucet  checkPendingTransactionState: transaction still pending, blockID: BlockID(0xd18283e4b4aa1cb7285ec88fe5ee2ed5a0cb7a838704a487c395b5d70f3080ee29000000:41), txID: TransactionID(0x713fa9836baa4a5e250f51fdf7058559f30b743711dbda43b03db8057d1e3a6722000000:34)
2023-10-24T17:57:16Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:57:16Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0xd18283e4b4aa1cb7285ec88fe5ee2ed5a0cb7a838704a487c395b5d70f3080ee29000000:41), txID: TransactionID(0x713fa9836baa4a5e250f51fdf7058559f30b743711dbda43b03db8057d1e3a6722000000:34)
2023-10-24T17:57:16Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:57:17Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:57:17Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0xd18283e4b4aa1cb7285ec88fe5ee2ed5a0cb7a838704a487c395b5d70f3080ee29000000:41), txID: TransactionID(0x713fa9836baa4a5e250f51fdf7058559f30b743711dbda43b03db8057d1e3a6722000000:34)
2023-10-24T17:57:18Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:57:18Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:57:20Z    DEBUG   Faucet  collected 2 requests
2023-10-24T17:57:20Z    DEBUG   Faucet  determined 1 available unspent outputs and 2 processable requests
2023-10-24T17:57:20Z    DEBUG   Faucet          unspent output 0, outputID: 0x713fa9836baa4a5e250f51fdf7058559f30b743711dbda43b03db8057d1e3a67220000000100, amount: 999893000000000, mana: 259062333833
2023-10-24T17:57:20Z    DEBUG   Faucet          processable request 0, address: rms1qzwwpgczkkue3qkrezmdvxn8w00pz52k7p0huwnnrqkrxdec3n32yfpvs80, amount: 1000000000
2023-10-24T17:57:20Z    DEBUG   Faucet          processable request 1, address: rms1qryfaeuun6ju0v3rq6ll859nlv387nz5u0uljqcz6ymgnmvfvkqtu06cr65, amount: 1000000000
2023-10-24T17:57:20Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:57:20Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0x8a879393a992ec49c7a2b80da272d06f4d8a93d805b8180dc41624d18e7425c629000000:41), txID: SignedTransactionID(0xdb45c674b4ac63ee20c461989ddc09e2c1f6d19c5239e60d42e5e6ca141a772822000000:34)
2023-10-24T17:57:20Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:57:20Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x8a879393a992ec49c7a2b80da272d06f4d8a93d805b8180dc41624d18e7425c629000000:41), txID: TransactionID(0xb632e18d97f3543e6fe04595ec69577abbe5b1dce2b2478af1713fbdbfe8f29a22000000:34)
2023-10-24T17:57:20Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:57:21Z    DEBUG   Faucet  entering checkPendingTransactionState...
2023-10-24T17:57:21Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:57:21Z    DEBUG   Faucet  checkPendingTransactionState: no pending transaction found
2023-10-24T17:57:21Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:57:23Z    DEBUG   Faucet  collected 1 requests
2023-10-24T17:57:23Z    DEBUG   Faucet  determined 1 available unspent outputs and 1 processable requests
2023-10-24T17:57:23Z    DEBUG   Faucet          unspent output 0, outputID: 0xb632e18d97f3543e6fe04595ec69577abbe5b1dce2b2478af1713fbdbfe8f29a220000000200, amount: 999891000000000, mana: 259057463833
2023-10-24T17:57:23Z    DEBUG   Faucet          processable request 0, address: rms1qrccejatf5c8lu3m3qwpcyyp5v89chn7cgm6av7vrs0cjxs43rugjuuejsh, amount: 1000000000
2023-10-24T17:57:23Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:57:23Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0x0bcbf627497a432556e265d25ea125be663a2bc2aee77b391b3929f103bcd07829000000:41), txID: SignedTransactionID(0x360b1b06348d5a0e94af3afdc67db3bc2e5b804ed79f40a6d29e79f28919e92222000000:34)
2023-10-24T17:57:23Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:57:23Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x0bcbf627497a432556e265d25ea125be663a2bc2aee77b391b3929f103bcd07829000000:41), txID: TransactionID(0x41016ee37c462da6485fb4d55b998136c7748c96ac6dcdd3a2aba2a7b7bfa8f122000000:34)
2023-10-24T17:57:23Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:57:24Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:57:24Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:57:26Z    DEBUG   Faucet  collected 1 requests
2023-10-24T17:57:26Z    DEBUG   Faucet  determined 1 available unspent outputs and 1 processable requests
2023-10-24T17:57:26Z    DEBUG   Faucet          unspent output 0, outputID: 0x41016ee37c462da6485fb4d55b998136c7748c96ac6dcdd3a2aba2a7b7bfa8f1220000000100, amount: 999890000000000, mana: 259053257333
2023-10-24T17:57:26Z    DEBUG   Faucet          processable request 0, address: rms1qqpezd2fuhneev3mxam3c55xdgzkd5020uy87rajqej62qy8054vxeqvnaq, amount: 1000000000
2023-10-24T17:57:26Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:57:26Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0x05525ac68c9107ec70b780f01781dc982db56fb862e32ddd517308d2451a72202a000000:42), txID: SignedTransactionID(0x09f5b112a57e0372cca7da7399e75a4bf14983efa0cddc15772cd5ecfd9c728823000000:35)
2023-10-24T17:57:26Z    DEBUG   Faucet  entering checkPendingTransactionState...
2023-10-24T17:57:26Z    DEBUG   Faucet  checkPendingTransactionState: transaction still pending, blockID: BlockID(0x05525ac68c9107ec70b780f01781dc982db56fb862e32ddd517308d2451a72202a000000:42), txID: TransactionID(0x4987bb3eedbf16d0b4c043a55f11a4f7beebe02104876f08216619bbcde4db9b23000000:35)
2023-10-24T17:57:26Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:57:26Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x05525ac68c9107ec70b780f01781dc982db56fb862e32ddd517308d2451a72202a000000:42), txID: TransactionID(0x4987bb3eedbf16d0b4c043a55f11a4f7beebe02104876f08216619bbcde4db9b23000000:35)
2023-10-24T17:57:26Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:57:27Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:57:27Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x05525ac68c9107ec70b780f01781dc982db56fb862e32ddd517308d2451a72202a000000:42), txID: TransactionID(0x4987bb3eedbf16d0b4c043a55f11a4f7beebe02104876f08216619bbcde4db9b23000000:35)
2023-10-24T17:57:28Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:57:28Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:57:30Z    DEBUG   Faucet  collected 2 requests
2023-10-24T17:57:30Z    DEBUG   Faucet  determined 1 available unspent outputs and 2 processable requests
2023-10-24T17:57:30Z    DEBUG   Faucet          unspent output 0, outputID: 0x4987bb3eedbf16d0b4c043a55f11a4f7beebe02104876f08216619bbcde4db9b230000000100, amount: 999889000000000, mana: 266677606130
2023-10-24T17:57:30Z    DEBUG   Faucet          processable request 0, address: rms1qz3vyl6dltsj68pacrd2luzfy8gl90vw3qj2d2flulz6ytzkt3rnue90x3y, amount: 1000000000
2023-10-24T17:57:30Z    DEBUG   Faucet          processable request 1, address: rms1qrs8e2gw6n5wrf7k7uzacz445hf22f2r5re852tvx4gtlxcxhl7l6gcf5g2, amount: 1000000000
2023-10-24T17:57:30Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:57:30Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0xd2e2dca99f3a8061a440057c96536b943af04ae39f3d30028091c468e4ce7dde2a000000:42), txID: SignedTransactionID(0x93d5285b480f42bc59625c758c2015478734200947e4496c2c2ec766206b20a523000000:35)
2023-10-24T17:57:30Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:57:30Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0xd2e2dca99f3a8061a440057c96536b943af04ae39f3d30028091c468e4ce7dde2a000000:42), txID: TransactionID(0x49810ebb8bf7c07d6c2a332c96ef6b1055e3d02e3a0911579501d4916a59389123000000:35)
2023-10-24T17:57:31Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:57:31Z    DEBUG   Faucet  entering checkPendingTransactionState...
2023-10-24T17:57:31Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:57:31Z    DEBUG   Faucet  checkPendingTransactionState: no pending transaction found
2023-10-24T17:57:31Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:57:33Z    DEBUG   Faucet  collected 1 requests
2023-10-24T17:57:33Z    DEBUG   Faucet  determined 1 available unspent outputs and 1 processable requests
2023-10-24T17:57:33Z    DEBUG   Faucet          unspent output 0, outputID: 0x49810ebb8bf7c07d6c2a332c96ef6b1055e3d02e3a0911579501d4916a593891230000000200, amount: 999887000000000, mana: 266672736130
2023-10-24T17:57:33Z    DEBUG   Faucet          processable request 0, address: rms1qr4z3pz7fzy98y4m4pzezafayhnmehdn59p8les46uetpcj8kxf5vgzqf55, amount: 1000000000
2023-10-24T17:57:33Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:57:33Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0x105e462ae516a2ee71793ca8ac8ab8e5584544a268901295ce3cc7a31981cf972a000000:42), txID: SignedTransactionID(0xa54cb2476c65869cd0bb5396007327434416b184401dd33f34923dd58087137423000000:35)
2023-10-24T17:57:33Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:57:33Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x105e462ae516a2ee71793ca8ac8ab8e5584544a268901295ce3cc7a31981cf972a000000:42), txID: TransactionID(0xa1cc1ad209834729cd47f449d2d6e1922710f0d41311b63c832cd74609868b0223000000:35)
2023-10-24T17:57:34Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:57:34Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:57:34Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:57:36Z    DEBUG   Faucet  collected 1 requests
2023-10-24T17:57:36Z    DEBUG   Faucet  determined 1 available unspent outputs and 1 processable requests
2023-10-24T17:57:36Z    DEBUG   Faucet          unspent output 0, outputID: 0xa1cc1ad209834729cd47f449d2d6e1922710f0d41311b63c832cd74609868b02230000000100, amount: 999886000000000, mana: 266668529630
2023-10-24T17:57:36Z    DEBUG   Faucet          processable request 0, address: rms1qp2z8k4yll4hvur8ym3mfkvsnansqywpg78nv3am39svqjv23mazc43p3vh, amount: 1000000000
2023-10-24T17:57:36Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:57:36Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0x04f251fad34970f38b2baebe61eb9cc73f7f84fef74c6e01d3ab8f68e6e7b5eb2b000000:43), txID: SignedTransactionID(0xc6c4abc31f66417ac2813af1a789274302b7594dbd38f5d172db407f1d804dab24000000:36)
2023-10-24T17:57:36Z    DEBUG   Faucet  entering checkPendingTransactionState...
2023-10-24T17:57:36Z    DEBUG   Faucet  checkPendingTransactionState: transaction still pending, blockID: BlockID(0x04f251fad34970f38b2baebe61eb9cc73f7f84fef74c6e01d3ab8f68e6e7b5eb2b000000:43), txID: TransactionID(0x54a6ac85d810ba8a615dc802cf86490500703198d125497d3f35240447afa43924000000:36)
2023-10-24T17:57:36Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:57:36Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x04f251fad34970f38b2baebe61eb9cc73f7f84fef74c6e01d3ab8f68e6e7b5eb2b000000:43), txID: TransactionID(0x54a6ac85d810ba8a615dc802cf86490500703198d125497d3f35240447afa43924000000:36)
2023-10-24T17:57:37Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:57:37Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:57:37Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x04f251fad34970f38b2baebe61eb9cc73f7f84fef74c6e01d3ab8f68e6e7b5eb2b000000:43), txID: TransactionID(0x54a6ac85d810ba8a615dc802cf86490500703198d125497d3f35240447afa43924000000:36)
2023-10-24T17:57:38Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:57:38Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:57:40Z    DEBUG   Faucet  collected 2 requests
2023-10-24T17:57:40Z    DEBUG   Faucet  determined 1 available unspent outputs and 2 processable requests
2023-10-24T17:57:40Z    DEBUG   Faucet          unspent output 0, outputID: 0x54a6ac85d810ba8a615dc802cf86490500703198d125497d3f35240447afa439240000000100, amount: 999885000000000, mana: 274292847910
2023-10-24T17:57:40Z    DEBUG   Faucet          processable request 0, address: rms1qq7xvj07lceg56ulvaajh7n8ymakp3ltx4pmwmkrcrc85gkrnhafg8807n2, amount: 1000000000
2023-10-24T17:57:40Z    DEBUG   Faucet          processable request 1, address: rms1qpguqw9su5uacxsr3ny75vfps564y60wvdvtlskvncu58dyhwe9kv87wjk0, amount: 1000000000
2023-10-24T17:57:40Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:57:40Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0x0d36602f7559b8aa1985952149bd08734c2a6a39a2c1001399206099f637450e2b000000:43), txID: SignedTransactionID(0x7b12c28e80273913a37b80c68631585d3d60df0744be4b58841fdd891370756024000000:36)
2023-10-24T17:57:40Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:57:40Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x0d36602f7559b8aa1985952149bd08734c2a6a39a2c1001399206099f637450e2b000000:43), txID: TransactionID(0x0c936d7fc3826f5705dce3cd12edbb88a98000a25e9d90286af613b540a6962b24000000:36)
2023-10-24T17:57:41Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:57:41Z    DEBUG   Faucet  entering checkPendingTransactionState...
2023-10-24T17:57:41Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:57:41Z    DEBUG   Faucet  checkPendingTransactionState: no pending transaction found
2023-10-24T17:57:41Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:57:43Z    DEBUG   Faucet  collected 1 requests
2023-10-24T17:57:43Z    DEBUG   Faucet  determined 1 available unspent outputs and 1 processable requests
2023-10-24T17:57:43Z    DEBUG   Faucet          unspent output 0, outputID: 0x0c936d7fc3826f5705dce3cd12edbb88a98000a25e9d90286af613b540a6962b240000000200, amount: 999883000000000, mana: 274287977910
2023-10-24T17:57:43Z    DEBUG   Faucet          processable request 0, address: rms1qqzt2c8ttwffjshmgmntsh8tt357eujknqtuw290qdaa6ygtnlk55y4pc9d, amount: 1000000000
2023-10-24T17:57:43Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:57:43Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0xd9cd40e226eb1650a35a83267f298d189599b70682d113e5c8deae281f5344742b000000:43), txID: SignedTransactionID(0xd2ab5cb2456667dee3c8cafe8ef0dfc16de51903d9161ccb59042b23e3e9029e24000000:36)
2023-10-24T17:57:43Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:57:43Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0xd9cd40e226eb1650a35a83267f298d189599b70682d113e5c8deae281f5344742b000000:43), txID: TransactionID(0xfcce2cf2bd765226ae7902624986ebae6c9b6a86681623b45fed609a4179579524000000:36)
2023-10-24T17:57:44Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:57:44Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:57:44Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:57:46Z    DEBUG   Faucet  collected 1 requests
2023-10-24T17:57:46Z    DEBUG   Faucet  determined 1 available unspent outputs and 1 processable requests
2023-10-24T17:57:46Z    DEBUG   Faucet          unspent output 0, outputID: 0xfcce2cf2bd765226ae7902624986ebae6c9b6a86681623b45fed609a41795795240000000100, amount: 999882000000000, mana: 274283771410
2023-10-24T17:57:46Z    DEBUG   Faucet          processable request 0, address: rms1qq02qegdv96q0zwst2cwnthvu5ph8yl9gcmmmxg4newvglhz5xr22q2k65k, amount: 1000000000
2023-10-24T17:57:46Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:57:46Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0xfa5102d9f6294719a31a2800d5ef83caf98b3d5e014a03621d2eb3c3967dbff82c000000:44), txID: SignedTransactionID(0x14370839cf8afadb695512a7f0e5bd84a5f9c3f19f61fefeefffc99c811402d025000000:37)
2023-10-24T17:57:46Z    DEBUG   Faucet  entering checkPendingTransactionState...
2023-10-24T17:57:46Z    WARN    Faucet  transaction failed, blockID: BlockID(0xfa5102d9f6294719a31a2800d5ef83caf98b3d5e014a03621d2eb3c3967dbff82c000000:44), txID: TransactionID(0x86b0e61fcc6afbcc4eae82e7f2ce49417928a52ae9d5d5d3f8c4b2208689504625000000:37), reason: 2
2023-10-24T17:57:46Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:57:47Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:57:48Z    DEBUG   Faucet  collected 2 requests
2023-10-24T17:57:48Z    DEBUG   Faucet  determined 1 available unspent outputs and 2 processable requests
2023-10-24T17:57:48Z    DEBUG   Faucet          unspent output 0, outputID: 0x86b0e61fcc6afbcc4eae82e7f2ce49417928a52ae9d5d5d3f8c4b22086895046250000000100, amount: 999881000000000, mana: 281908059172
2023-10-24T17:57:48Z    DEBUG   Faucet          processable request 0, address: rms1qq02qegdv96q0zwst2cwnthvu5ph8yl9gcmmmxg4newvglhz5xr22q2k65k, amount: 1000000000
2023-10-24T17:57:48Z    DEBUG   Faucet          processable request 1, address: rms1qzeev9pfqlqznhn3zuup5juur39v5ru75tm76plul35z9pgkt8qau3zway2, amount: 1000000000
2023-10-24T17:57:48Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:57:48Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0xb4f7f1ab247f12852cd436aa6540e758fa5ac3738be35e25220ac6cef27896512c000000:44), txID: SignedTransactionID(0xc5fc879a133c52f9a9fa5bfbc53f557d38ab6f55ce8f0cc166a69b0aaa1fa76025000000:37)
2023-10-24T17:57:48Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:57:48Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0xb4f7f1ab247f12852cd436aa6540e758fa5ac3738be35e25220ac6cef27896512c000000:44), txID: TransactionID(0x53faca3e56262b4b9c9217abc2d4345002bb36e587cea546a2e42848d8f4aed925000000:37)
2023-10-24T17:57:49Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:57:49Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0xb4f7f1ab247f12852cd436aa6540e758fa5ac3738be35e25220ac6cef27896512c000000:44), txID: TransactionID(0x53faca3e56262b4b9c9217abc2d4345002bb36e587cea546a2e42848d8f4aed925000000:37)
2023-10-24T17:57:49Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:57:50Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:57:50Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0xb4f7f1ab247f12852cd436aa6540e758fa5ac3738be35e25220ac6cef27896512c000000:44), txID: TransactionID(0x53faca3e56262b4b9c9217abc2d4345002bb36e587cea546a2e42848d8f4aed925000000:37)
2023-10-24T17:57:51Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:57:51Z    DEBUG   Faucet  entering checkPendingTransactionState...
2023-10-24T17:57:51Z    DEBUG   Faucet  checkPendingTransactionState: no pending transaction found
2023-10-24T17:57:51Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:57:53Z    DEBUG   Faucet  collected 2 requests
2023-10-24T17:57:53Z    DEBUG   Faucet  determined 1 available unspent outputs and 2 processable requests
2023-10-24T17:57:53Z    DEBUG   Faucet          unspent output 0, outputID: 0x53faca3e56262b4b9c9217abc2d4345002bb36e587cea546a2e42848d8f4aed9250000000200, amount: 999879000000000, mana: 281903189172
2023-10-24T17:57:53Z    DEBUG   Faucet          processable request 0, address: rms1qzuz68ld70ralh46yl8n6mt957kfu60cwdpfuzgs5jrpeng5uau6vtsyq5a, amount: 1000000000
2023-10-24T17:57:53Z    DEBUG   Faucet          processable request 1, address: rms1qq80zd4zhwcc0mgay8wf84psajmw9jegey0r8vnzzuyc3uv3g2qgsjlgxhy, amount: 1000000000
2023-10-24T17:57:53Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:57:53Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0x85fc6f071775ad1eecab25304ce937d8c17b579daab30ae3e702fde886c1bff72c000000:44), txID: SignedTransactionID(0xc8395e5e2fe2230a0c4b69dea917c7b473b77c915056dfa1aa993859b142ccd925000000:37)
2023-10-24T17:57:53Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:57:53Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x85fc6f071775ad1eecab25304ce937d8c17b579daab30ae3e702fde886c1bff72c000000:44), txID: TransactionID(0x2f0a928ba613f75f1eea750e5a1205ad7634e3edbc8160e92b0415f2cbb6607a25000000:37)
2023-10-24T17:57:54Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:57:54Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:57:54Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:57:56Z    DEBUG   Faucet  collected 1 requests
2023-10-24T17:57:56Z    DEBUG   Faucet  determined 1 available unspent outputs and 1 processable requests
2023-10-24T17:57:56Z    DEBUG   Faucet          unspent output 0, outputID: 0x2f0a928ba613f75f1eea750e5a1205ad7634e3edbc8160e92b0415f2cbb6607a250000000200, amount: 999877000000000, mana: 281898319172
2023-10-24T17:57:56Z    DEBUG   Faucet          processable request 0, address: rms1qqwq4um6j3tf40gehhkx7avnxft5qfl53wln964mgzsxcnfg3fryxzkcd9q, amount: 1000000000
2023-10-24T17:57:56Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:57:56Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0x62ff2205c0380d3b5b9548879a95681ee456573d2a236dba4bacdedc0a3b96dd2d000000:45), txID: SignedTransactionID(0x08d63505e06eb96b674a1485afc2d45dad612ae5d32a1c0079bfa3138b8b4c9326000000:38)
2023-10-24T17:57:56Z    DEBUG   Faucet  entering checkPendingTransactionState...
2023-10-24T17:57:56Z    DEBUG   Faucet  checkPendingTransactionState: transaction still pending, blockID: BlockID(0x62ff2205c0380d3b5b9548879a95681ee456573d2a236dba4bacdedc0a3b96dd2d000000:45), txID: TransactionID(0x7943c0979a1c30c1a36cf63ab62baf3b00d8089df2b2c763ea45be5a7583530b26000000:38)
2023-10-24T17:57:56Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:57:56Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x62ff2205c0380d3b5b9548879a95681ee456573d2a236dba4bacdedc0a3b96dd2d000000:45), txID: TransactionID(0x7943c0979a1c30c1a36cf63ab62baf3b00d8089df2b2c763ea45be5a7583530b26000000:38)
2023-10-24T17:57:57Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:57:57Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:57:57Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x62ff2205c0380d3b5b9548879a95681ee456573d2a236dba4bacdedc0a3b96dd2d000000:45), txID: TransactionID(0x7943c0979a1c30c1a36cf63ab62baf3b00d8089df2b2c763ea45be5a7583530b26000000:38)
2023-10-24T17:57:58Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:57:58Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:58:00Z    DEBUG   Faucet  collected 2 requests
2023-10-24T17:58:00Z    DEBUG   Faucet  determined 1 available unspent outputs and 2 processable requests
2023-10-24T17:58:00Z    DEBUG   Faucet          unspent output 0, outputID: 0x7943c0979a1c30c1a36cf63ab62baf3b00d8089df2b2c763ea45be5a7583530b260000000100, amount: 999876000000000, mana: 289522568787
2023-10-24T17:58:00Z    DEBUG   Faucet          processable request 0, address: rms1qqhuw5ck9jepcwmf757zmf0w57h7cz2uu22rt807j3sgfyc0auqk2cnjn53, amount: 1000000000
2023-10-24T17:58:00Z    DEBUG   Faucet          processable request 1, address: rms1qzww30w3x0yq5eyvxkylgp6spx29t0j8l3wa6hxztlpxlsef5uf65vu4dp0, amount: 1000000000
2023-10-24T17:58:00Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:58:00Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0x1a18abd960191a34935dde84514d6e69660d10da5df0a5bc49b3457c54e945562d000000:45), txID: SignedTransactionID(0x09197e141c01edb7878a405e8b7f818c71d219c002bfafa889e6b3bc3db72dc126000000:38)
2023-10-24T17:58:00Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:58:00Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x1a18abd960191a34935dde84514d6e69660d10da5df0a5bc49b3457c54e945562d000000:45), txID: TransactionID(0x8b8d799bee302be3978bc5299bb6309032bff3eaaca5b49bf7e323432239f8ff26000000:38)
2023-10-24T17:58:01Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:58:01Z    DEBUG   Faucet  entering checkPendingTransactionState...
2023-10-24T17:58:01Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:58:01Z    DEBUG   Faucet  checkPendingTransactionState: no pending transaction found
2023-10-24T17:58:01Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:58:03Z    DEBUG   Faucet  collected 1 requests
2023-10-24T17:58:03Z    DEBUG   Faucet  determined 1 available unspent outputs and 1 processable requests
2023-10-24T17:58:03Z    DEBUG   Faucet          unspent output 0, outputID: 0x8b8d799bee302be3978bc5299bb6309032bff3eaaca5b49bf7e323432239f8ff260000000200, amount: 999874000000000, mana: 289517698787
2023-10-24T17:58:03Z    DEBUG   Faucet          processable request 0, address: rms1qpkp8m26fhtwstzv9q4wjhczpvqmp45tlqgfttgrsne8g2stcyrkq9dggv7, amount: 1000000000
2023-10-24T17:58:03Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:58:03Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0x8358c8f76be6064e324a234c3cdad2c6126f76572eb29f4f4e6cfe70c574a85a2d000000:45), txID: SignedTransactionID(0xeb1c229fbe29f38b4757aef85066a5bf67937081d1e2dd12181eb3e83173784426000000:38)
2023-10-24T17:58:03Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:58:03Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x8358c8f76be6064e324a234c3cdad2c6126f76572eb29f4f4e6cfe70c574a85a2d000000:45), txID: TransactionID(0x5c60df853a6a9e68dc2758a491cd3e7f7bd694703b2b9311f47fa43091a2ccb826000000:38)
2023-10-24T17:58:04Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:58:04Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:58:04Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:58:06Z    DEBUG   Faucet  collected 1 requests
2023-10-24T17:58:06Z    DEBUG   Faucet  determined 1 available unspent outputs and 1 processable requests
2023-10-24T17:58:06Z    DEBUG   Faucet          unspent output 0, outputID: 0x5c60df853a6a9e68dc2758a491cd3e7f7bd694703b2b9311f47fa43091a2ccb8260000000100, amount: 999873000000000, mana: 289513492287
2023-10-24T17:58:06Z    DEBUG   Faucet          processable request 0, address: rms1qrqnaprz0t80jj8va4nuwysvkgxy03kr3p3fwy6ugwuctg44u78rj9u65vs, amount: 1000000000
2023-10-24T17:58:06Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:58:06Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0x1c0996a7785ed16e2bcd0401945442310c895ceb643d17ff6dc6229fc282123f2e000000:46), txID: SignedTransactionID(0x8e3e4b555b080b835781c0f4bc506fd391a984b20a23f80bb97d7cb0df8945c827000000:39)
2023-10-24T17:58:06Z    DEBUG   Faucet  entering checkPendingTransactionState...
2023-10-24T17:58:06Z    DEBUG   Faucet  checkPendingTransactionState: transaction still pending, blockID: BlockID(0x1c0996a7785ed16e2bcd0401945442310c895ceb643d17ff6dc6229fc282123f2e000000:46), txID: TransactionID(0x5f837ffc2e90df6eb955b23875ed1a1f3089378b94242b4aeb687ed8673c20f827000000:39)
2023-10-24T17:58:06Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:58:06Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x1c0996a7785ed16e2bcd0401945442310c895ceb643d17ff6dc6229fc282123f2e000000:46), txID: TransactionID(0x5f837ffc2e90df6eb955b23875ed1a1f3089378b94242b4aeb687ed8673c20f827000000:39)
2023-10-24T17:58:07Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:58:07Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:58:07Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x1c0996a7785ed16e2bcd0401945442310c895ceb643d17ff6dc6229fc282123f2e000000:46), txID: TransactionID(0x5f837ffc2e90df6eb955b23875ed1a1f3089378b94242b4aeb687ed8673c20f827000000:39)
2023-10-24T17:58:08Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:58:08Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:58:10Z    DEBUG   Faucet  collected 2 requests
2023-10-24T17:58:10Z    DEBUG   Faucet  determined 1 available unspent outputs and 2 processable requests
2023-10-24T17:58:10Z    DEBUG   Faucet          unspent output 0, outputID: 0x5f837ffc2e90df6eb955b23875ed1a1f3089378b94242b4aeb687ed8673c20f8270000000100, amount: 999872000000000, mana: 297137711385
2023-10-24T17:58:10Z    DEBUG   Faucet          processable request 0, address: rms1qrr6kj3lx68vs5ruvfvt76yf6xkpwjw78emtd8c2a4c4t44jkqd774s3z3s, amount: 1000000000
2023-10-24T17:58:10Z    DEBUG   Faucet          processable request 1, address: rms1qq9cu5ktjn4za7e0dzw468qet0upf4p3xf54aqn598sthajhm87dsc8kx9f, amount: 1000000000
2023-10-24T17:58:10Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:58:10Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0xd65c741552d19faafbdd3d0517a062af14277335b26589f0a90fb11f2568fad42e000000:46), txID: SignedTransactionID(0x9a200c31fc0cc2ff99640ae47d433a467ea2fea9d99ca099d2eb1c69698c379e27000000:39)
2023-10-24T17:58:10Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:58:10Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0xd65c741552d19faafbdd3d0517a062af14277335b26589f0a90fb11f2568fad42e000000:46), txID: TransactionID(0x344be6e073d7292cec99e3a0f38f7a6556b637a1dcfdd411094f2e92d54e08a727000000:39)
2023-10-24T17:58:11Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:58:11Z    DEBUG   Faucet  entering checkPendingTransactionState...
2023-10-24T17:58:11Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:58:11Z    DEBUG   Faucet  checkPendingTransactionState: no pending transaction found
2023-10-24T17:58:11Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:58:13Z    DEBUG   Faucet  collected 1 requests
2023-10-24T17:58:13Z    DEBUG   Faucet  determined 1 available unspent outputs and 1 processable requests
2023-10-24T17:58:13Z    DEBUG   Faucet          unspent output 0, outputID: 0x344be6e073d7292cec99e3a0f38f7a6556b637a1dcfdd411094f2e92d54e08a7270000000200, amount: 999870000000000, mana: 297132841385
2023-10-24T17:58:13Z    DEBUG   Faucet          processable request 0, address: rms1qqga2dt5jdjhmm7s0q7f6h8nrry4wr230r9gtv5wvx47mmpj0un0krlp8t3, amount: 1000000000
2023-10-24T17:58:13Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:58:13Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0xa416fca13457e598300b42b7b08a6006bc11e1d9cea450de123740723989d3b52e000000:46), txID: SignedTransactionID(0x7fe593ecd1d0378cf387390543cfc44ea244df20cdf42546c8ab654cb46f775427000000:39)
2023-10-24T17:58:13Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:58:13Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0xa416fca13457e598300b42b7b08a6006bc11e1d9cea450de123740723989d3b52e000000:46), txID: TransactionID(0x71ddab276e5370226248ba45d0b0e6c73d009c9a8c65c266eba10184e8f877e327000000:39)
2023-10-24T17:58:14Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:58:14Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:58:14Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:58:16Z    DEBUG   Faucet  collected 1 requests
2023-10-24T17:58:16Z    DEBUG   Faucet  determined 1 available unspent outputs and 1 processable requests
2023-10-24T17:58:16Z    DEBUG   Faucet          unspent output 0, outputID: 0x71ddab276e5370226248ba45d0b0e6c73d009c9a8c65c266eba10184e8f877e3270000000100, amount: 999869000000000, mana: 297128634885
2023-10-24T17:58:16Z    DEBUG   Faucet          processable request 0, address: rms1qqxqpcywdgk2r6fscdz89nwg94m626ldffjw4fag9pfdsdvp2tk65k9pj4m, amount: 1000000000
2023-10-24T17:58:16Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:58:16Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0x43f3918bfd78225684cef759c8804f9d4af11b8e8a698cc66dd40bad17e237062f000000:47), txID: SignedTransactionID(0xe8f6cbd5e40d95eb3e08606a8da90a389c4d09a9f34c7d8fddab9574290c9a9b28000000:40)
2023-10-24T17:58:16Z    DEBUG   Faucet  entering checkPendingTransactionState...
2023-10-24T17:58:16Z    DEBUG   Faucet  checkPendingTransactionState: transaction still pending, blockID: BlockID(0x43f3918bfd78225684cef759c8804f9d4af11b8e8a698cc66dd40bad17e237062f000000:47), txID: TransactionID(0xcb940d9b2a4e149ffbe26e85970330d3ab011045ebda86c6bde7ab57d4b8ddad28000000:40)
2023-10-24T17:58:16Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:58:16Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x43f3918bfd78225684cef759c8804f9d4af11b8e8a698cc66dd40bad17e237062f000000:47), txID: TransactionID(0xcb940d9b2a4e149ffbe26e85970330d3ab011045ebda86c6bde7ab57d4b8ddad28000000:40)
2023-10-24T17:58:17Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:58:17Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:58:17Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x43f3918bfd78225684cef759c8804f9d4af11b8e8a698cc66dd40bad17e237062f000000:47), txID: TransactionID(0xcb940d9b2a4e149ffbe26e85970330d3ab011045ebda86c6bde7ab57d4b8ddad28000000:40)
2023-10-24T17:58:18Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:58:18Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:58:20Z    DEBUG   Faucet  collected 2 requests
2023-10-24T17:58:20Z    DEBUG   Faucet  determined 1 available unspent outputs and 2 processable requests
2023-10-24T17:58:20Z    DEBUG   Faucet          unspent output 0, outputID: 0xcb940d9b2a4e149ffbe26e85970330d3ab011045ebda86c6bde7ab57d4b8ddad280000000100, amount: 999868000000000, mana: 304752823465
2023-10-24T17:58:20Z    DEBUG   Faucet          processable request 0, address: rms1qz54hg3xu9pmlm2qe7faw9jesnwhv2z57l23j07tuds6lxldadevwgt0ac4, amount: 1000000000
2023-10-24T17:58:20Z    DEBUG   Faucet          processable request 1, address: rms1qqxm7gjlnt9dkckr3w9wsxpcz0gx0u2h90qest9s9velpnvmxv2gchzlrfa, amount: 1000000000
2023-10-24T17:58:20Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:58:20Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0x5c566aab4cfeea826b9aec0e624f83cea0b5a7a0d34e48d2a75186c25a9ef9352f000000:47), txID: SignedTransactionID(0x65673ea47ee5b07762dcbdf4f1e07560bc9f4cef1cf33dde7d22b38359a36bc828000000:40)
2023-10-24T17:58:20Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:58:20Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x5c566aab4cfeea826b9aec0e624f83cea0b5a7a0d34e48d2a75186c25a9ef9352f000000:47), txID: TransactionID(0x74e815202337c52ead25f37c36cf4d4f33803de24f8679b3a4f49c1514510eba28000000:40)
2023-10-24T17:58:21Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:58:21Z    DEBUG   Faucet  entering checkPendingTransactionState...
2023-10-24T17:58:21Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:58:21Z    DEBUG   Faucet  checkPendingTransactionState: no pending transaction found
2023-10-24T17:58:21Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:58:23Z    DEBUG   Faucet  collected 1 requests
2023-10-24T17:58:23Z    DEBUG   Faucet  determined 1 available unspent outputs and 1 processable requests
2023-10-24T17:58:23Z    DEBUG   Faucet          unspent output 0, outputID: 0x74e815202337c52ead25f37c36cf4d4f33803de24f8679b3a4f49c1514510eba280000000200, amount: 999866000000000, mana: 304747953465
2023-10-24T17:58:23Z    DEBUG   Faucet          processable request 0, address: rms1qqrjqlh9u9a298t0j7tsfsq98r6dzml4xhcln7m8ptvul9znckkpgd0atpd, amount: 1000000000
2023-10-24T17:58:23Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:58:23Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0x1b8f3990a36ee68cab6255df758268c7f61e3b52852aa38bbe7aabfb7079f7eb2f000000:47), txID: SignedTransactionID(0x58e91582406111908add570057b5327b262bc5a27eeb12bf6d6277672410849a28000000:40)
2023-10-24T17:58:23Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:58:23Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x1b8f3990a36ee68cab6255df758268c7f61e3b52852aa38bbe7aabfb7079f7eb2f000000:47), txID: TransactionID(0xd4512a9eff0305768b69cec7958f9cacd6d9912bce6bd42e66352c3f94eb5dc728000000:40)
2023-10-24T17:58:24Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:58:24Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:58:24Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:58:26Z    DEBUG   Faucet  collected 1 requests
2023-10-24T17:58:26Z    DEBUG   Faucet  determined 1 available unspent outputs and 1 processable requests
2023-10-24T17:58:26Z    DEBUG   Faucet          unspent output 0, outputID: 0xd4512a9eff0305768b69cec7958f9cacd6d9912bce6bd42e66352c3f94eb5dc7280000000100, amount: 999865000000000, mana: 304743746965
2023-10-24T17:58:26Z    DEBUG   Faucet          processable request 0, address: rms1qpx48du2746mqfzew3aczaf8axxwhap5wanvkhpzzlp2kqmk3v936qyzgzh, amount: 1000000000
2023-10-24T17:58:26Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:58:26Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0x1fe1170bf1cf7b4e9419c848d0da0c511dece6485b0f50d5f63a45247d46964b30000000:48), txID: SignedTransactionID(0x08ffadca20c983f1cd38c495e5ba16205bda8ac7db66cadb6164c6d9bdd7164529000000:41)
2023-10-24T17:58:26Z    DEBUG   Faucet  entering checkPendingTransactionState...
2023-10-24T17:58:26Z    DEBUG   Faucet  checkPendingTransactionState: transaction still pending, blockID: BlockID(0x1fe1170bf1cf7b4e9419c848d0da0c511dece6485b0f50d5f63a45247d46964b30000000:48), txID: TransactionID(0x7c6de88aa068fe087fe665200d65554ee6c705caea570e49131ddab834aefa0d29000000:41)
2023-10-24T17:58:26Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:58:26Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x1fe1170bf1cf7b4e9419c848d0da0c511dece6485b0f50d5f63a45247d46964b30000000:48), txID: TransactionID(0x7c6de88aa068fe087fe665200d65554ee6c705caea570e49131ddab834aefa0d29000000:41)
2023-10-24T17:58:27Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:58:27Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:58:27Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x1fe1170bf1cf7b4e9419c848d0da0c511dece6485b0f50d5f63a45247d46964b30000000:48), txID: TransactionID(0x7c6de88aa068fe087fe665200d65554ee6c705caea570e49131ddab834aefa0d29000000:41)
2023-10-24T17:58:28Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:58:28Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:58:30Z    DEBUG   Faucet  collected 2 requests
2023-10-24T17:58:30Z    DEBUG   Faucet  determined 1 available unspent outputs and 2 processable requests
2023-10-24T17:58:30Z    DEBUG   Faucet          unspent output 0, outputID: 0x7c6de88aa068fe087fe665200d65554ee6c705caea570e49131ddab834aefa0d290000000100, amount: 999864000000000, mana: 312367905027
2023-10-24T17:58:30Z    DEBUG   Faucet          processable request 0, address: rms1qzwm93te8p7tulpufcmvd9nhlx6acdha2uj2g87van9rtrvdtxthyjjnyqf, amount: 1000000000
2023-10-24T17:58:30Z    DEBUG   Faucet          processable request 1, address: rms1qp9kn47xldsxpqqnv648vctgh0qqhpyn7nd7jzyamxtcrtvnm75n7j3xn7e, amount: 1000000000
2023-10-24T17:58:30Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:58:30Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0x24d1f89f5a06df249dc1ef1b34fc807ca1c743c4e1b4652a47b263408f90218d30000000:48), txID: SignedTransactionID(0x49493d228dd125cf6979437d5c72866603c5b6135d5c4f0d257613c00807272829000000:41)
2023-10-24T17:58:30Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:58:30Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x24d1f89f5a06df249dc1ef1b34fc807ca1c743c4e1b4652a47b263408f90218d30000000:48), txID: TransactionID(0xa7ea5975c2e144dfebda6f6ca179368dcdc231f09afc9620838d1de54aa539d529000000:41)
2023-10-24T17:58:31Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:58:31Z    DEBUG   Faucet  entering checkPendingTransactionState...
2023-10-24T17:58:31Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:58:31Z    DEBUG   Faucet  checkPendingTransactionState: no pending transaction found
2023-10-24T17:58:31Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:58:33Z    DEBUG   Faucet  collected 1 requests
2023-10-24T17:58:33Z    DEBUG   Faucet  determined 1 available unspent outputs and 1 processable requests
2023-10-24T17:58:33Z    DEBUG   Faucet          unspent output 0, outputID: 0xa7ea5975c2e144dfebda6f6ca179368dcdc231f09afc9620838d1de54aa539d5290000000200, amount: 999862000000000, mana: 312363035027
2023-10-24T17:58:33Z    DEBUG   Faucet          processable request 0, address: rms1qp7xdtw5nmmnhgtxgv66wh67m3dzgjgvvadzw60xsu68xm77da8pukzcznx, amount: 1000000000
2023-10-24T17:58:33Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:58:33Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0xf99520cd255cc068d46894c3c55b74900c227ce3a368c38dcad55a9ea1c8045730000000:48), txID: SignedTransactionID(0x88ddd9519297ef5db38c6b321caf973f589218df14b68d7ac56b6f4ec244787529000000:41)
2023-10-24T17:58:33Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:58:33Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0xf99520cd255cc068d46894c3c55b74900c227ce3a368c38dcad55a9ea1c8045730000000:48), txID: TransactionID(0xbb7bb4f9245443bdd5bb59caea7e567b19ffe1dcea31ea9508720d36d37308ba29000000:41)
2023-10-24T17:58:34Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:58:34Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:58:34Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:58:36Z    DEBUG   Faucet  collected 1 requests
2023-10-24T17:58:36Z    DEBUG   Faucet  determined 1 available unspent outputs and 1 processable requests
2023-10-24T17:58:36Z    DEBUG   Faucet          unspent output 0, outputID: 0xbb7bb4f9245443bdd5bb59caea7e567b19ffe1dcea31ea9508720d36d37308ba290000000100, amount: 999861000000000, mana: 312358828527
2023-10-24T17:58:36Z    DEBUG   Faucet          processable request 0, address: rms1qq5ushhq7cp3ss8lxma0p4vuc6xey9a7dll3jg9xxj2eszjquyykurkqtl2, amount: 1000000000
2023-10-24T17:58:36Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:58:36Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0x9b018d4dfda987afb35ad6f4272ffb68bb3c759654fb83138ae86ce2b077987c31000000:49), txID: SignedTransactionID(0xdf40dc3f2e02c1b12da51aed1ede66b5d4939926c9bcc80fea98bf0fdbc3455b2a000000:42)
2023-10-24T17:58:36Z    DEBUG   Faucet  entering checkPendingTransactionState...
2023-10-24T17:58:36Z    DEBUG   Faucet  checkPendingTransactionState: transaction still pending, blockID: BlockID(0x9b018d4dfda987afb35ad6f4272ffb68bb3c759654fb83138ae86ce2b077987c31000000:49), txID: TransactionID(0xdc8b2569b0b414151dad19a9ad297ec5bbe4d8cf8009c0b37cfaec35eb5170d52a000000:42)
2023-10-24T17:58:36Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:58:36Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x9b018d4dfda987afb35ad6f4272ffb68bb3c759654fb83138ae86ce2b077987c31000000:49), txID: TransactionID(0xdc8b2569b0b414151dad19a9ad297ec5bbe4d8cf8009c0b37cfaec35eb5170d52a000000:42)
2023-10-24T17:58:37Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:58:37Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:58:37Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x9b018d4dfda987afb35ad6f4272ffb68bb3c759654fb83138ae86ce2b077987c31000000:49), txID: TransactionID(0xdc8b2569b0b414151dad19a9ad297ec5bbe4d8cf8009c0b37cfaec35eb5170d52a000000:42)
2023-10-24T17:58:38Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:58:38Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:58:40Z    DEBUG   Faucet  collected 2 requests
2023-10-24T17:58:40Z    DEBUG   Faucet  determined 1 available unspent outputs and 2 processable requests
2023-10-24T17:58:40Z    DEBUG   Faucet          unspent output 0, outputID: 0xdc8b2569b0b414151dad19a9ad297ec5bbe4d8cf8009c0b37cfaec35eb5170d52a0000000100, amount: 999860000000000, mana: 319982956072
2023-10-24T17:58:40Z    DEBUG   Faucet          processable request 0, address: rms1qqhrfmhwkuh3kxhtfza8c0lc0m6tyyfrxk9a0alq0thx730wdazkk9wt6zm, amount: 1000000000
2023-10-24T17:58:40Z    DEBUG   Faucet          processable request 1, address: rms1qrarjplc0w4edgdqfrfk2vrxmhwmcpzpu3q847vlupdd2z093990za9ahtk, amount: 1000000000
2023-10-24T17:58:40Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:58:40Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0x22bc752eec5fd7760144250fa95485e32858d7b8fe7c957042b2dbf031d3d70931000000:49), txID: SignedTransactionID(0x1aba9270be2ca540e556fd7dc816238743ca449685a714d5c96f6f2b59561be82a000000:42)
2023-10-24T17:58:40Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:58:40Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x22bc752eec5fd7760144250fa95485e32858d7b8fe7c957042b2dbf031d3d70931000000:49), txID: TransactionID(0xba5bf97c0c4cb45845458a25e70acee041e3cec9e63cb41e7d09a4dd6d1f36db2a000000:42)
2023-10-24T17:58:41Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:58:41Z    DEBUG   Faucet  entering checkPendingTransactionState...
2023-10-24T17:58:41Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:58:41Z    DEBUG   Faucet  checkPendingTransactionState: no pending transaction found
2023-10-24T17:58:41Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:58:43Z    DEBUG   Faucet  collected 1 requests
2023-10-24T17:58:43Z    DEBUG   Faucet  determined 1 available unspent outputs and 1 processable requests
2023-10-24T17:58:43Z    DEBUG   Faucet          unspent output 0, outputID: 0xba5bf97c0c4cb45845458a25e70acee041e3cec9e63cb41e7d09a4dd6d1f36db2a0000000200, amount: 999858000000000, mana: 319978086072
2023-10-24T17:58:43Z    DEBUG   Faucet          processable request 0, address: rms1qpqujv4lqc5efeku6rencrejp30wtzmeftrxm95agany3zpuhm8e58c05tv, amount: 1000000000
2023-10-24T17:58:43Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:58:43Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0xad8f422699a3ade410247f522ef14242a2d1c4cc4ec44d7db96a53e50301b4b031000000:49), txID: SignedTransactionID(0x85d85761fff282829fe00492ba5be18a8306b69c9f23f105de360564e8c8854a2a000000:42)
2023-10-24T17:58:43Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:58:43Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0xad8f422699a3ade410247f522ef14242a2d1c4cc4ec44d7db96a53e50301b4b031000000:49), txID: TransactionID(0xdeb291d4766825046130a14fb6b43227020faff7cd2db3263085db90fe54fc6a2a000000:42)
2023-10-24T17:58:44Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:58:44Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:58:44Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:58:46Z    DEBUG   Faucet  collected 1 requests
2023-10-24T17:58:46Z    DEBUG   Faucet  determined 1 available unspent outputs and 1 processable requests
2023-10-24T17:58:46Z    DEBUG   Faucet          unspent output 0, outputID: 0xdeb291d4766825046130a14fb6b43227020faff7cd2db3263085db90fe54fc6a2a0000000100, amount: 999857000000000, mana: 319973879572
2023-10-24T17:58:46Z    DEBUG   Faucet          processable request 0, address: rms1qpwf64wu74uajhcjk7x9khsmnp8ulum52rswdg5ezyf66ncrkfw859nhczn, amount: 1000000000
2023-10-24T17:58:46Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:58:46Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0xacd94036fbfec4333c520170d6f84052aa0e98ace4c74d4b05009039876a3d8832000000:50), txID: SignedTransactionID(0x83c533ee35f2452c15db1e93426125c38298a7a6c3bc5221d205065a799e966d2b000000:43)
2023-10-24T17:58:46Z    DEBUG   Faucet  entering checkPendingTransactionState...
2023-10-24T17:58:46Z    DEBUG   Faucet  checkPendingTransactionState: transaction still pending, blockID: BlockID(0xacd94036fbfec4333c520170d6f84052aa0e98ace4c74d4b05009039876a3d8832000000:50), txID: TransactionID(0xb1685e8dd6d0590edaa774348ad8db6cf11ca7d01530ed20f0550e14c98089012b000000:43)
2023-10-24T17:58:46Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:58:46Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0xacd94036fbfec4333c520170d6f84052aa0e98ace4c74d4b05009039876a3d8832000000:50), txID: TransactionID(0xb1685e8dd6d0590edaa774348ad8db6cf11ca7d01530ed20f0550e14c98089012b000000:43)
2023-10-24T17:58:47Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:58:47Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:58:47Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0xacd94036fbfec4333c520170d6f84052aa0e98ace4c74d4b05009039876a3d8832000000:50), txID: TransactionID(0xb1685e8dd6d0590edaa774348ad8db6cf11ca7d01530ed20f0550e14c98089012b000000:43)
2023-10-24T17:58:48Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:58:48Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:58:50Z    DEBUG   Faucet  collected 2 requests
2023-10-24T17:58:50Z    DEBUG   Faucet  determined 1 available unspent outputs and 2 processable requests
2023-10-24T17:58:50Z    DEBUG   Faucet          unspent output 0, outputID: 0xb1685e8dd6d0590edaa774348ad8db6cf11ca7d01530ed20f0550e14c98089012b0000000100, amount: 999856000000000, mana: 327597976599
2023-10-24T17:58:50Z    DEBUG   Faucet          processable request 0, address: rms1qps7jtt05yry4gfmff5c9qss77l77lje9jvu9tcxm03ejszv4nd5c4c27lw, amount: 1000000000
2023-10-24T17:58:50Z    DEBUG   Faucet          processable request 1, address: rms1qqxv6vm0l9mq0a3v8jq77ysr2dyk03xdc63n0qa2lzpejkkuyv7vyjsqyay, amount: 1000000000
2023-10-24T17:58:50Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:58:50Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0x9b19fa5f482374ffeeccae12d855db445d5e12937dc402993c7322564c2ce5dc32000000:50), txID: SignedTransactionID(0x88c835eb7360a94fc829d6d6026409157e346f4aa271b3608a33d615f5035cd32b000000:43)
2023-10-24T17:58:50Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:58:50Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x9b19fa5f482374ffeeccae12d855db445d5e12937dc402993c7322564c2ce5dc32000000:50), txID: TransactionID(0xba6f65842b6df975354f767d05ba40c22402037444580891fde110c6ae7d4faa2b000000:43)
2023-10-24T17:58:51Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:58:51Z    DEBUG   Faucet  entering checkPendingTransactionState...
2023-10-24T17:58:51Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:58:51Z    DEBUG   Faucet  checkPendingTransactionState: no pending transaction found
2023-10-24T17:58:51Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:58:53Z    DEBUG   Faucet  collected 1 requests
2023-10-24T17:58:53Z    DEBUG   Faucet  determined 1 available unspent outputs and 1 processable requests
2023-10-24T17:58:53Z    DEBUG   Faucet          unspent output 0, outputID: 0xba6f65842b6df975354f767d05ba40c22402037444580891fde110c6ae7d4faa2b0000000200, amount: 999854000000000, mana: 327593106599
2023-10-24T17:58:53Z    DEBUG   Faucet          processable request 0, address: rms1qq2agr9vrpcgwwr9gru3twpkr9pmwn6h7uwaz2yqylt0rxrfu85s2tk8s0n, amount: 1000000000
2023-10-24T17:58:53Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:58:53Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0x6b8a4c6e1382f4d05b36d128c830c4c914391f51d4298c2e0fd693e72915982332000000:50), txID: SignedTransactionID(0x15737d82863fede1ec28e98f6f28c83628d5e38c3a3a05bf7ff0c7d36d9e494c2b000000:43)
2023-10-24T17:58:53Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:58:53Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x6b8a4c6e1382f4d05b36d128c830c4c914391f51d4298c2e0fd693e72915982332000000:50), txID: TransactionID(0xd9117916f29a88c36b819cb1f53609b045c4a0aa06ccad116b6f7280c8bc28862b000000:43)
2023-10-24T17:58:54Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:58:54Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:58:54Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:58:56Z    DEBUG   Faucet  collected 1 requests
2023-10-24T17:58:56Z    DEBUG   Faucet  determined 1 available unspent outputs and 1 processable requests
2023-10-24T17:58:56Z    DEBUG   Faucet          unspent output 0, outputID: 0xd9117916f29a88c36b819cb1f53609b045c4a0aa06ccad116b6f7280c8bc28862b0000000100, amount: 999853000000000, mana: 327588900099
2023-10-24T17:58:56Z    DEBUG   Faucet          processable request 0, address: rms1qzd2cslyavx6m0cr9raamlw4unxly7ur7h3l0nk6lcgk8qecxpljsf9crv2, amount: 1000000000
2023-10-24T17:58:56Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:58:56Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0x4138a5e794154f01b41fe87eecbefd396aa6a789f9fa0b2985484bdbb040eb8533000000:51), txID: SignedTransactionID(0xe9f9e050ba6354d6d9e2b4f5255a2b5e3258323f312a0ac5d5ac685bef7e53492c000000:44)
2023-10-24T17:58:56Z    DEBUG   Faucet  entering checkPendingTransactionState...
2023-10-24T17:58:56Z    DEBUG   Faucet  checkPendingTransactionState: transaction still pending, blockID: BlockID(0x4138a5e794154f01b41fe87eecbefd396aa6a789f9fa0b2985484bdbb040eb8533000000:51), txID: TransactionID(0xfab4e9206b3c0be76db0a0d868cf03038e1fe544de7a9e12e08a3cd268a7479f2c000000:44)
2023-10-24T17:58:56Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:58:56Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x4138a5e794154f01b41fe87eecbefd396aa6a789f9fa0b2985484bdbb040eb8533000000:51), txID: TransactionID(0xfab4e9206b3c0be76db0a0d868cf03038e1fe544de7a9e12e08a3cd268a7479f2c000000:44)
2023-10-24T17:58:57Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:58:57Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:58:57Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x4138a5e794154f01b41fe87eecbefd396aa6a789f9fa0b2985484bdbb040eb8533000000:51), txID: TransactionID(0xfab4e9206b3c0be76db0a0d868cf03038e1fe544de7a9e12e08a3cd268a7479f2c000000:44)
2023-10-24T17:58:58Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:58:58Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:59:00Z    DEBUG   Faucet  collected 2 requests
2023-10-24T17:59:00Z    DEBUG   Faucet  determined 1 available unspent outputs and 2 processable requests
2023-10-24T17:59:00Z    DEBUG   Faucet          unspent output 0, outputID: 0xfab4e9206b3c0be76db0a0d868cf03038e1fe544de7a9e12e08a3cd268a7479f2c0000000100, amount: 999852000000000, mana: 335212966609
2023-10-24T17:59:00Z    DEBUG   Faucet          processable request 0, address: rms1qzge9r3wpljgf0zw8uygk3fdqmxalsymfalyu6832ckd406s0njhsx52tph, amount: 1000000000
2023-10-24T17:59:00Z    DEBUG   Faucet          processable request 1, address: rms1qpydlvex564957r20m4eyd2993wnwlrny450gnfzlxak63a42cy0gk58mu7, amount: 1000000000
2023-10-24T17:59:00Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:59:00Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0x3cc5e2bf35da0169a99ee12c793bec1f525d34724c6a9b1da83fb51832d4cd3433000000:51), txID: SignedTransactionID(0xbd1afe220d1113bbd9f1712889142086ea12ed0cbdf6e036ee279541901ab2ef2c000000:44)
2023-10-24T17:59:00Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:59:00Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x3cc5e2bf35da0169a99ee12c793bec1f525d34724c6a9b1da83fb51832d4cd3433000000:51), txID: TransactionID(0x10220ce70b392a509093fbcebd212a4ed4eb33cbd7a3674b34e5a8425113254a2c000000:44)
2023-10-24T17:59:01Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:59:01Z    DEBUG   Faucet  entering checkPendingTransactionState...
2023-10-24T17:59:01Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:59:01Z    DEBUG   Faucet  checkPendingTransactionState: no pending transaction found
2023-10-24T17:59:01Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:59:03Z    DEBUG   Faucet  collected 1 requests
2023-10-24T17:59:03Z    DEBUG   Faucet  determined 1 available unspent outputs and 1 processable requests
2023-10-24T17:59:03Z    DEBUG   Faucet          unspent output 0, outputID: 0x10220ce70b392a509093fbcebd212a4ed4eb33cbd7a3674b34e5a8425113254a2c0000000200, amount: 999850000000000, mana: 335208096609
2023-10-24T17:59:03Z    DEBUG   Faucet          processable request 0, address: rms1qrlytxlxguznv9adjgp4mlptzm9hdaryyxamp5zdj6ccflqk4r7ac3u7n3m, amount: 1000000000
2023-10-24T17:59:03Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:59:03Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0x8c86025f2ac7a97d5c505f6bab76ecdf30652f603b9a9fffba5ac772f7a3765a33000000:51), txID: SignedTransactionID(0xbe3f51abc003f0ffa1e68e7aa5a39e1a7b9799307aa89ca5e3849a0214b097172c000000:44)
2023-10-24T17:59:03Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:59:03Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x8c86025f2ac7a97d5c505f6bab76ecdf30652f603b9a9fffba5ac772f7a3765a33000000:51), txID: TransactionID(0x10df6f3a0c15ceb2e4895916db00f0734455ecffc9d8ce93944202a646b877b22c000000:44)
2023-10-24T17:59:04Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:59:04Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:59:04Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:59:06Z    DEBUG   Faucet  collected 1 requests
2023-10-24T17:59:06Z    DEBUG   Faucet  determined 1 available unspent outputs and 1 processable requests
2023-10-24T17:59:06Z    DEBUG   Faucet          unspent output 0, outputID: 0x10df6f3a0c15ceb2e4895916db00f0734455ecffc9d8ce93944202a646b877b22c0000000100, amount: 999849000000000, mana: 335203890109
2023-10-24T17:59:06Z    DEBUG   Faucet          processable request 0, address: rms1qrtqfy6e459qtzzlghgtgkweuzv0uqtrt7qca583ywv4ggpn59jdv2hgzsv, amount: 1000000000
2023-10-24T17:59:06Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:59:06Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0x5148b147526efa4fb22d87c08fcb12b6e312908ed2646d7baf007ba05e9df3cd34000000:52), txID: SignedTransactionID(0xa7d1f3b9a820f8474d436d9ca273e945a20c77f43aceb8e6483cc3e309c099992d000000:45)
2023-10-24T17:59:06Z    DEBUG   Faucet  entering checkPendingTransactionState...
2023-10-24T17:59:06Z    DEBUG   Faucet  checkPendingTransactionState: transaction still pending, blockID: BlockID(0x5148b147526efa4fb22d87c08fcb12b6e312908ed2646d7baf007ba05e9df3cd34000000:52), txID: TransactionID(0xaa8a1e1969133cb41600d7dbfda4eda0db62d84b74ccf2b33ebb5a4c4820a9e72d000000:45)
2023-10-24T17:59:06Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:59:06Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x5148b147526efa4fb22d87c08fcb12b6e312908ed2646d7baf007ba05e9df3cd34000000:52), txID: TransactionID(0xaa8a1e1969133cb41600d7dbfda4eda0db62d84b74ccf2b33ebb5a4c4820a9e72d000000:45)
2023-10-24T17:59:07Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:59:07Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:59:07Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x5148b147526efa4fb22d87c08fcb12b6e312908ed2646d7baf007ba05e9df3cd34000000:52), txID: TransactionID(0xaa8a1e1969133cb41600d7dbfda4eda0db62d84b74ccf2b33ebb5a4c4820a9e72d000000:45)
2023-10-24T17:59:08Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:59:08Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:59:10Z    DEBUG   Faucet  collected 2 requests
2023-10-24T17:59:10Z    DEBUG   Faucet  determined 1 available unspent outputs and 2 processable requests
2023-10-24T17:59:10Z    DEBUG   Faucet          unspent output 0, outputID: 0xaa8a1e1969133cb41600d7dbfda4eda0db62d84b74ccf2b33ebb5a4c4820a9e72d0000000100, amount: 999848000000000, mana: 342827926101
2023-10-24T17:59:10Z    DEBUG   Faucet          processable request 0, address: rms1qz2n8dgk8h4stywp934ll606z4eup3kf9phujg8p52ejc6lg36nj6d6mjer, amount: 1000000000
2023-10-24T17:59:10Z    DEBUG   Faucet          processable request 1, address: rms1qq9jlr3wsx43jl64h75znqpw4ufrr2fuf0jrqavvkd6gx2c5xnswjw776lx, amount: 1000000000
2023-10-24T17:59:10Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:59:10Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0x9c8c167a01189c82a33008e4cb14d03c44d1df51b1c13726cc70fa837e9df06a34000000:52), txID: SignedTransactionID(0x67c199c88f05b96425f398c552836fd7fdbfe7fd326bd42a7d7cdbd9ff81d7b42d000000:45)
2023-10-24T17:59:10Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:59:10Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x9c8c167a01189c82a33008e4cb14d03c44d1df51b1c13726cc70fa837e9df06a34000000:52), txID: TransactionID(0x394d486fa21cb3ca13a394076a6c140020a648991d65baf322646d5c70d855932d000000:45)
2023-10-24T17:59:11Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:59:11Z    DEBUG   Faucet  entering checkPendingTransactionState...
2023-10-24T17:59:11Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:59:11Z    DEBUG   Faucet  checkPendingTransactionState: no pending transaction found
2023-10-24T17:59:11Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:59:13Z    DEBUG   Faucet  collected 1 requests
2023-10-24T17:59:13Z    DEBUG   Faucet  determined 1 available unspent outputs and 1 processable requests
2023-10-24T17:59:13Z    DEBUG   Faucet          unspent output 0, outputID: 0x394d486fa21cb3ca13a394076a6c140020a648991d65baf322646d5c70d855932d0000000200, amount: 999846000000000, mana: 342823056101
2023-10-24T17:59:13Z    DEBUG   Faucet          processable request 0, address: rms1qzj6p9k48s8vmzcsd6k0tz729md6xzqjy2x5hn76cczgduut7k5aumv38gk, amount: 1000000000
2023-10-24T17:59:13Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:59:13Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0x434419fefc6e1cc1b32bc509a50310f12873ff21f896e9bfc307afdff17397c834000000:52), txID: SignedTransactionID(0x1e3bc5f75c71b4125e61d28b5fccdcdd2209dc2f69e359595dae7df4f82347cb2d000000:45)
2023-10-24T17:59:13Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:59:13Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x434419fefc6e1cc1b32bc509a50310f12873ff21f896e9bfc307afdff17397c834000000:52), txID: TransactionID(0x1efc68b8f6d41e9f4df86f0f699dfecfe7722666eff04cf97d333536963b182a2d000000:45)
2023-10-24T17:59:14Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:59:14Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:59:14Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:59:16Z    DEBUG   Faucet  collected 1 requests
2023-10-24T17:59:16Z    DEBUG   Faucet  determined 1 available unspent outputs and 1 processable requests
2023-10-24T17:59:16Z    DEBUG   Faucet          unspent output 0, outputID: 0x1efc68b8f6d41e9f4df86f0f699dfecfe7722666eff04cf97d333536963b182a2d0000000100, amount: 999845000000000, mana: 342818849601
2023-10-24T17:59:16Z    DEBUG   Faucet          processable request 0, address: rms1qrc6r973xnm5epnd03smcwwxapht2qhuqc9knvka558jeuq57lxx5dfzprm, amount: 1000000000
2023-10-24T17:59:16Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:59:16Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0x6825096920621ae041429ad81a7861b3975883644c7021b75a22b5d9a3fe3f5e35000000:53), txID: SignedTransactionID(0xcd80043e63c1fbdd0834e509dc2218f86a3be0745b7e48b32df260b6277ab7852e000000:46)
2023-10-24T17:59:16Z    DEBUG   Faucet  entering checkPendingTransactionState...
2023-10-24T17:59:16Z    DEBUG   Faucet  checkPendingTransactionState: transaction still pending, blockID: BlockID(0x6825096920621ae041429ad81a7861b3975883644c7021b75a22b5d9a3fe3f5e35000000:53), txID: TransactionID(0xf439aabf281eb9b5ad0e0c13e17ee73ebcac88414b073d878fbdaf885a7e631d2e000000:46)
2023-10-24T17:59:16Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:59:16Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x6825096920621ae041429ad81a7861b3975883644c7021b75a22b5d9a3fe3f5e35000000:53), txID: TransactionID(0xf439aabf281eb9b5ad0e0c13e17ee73ebcac88414b073d878fbdaf885a7e631d2e000000:46)
2023-10-24T17:59:17Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:59:17Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:59:17Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x6825096920621ae041429ad81a7861b3975883644c7021b75a22b5d9a3fe3f5e35000000:53), txID: TransactionID(0xf439aabf281eb9b5ad0e0c13e17ee73ebcac88414b073d878fbdaf885a7e631d2e000000:46)
2023-10-24T17:59:18Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:59:18Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:59:20Z    DEBUG   Faucet  collected 2 requests
2023-10-24T17:59:20Z    DEBUG   Faucet  determined 1 available unspent outputs and 2 processable requests
2023-10-24T17:59:20Z    DEBUG   Faucet          unspent output 0, outputID: 0xf439aabf281eb9b5ad0e0c13e17ee73ebcac88414b073d878fbdaf885a7e631d2e0000000100, amount: 999844000000000, mana: 350442855076
2023-10-24T17:59:20Z    DEBUG   Faucet          processable request 0, address: rms1qpgxvfft3dn6c72l7ctdf0v4638lw5ncxs9ngluusc6pgz60uxtnz6e994h, amount: 1000000000
2023-10-24T17:59:20Z    DEBUG   Faucet          processable request 1, address: rms1qpw7k5t9we7y506ethd625fahwdf9gy4jcg087weyclkhn4d0sycc92gzcs, amount: 1000000000
2023-10-24T17:59:20Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:59:20Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0x6cad821824ec8efc9b4045331d02865b68fb20f189f7efe7583d5d43a6d6939d35000000:53), txID: SignedTransactionID(0x635c7b5ba3f655e543746224126f60d26cf544c7b72345ba43ca65ee331276122e000000:46)
2023-10-24T17:59:20Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:59:20Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x6cad821824ec8efc9b4045331d02865b68fb20f189f7efe7583d5d43a6d6939d35000000:53), txID: TransactionID(0x10e3fa71951ca9869e1bf0f9f060b4f29d9314536caa7cd899bd99731f8275b52e000000:46)
2023-10-24T17:59:21Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:59:21Z    DEBUG   Faucet  entering checkPendingTransactionState...
2023-10-24T17:59:21Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:59:21Z    DEBUG   Faucet  checkPendingTransactionState: no pending transaction found
2023-10-24T17:59:21Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:59:23Z    DEBUG   Faucet  collected 1 requests
2023-10-24T17:59:23Z    DEBUG   Faucet  determined 1 available unspent outputs and 1 processable requests
2023-10-24T17:59:23Z    DEBUG   Faucet          unspent output 0, outputID: 0x10e3fa71951ca9869e1bf0f9f060b4f29d9314536caa7cd899bd99731f8275b52e0000000200, amount: 999842000000000, mana: 350437985076
2023-10-24T17:59:23Z    DEBUG   Faucet          processable request 0, address: rms1qqy99tmsp6q06m7p5xhn0p07pq3lpfmpk9tyawe46820akrjtehys9v6jjg, amount: 1000000000
2023-10-24T17:59:23Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:59:23Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0xbf10594851ea386f7f6020f9297fbf698da56181c0ca834e5da198f07bf3805935000000:53), txID: SignedTransactionID(0x239d9748d4e091983f4fd514c015f740dcb5deb81e84e76c378fe8613cd261f82e000000:46)
2023-10-24T17:59:23Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:59:23Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0xbf10594851ea386f7f6020f9297fbf698da56181c0ca834e5da198f07bf3805935000000:53), txID: TransactionID(0xd82a8a0c0f43e956fa419b4c1a3c4ae901adc135f4900bd9748dbd09929a4e762e000000:46)
2023-10-24T17:59:24Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:59:24Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:59:24Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:59:26Z    DEBUG   Faucet  collected 1 requests
2023-10-24T17:59:26Z    DEBUG   Faucet  determined 1 available unspent outputs and 1 processable requests
2023-10-24T17:59:26Z    DEBUG   Faucet          unspent output 0, outputID: 0xd82a8a0c0f43e956fa419b4c1a3c4ae901adc135f4900bd9748dbd09929a4e762e0000000100, amount: 999841000000000, mana: 350433778576
2023-10-24T17:59:26Z    DEBUG   Faucet          processable request 0, address: rms1qzyknql7mwqa07esauxzpw4dhqxp20nl9pp5fhv4lz077gzvhm0evddk7rj, amount: 1000000000
2023-10-24T17:59:26Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:59:26Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0xd8a1485c6f876a2826eaa7fba6a0e35fbfcefb3de6337d0ab9407fcae2040c3d36000000:54), txID: SignedTransactionID(0xee7352535450d29d6b1eb4a2d7fd2d54089ace675538270baa0c112d505acb982f000000:47)
2023-10-24T17:59:26Z    DEBUG   Faucet  entering checkPendingTransactionState...
2023-10-24T17:59:26Z    DEBUG   Faucet  checkPendingTransactionState: transaction still pending, blockID: BlockID(0xd8a1485c6f876a2826eaa7fba6a0e35fbfcefb3de6337d0ab9407fcae2040c3d36000000:54), txID: TransactionID(0x9f5a4eaeb2b2b274d9392941629b3bd5bac0d0c2f3ea78e16d1753996f5ad5292f000000:47)
2023-10-24T17:59:26Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:59:26Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0xd8a1485c6f876a2826eaa7fba6a0e35fbfcefb3de6337d0ab9407fcae2040c3d36000000:54), txID: TransactionID(0x9f5a4eaeb2b2b274d9392941629b3bd5bac0d0c2f3ea78e16d1753996f5ad5292f000000:47)
2023-10-24T17:59:27Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:59:27Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:59:27Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0xd8a1485c6f876a2826eaa7fba6a0e35fbfcefb3de6337d0ab9407fcae2040c3d36000000:54), txID: TransactionID(0x9f5a4eaeb2b2b274d9392941629b3bd5bac0d0c2f3ea78e16d1753996f5ad5292f000000:47)
2023-10-24T17:59:28Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:59:28Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:59:30Z    DEBUG   Faucet  collected 2 requests
2023-10-24T17:59:30Z    DEBUG   Faucet  determined 1 available unspent outputs and 2 processable requests
2023-10-24T17:59:30Z    DEBUG   Faucet          unspent output 0, outputID: 0x9f5a4eaeb2b2b274d9392941629b3bd5bac0d0c2f3ea78e16d1753996f5ad5292f0000000100, amount: 999840000000000, mana: 358057753533
2023-10-24T17:59:30Z    DEBUG   Faucet          processable request 0, address: rms1qqfu70srac7zxyjczfwp9w0933dgcvqj7v27a4hxt8h9v35zqydyskmmp46, amount: 1000000000
2023-10-24T17:59:30Z    DEBUG   Faucet          processable request 1, address: rms1qrfwwwlm3vatf8pmkz5t5h43er44he4k9hagxqeq5dhz7ftlyyqlgna8rya, amount: 1000000000
2023-10-24T17:59:30Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:59:30Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0x60c0ae501f583d1dff5821a91e64dc133738cfc5d3c048b08810f74dbfb255f436000000:54), txID: SignedTransactionID(0xebd675ad806e6d7d03f935f99c90ddb457282fd6d61e4c0cd8c2f3bd47397a622f000000:47)
2023-10-24T17:59:30Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:59:30Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x60c0ae501f583d1dff5821a91e64dc133738cfc5d3c048b08810f74dbfb255f436000000:54), txID: TransactionID(0x258aafec19460221f8810e732853d97c34d802afc74d5582c21df973854189192f000000:47)
2023-10-24T17:59:31Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:59:31Z    DEBUG   Faucet  entering checkPendingTransactionState...
2023-10-24T17:59:31Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:59:31Z    DEBUG   Faucet  checkPendingTransactionState: no pending transaction found
2023-10-24T17:59:31Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:59:33Z    DEBUG   Faucet  collected 1 requests
2023-10-24T17:59:33Z    DEBUG   Faucet  determined 1 available unspent outputs and 1 processable requests
2023-10-24T17:59:33Z    DEBUG   Faucet          unspent output 0, outputID: 0x258aafec19460221f8810e732853d97c34d802afc74d5582c21df973854189192f0000000200, amount: 999838000000000, mana: 358052883533
2023-10-24T17:59:33Z    DEBUG   Faucet          processable request 0, address: rms1qzdurdzy2n4ez7updt2rz7v7yzm4pxn8pyskan0k46w6p9fkh9hncv60l0g, amount: 1000000000
2023-10-24T17:59:33Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:59:33Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0x68593c208049aebc01ed2eabb940683a81dd478ed522f41f146369e4ece726ee36000000:54), txID: SignedTransactionID(0x04af6e3ec3ea609d46f10fa59305c07e9afcf46501ed91d8569fbecffcfa6a482f000000:47)
2023-10-24T17:59:33Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:59:33Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x68593c208049aebc01ed2eabb940683a81dd478ed522f41f146369e4ece726ee36000000:54), txID: TransactionID(0xe784fb229951e55c4f56f396356b6bc2be07a778a3349d562b173e29cd279e5d2f000000:47)
2023-10-24T17:59:34Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:59:34Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:59:34Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:59:36Z    DEBUG   Faucet  collected 1 requests
2023-10-24T17:59:36Z    DEBUG   Faucet  determined 1 available unspent outputs and 1 processable requests
2023-10-24T17:59:36Z    DEBUG   Faucet          unspent output 0, outputID: 0xe784fb229951e55c4f56f396356b6bc2be07a778a3349d562b173e29cd279e5d2f0000000100, amount: 999837000000000, mana: 358048677033
2023-10-24T17:59:36Z    DEBUG   Faucet          processable request 0, address: rms1qrdkmmh3kee9gqheu3p8h7l62808athvxtsuntfnzqutcccumv6xzyvsaxl, amount: 1000000000
2023-10-24T17:59:36Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:59:36Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0xa047b1bf37b325810186c69ea7d0274cde408ab843429d7d8b010b2d81bec97837000000:55), txID: SignedTransactionID(0x1265440970d2fcf63c016be0fc30694cc3971c7970d0080d825ddcb4f868fade30000000:48)
2023-10-24T17:59:36Z    DEBUG   Faucet  entering checkPendingTransactionState...
2023-10-24T17:59:36Z    DEBUG   Faucet  checkPendingTransactionState: transaction still pending, blockID: BlockID(0xa047b1bf37b325810186c69ea7d0274cde408ab843429d7d8b010b2d81bec97837000000:55), txID: TransactionID(0xc2bc2e85c8df872745cc60a3dd48be8f62e90ed76e26ff1dbf17155de16fb35830000000:48)
2023-10-24T17:59:36Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:59:36Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0xa047b1bf37b325810186c69ea7d0274cde408ab843429d7d8b010b2d81bec97837000000:55), txID: TransactionID(0xc2bc2e85c8df872745cc60a3dd48be8f62e90ed76e26ff1dbf17155de16fb35830000000:48)
2023-10-24T17:59:37Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:59:37Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:59:37Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0xa047b1bf37b325810186c69ea7d0274cde408ab843429d7d8b010b2d81bec97837000000:55), txID: TransactionID(0xc2bc2e85c8df872745cc60a3dd48be8f62e90ed76e26ff1dbf17155de16fb35830000000:48)
2023-10-24T17:59:38Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:59:38Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:59:40Z    DEBUG   Faucet  collected 2 requests
2023-10-24T17:59:40Z    DEBUG   Faucet  determined 1 available unspent outputs and 2 processable requests
2023-10-24T17:59:40Z    DEBUG   Faucet          unspent output 0, outputID: 0xc2bc2e85c8df872745cc60a3dd48be8f62e90ed76e26ff1dbf17155de16fb358300000000100, amount: 999836000000000, mana: 365672621472
2023-10-24T17:59:40Z    DEBUG   Faucet          processable request 0, address: rms1qze9xwgmn76yt6m6cnwwvnqgyjewxkkyj90ty7rhkkgatatkwpu85442xj9, amount: 1000000000
2023-10-24T17:59:40Z    DEBUG   Faucet          processable request 1, address: rms1qpf05hcteg88jx8vk6prhuxku3x6ll838sywghau6ul9x70p9tmvkwylduz, amount: 1000000000
2023-10-24T17:59:40Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:59:40Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0xc956be3fb6e8b449defe3294b3d173aaa9ba2e6be9e7d990ad60a33b85ba7e2a37000000:55), txID: SignedTransactionID(0xfe173dd94b119516ac3e65907cb586fe44c1f4879ebdbd5d8e925ba7c6943a9530000000:48)
2023-10-24T17:59:40Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:59:40Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0xc956be3fb6e8b449defe3294b3d173aaa9ba2e6be9e7d990ad60a33b85ba7e2a37000000:55), txID: TransactionID(0xf219d3de1b137647581fc4f2b9cc6aa20537792db707361c9c718ba833b74ab630000000:48)
2023-10-24T17:59:41Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:59:41Z    DEBUG   Faucet  entering checkPendingTransactionState...
2023-10-24T17:59:41Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:59:41Z    DEBUG   Faucet  checkPendingTransactionState: no pending transaction found
2023-10-24T17:59:41Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:59:43Z    DEBUG   Faucet  collected 1 requests
2023-10-24T17:59:43Z    DEBUG   Faucet  determined 1 available unspent outputs and 1 processable requests
2023-10-24T17:59:43Z    DEBUG   Faucet          unspent output 0, outputID: 0xf219d3de1b137647581fc4f2b9cc6aa20537792db707361c9c718ba833b74ab6300000000200, amount: 999834000000000, mana: 365667751472
2023-10-24T17:59:43Z    DEBUG   Faucet          processable request 0, address: rms1qz6krm97dkukqcd64xw7vcx230jm9af2hdnfu0m6ay5s8r2el206qw30lkz, amount: 1000000000
2023-10-24T17:59:43Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:59:43Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0x32bd8690a790c2dc36984d220c1fafa04264aa71845856e7c998475fc4d0285837000000:55), txID: SignedTransactionID(0x98356667f2fa9b562c07693cdb387f71933dc51a8babb893e567b7bc431831c230000000:48)
2023-10-24T17:59:43Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:59:43Z    DEBUG   Faucet  skip processing of new requests because a pending tx was found, blockID: BlockID(0x32bd8690a790c2dc36984d220c1fafa04264aa71845856e7c998475fc4d0285837000000:55), txID: TransactionID(0x5df0441fec407a764a13a94f9d17ae511fa2427998e9380a120eeae1229a35f630000000:48)
2023-10-24T17:59:44Z    DEBUG   Faucet  entering ApplyAcceptedTransaction...
2023-10-24T17:59:44Z    DEBUG   Faucet  ApplyAcceptedTransaction: transaction successful
2023-10-24T17:59:44Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
2023-10-24T17:59:46Z    DEBUG   Faucet  collected 1 requests
2023-10-24T17:59:46Z    DEBUG   Faucet  determined 1 available unspent outputs and 1 processable requests
2023-10-24T17:59:46Z    DEBUG   Faucet          unspent output 0, outputID: 0x5df0441fec407a764a13a94f9d17ae511fa2427998e9380a120eeae1229a35f6300000000100, amount: 999833000000000, mana: 365663544972
2023-10-24T17:59:46Z    DEBUG   Faucet          processable request 0, address: rms1qqthgezzqvawdv563sjd0jpgylad5vkc4ndq0fsxp4huyrac8y2jxw73c06, amount: 1000000000
2023-10-24T17:59:46Z    DEBUG   Faucet  sending transaction payload...
2023-10-24T17:59:46Z    DEBUG   Faucet  sent transaction payload, blockID: BlockID(0x2035e8171c5c12704bbe5160d79b2c00dd207375fa925786e2eafe99ca65f6eb38000000:56), txID: SignedTransactionID(0x6c3d6feb4281c2fe9ba18b84bbd34d6c205522e942ff8b46df2273943bc59adf31000000:49)
2023-10-24T17:59:46Z    DEBUG   Faucet  entering checkPendingTransactionState...
2023-10-24T17:59:46Z    WARN    Faucet  transaction failed, blockID: BlockID(0x2035e8171c5c12704bbe5160d79b2c00dd207375fa925786e2eafe99ca65f6eb38000000:56), txID: TransactionID(0x354317a93a23b608aec43e522f8dcb538df68a68048d1c1720f0aa0251a2940231000000:49), reason: 2
2023-10-24T17:59:46Z    DEBUG   Faucet  entering collectRequestsAndSendFaucetBlock...
```

### PR DESCRIPTION
**Pull request by jkrvivian**
* Remove `optForkAllTransactions` option. The default is to fork all transactions.
* Store conflicting transaction failure reason on TransactionMetadata `OnRejected` event.

* Rename `ConflictDAG` to `SpendDAG`.
Since we fork every transaction, not just conflicts are included.
* Rename `Conflict` to `Spender` and `ConflictID` to `SpenderID` because these objects represent transactions (transactions are generically referred to as a spender, and an output is generically referred to as a resource).

Close #462

### CODE REVIEW

File: components/dashboard/type.go [hunk 1]
```diff
@@ -151,9 +151,9 @@ type ExplorerBlock struct {
 	LikedInsteadChildren []string `json:"shallowLikeChildren"`
 	// Solid defines the solid status of the block.
 	Solid                  bool     `json:"solid"`
-	ConflictIDs            []string `json:"conflictIDs"`
-	AddedConflictIDs       []string `json:"addedConflictIDs"`
-	SubtractedConflictIDs  []string `json:"subtractedConflictIDs"`
+	SpendIDs               []string `json:"spendIDs"`
+	AddedSpendIDs          []string `json:"addedSpendIDs"`
```
Comment (piotrm50) [inline components/dashboard/type.go]: Make sure that the dashboard still works to the same extent as it did before and does not crash on the main page.

File: pkg/protocol/engine/mempool/spenddag/tests/assertions.go [hunk 2]
```diff
@@ -0,0 +1,87 @@
...
+
+// Assertions provides a set of assertions for the ConflictDAG.
+type Assertions struct {
+	f *Framework
+}
+
+// Children asserts that the given spend has the given children.
+func (a *Assertions) Children(spendAlias string, childAliases ...string) {
+	childIDs, exists := a.f.Instance.SpendChildren(a.f.SpendID(spendAlias))
+	require.True(a.f.test, exists, "Conflict %s does not exist", spendAlias)
```
Comment (piotrm50) [inline pkg/protocol/engine/mempool/spenddag/tests/assertions.go]:
```suggestion
	require.True(a.f.test, exists, "Spend %s does not exist", spendAlias)
```

File: pkg/protocol/engine/mempool/spenddag/events.go [hunk 3]
```diff
@@ -0,0 +1,47 @@
...
+import (
+	"github.com/iotaledger/hive.go/ds"
+	"github.com/iotaledger/hive.go/runtime/event"
+)
+
+// region Events ///////////////////////////////////////////////////////////////////////////////////////////////////////
+
+// Events is a container that acts as a dictionary for the events of a SpendDAG.
+type Events[SpendID, ResourceID comparable] struct {
+	// SpendCreated is triggered when a new Conflict is created.
```
Comment (piotrm50) [inline pkg/protocol/engine/mempool/spenddag/events.go]:
```suggestion
	// SpendCreated is triggered when a new Spend is created.
```

File: pkg/protocol/engine/mempool/spenddag/events.go [hunk 4]
```diff
@@ -0,0 +1,47 @@
...
+	SpendCreated *event.Event1[SpendID]
+
+	// SpendEvicted is triggered when a Conflict is evicted from the SpendDAG.
```
Comment (piotrm50) [inline pkg/protocol/engine/mempool/spenddag/events.go]:
```suggestion
	// SpendEvicted is triggered when a Spend is evicted from the SpendDAG.
```

File: pkg/protocol/engine/mempool/spenddag/events.go [hunk 5]
```diff
@@ -0,0 +1,47 @@
...
+	SpendEvicted *event.Event1[SpendID]
+
+	// ConflictingResourcesAdded is triggered when the Conflict is added to a new ConflictSet.
```
Comment (piotrm50) [inline pkg/protocol/engine/mempool/spenddag/events.go]:
```suggestion
	// ConflictingResourcesAdded is triggered when the Spend is added to a new ConflictSet.
```

Comment (piotrm50) [reply pkg/protocol/engine/mempool/spenddag/events.go]: Is that still called `ConflictSet`?

File: pkg/protocol/engine/mempool/spenddag/events.go [hunk 6]
```diff
@@ -0,0 +1,47 @@
...
+	ConflictingResourcesAdded *event.Event2[SpendID, ds.Set[ResourceID]]
+
+	// SpendParentsUpdated is triggered when the parents of a Conflict are updated.
```
Comment (piotrm50) [inline pkg/protocol/engine/mempool/spenddag/events.go]:
```suggestion
	// SpendParentsUpdated is triggered when the parents of a Spend are updated.
```

File: pkg/protocol/engine/mempool/spenddag/events.go [hunk 7]
```diff
@@ -0,0 +1,47 @@
...
+	SpendParentsUpdated *event.Event2[SpendID, ds.Set[SpendID]]
+
+	// SpendAccepted is an event that gets triggered whenever a Conflict is confirmed.
```
Comment (piotrm50) [inline pkg/protocol/engine/mempool/spenddag/events.go]:
```suggestion
	// SpendAccepted is an event that gets triggered whenever a Spend is confirmed.
```

File: pkg/protocol/engine/mempool/spenddag/events.go [hunk 8]
```diff
@@ -0,0 +1,47 @@
...
+	SpendAccepted *event.Event1[SpendID]
+
+	// SpendRejected is an event that gets triggered whenever a Conflict is rejected.
```
Comment (piotrm50) [inline pkg/protocol/engine/mempool/spenddag/events.go]:
```suggestion
	// SpendRejected is an event that gets triggered whenever a Spend is rejected.
```

File: pkg/protocol/engine/mempool/spenddag/spenddagv1/sorted_spend.go [hunk 9]
```diff
@@ -0,0 +1,197 @@
...
+	}
+
+	s.currentWeight = *s.queuedWeight
+	s.queuedWeight = nil
+
+	return true
+}
+
+// queuePreferredInsteadUpdate notifies the sortedSet that the preferred instead flag of the Spend was updated.
+func (s *sortedSpend[SpendID, ResourceID, VoteRank]) queuePreferredInsteadUpdate(conflict *Spend[SpendID, ResourceID, VoteRank]) {
```
Comment (piotrm50) [inline pkg/protocol/engine/mempool/spenddag/spenddagv1/sorted_spend.go]:
```suggestion
func (s *sortedSpend[SpendID, ResourceID, VoteRank]) queuePreferredInsteadUpdate(spend *Spend[SpendID, ResourceID, VoteRank]) {
```

File: pkg/protocol/engine/mempool/spenddag/spenddagv1/sorted_spend.go [hunk 10]
```diff
@@ -0,0 +1,197 @@
...
+	s.preferredInsteadMutex.Lock()
+	defer s.preferredInsteadMutex.Unlock()
+
+	if (s.queuedPreferredInstead == nil && s.currentPreferredInstead == conflict) ||
```
Comment (piotrm50) [inline pkg/protocol/engine/mempool/spenddag/spenddagv1/sorted_spend.go]:
```suggestion
	if (s.queuedPreferredInstead == nil && s.currentPreferredInstead == spend) ||
```

File: pkg/protocol/engine/mempool/spenddag/spenddagv1/sorted_spend.go [hunk 11]
```diff
@@ -0,0 +1,197 @@
...
+		(s.queuedPreferredInstead != nil && s.queuedPreferredInstead == conflict) ||
```
Comment (piotrm50) [inline pkg/protocol/engine/mempool/spenddag/spenddagv1/sorted_spend.go]:
```suggestion
		(s.queuedPreferredInstead != nil && s.queuedPreferredInstead == spend) ||
```

File: pkg/protocol/engine/mempool/spenddag/spenddagv1/sorted_spend.go [hunk 12]
```diff
@@ -0,0 +1,197 @@
...
+		s.sortedSet.owner.Spend == conflict {
```
Comment (piotrm50) [inline pkg/protocol/engine/mempool/spenddag/spenddagv1/sorted_spend.go]:
```suggestion
		s.sortedSet.owner.Spend == spend {
```

File: pkg/protocol/engine/mempool/spenddag/spenddagv1/sorted_spend.go [hunk 13]
```diff
@@ -0,0 +1,197 @@
...
+		return
+	}
+
+	s.queuedPreferredInstead = conflict
```
Comment (piotrm50) [inline pkg/protocol/engine/mempool/spenddag/spenddagv1/sorted_spend.go]:
```suggestion
	s.queuedPreferredInstead = spend
```

File: pkg/protocol/engine/mempool/spenddag/spenddagv1/sorted_spends.go [hunk 14]
```diff
@@ -265,34 +265,34 @@ func (s *SortedConflicts[ConflictID, ResourceID, VoteRank]) applyWeightUpdate(me
 	}
 }
 
-// fixMemberPosition fixes the position of the given member in the SortedConflicts.
-func (s *SortedConflicts[ConflictID, ResourceID, VoteRank]) fixMemberPosition(member *sortedConflict[ConflictID, ResourceID, VoteRank]) {
+// fixMemberPosition fixes the position of the given member in the SortedSpends.
+func (s *SortedSpends[SpendID, ResourceID, VoteRank]) fixMemberPosition(member *sortedSpend[SpendID, ResourceID, VoteRank]) {
 	preferredConflict := member.PreferredInstead()
```
Comment (piotrm50) [inline pkg/protocol/engine/mempool/spenddag/spenddagv1/sorted_spends.go]:
```suggestion
	preferredSpend := member.PreferredInstead()
```

File: pkg/protocol/engine/mempool/spenddag/spenddagv1/sorted_spends.go [hunk 15]
```diff
@@ -265,34 +265,34 @@ func (s *SortedConflicts[ConflictID, ResourceID, VoteRank]) applyWeightUpdate(me
...
 	memberIsPreferred := member.IsPreferred()
 
 	// the member needs to be moved up in the list
 	for currentMember := member.heavierMember; currentMember != nil && currentMember.Compare(member) == weight.Lighter; currentMember = member.heavierMember {
 		s.swapNeighbors(member, currentMember)
 
-		if currentMember == s.heaviestPreferredMember && (preferredConflict == currentMember.Conflict || memberIsPreferred || member == s.owner) {
+		if currentMember == s.heaviestPreferredMember && (preferredConflict == currentMember.Spend || memberIsPreferred || member == s.owner) {
```
Comment (piotrm50) [inline pkg/protocol/engine/mempool/spenddag/spenddagv1/sorted_spends.go]:
```suggestion
		if currentMember == s.heaviestPreferredMember && (preferredSpend == currentMember.Spend || memberIsPreferred || member == s.owner) {
```

File: pkg/protocol/engine/mempool/spenddag/spenddagv1/utils.go [hunk 16]
```diff
@@ -0,0 +1,19 @@
+package spenddagv1
+
+import (
+	"github.com/iotaledger/hive.go/ds"
+	"github.com/iotaledger/iota-core/pkg/core/weight"
+	"github.com/iotaledger/iota-core/pkg/protocol/engine/mempool/spenddag"
+)
+
+// heaviestConflict returns the largest Conflict from the given Spends.
```
Comment (piotrm50) [inline pkg/protocol/engine/mempool/spenddag/spenddagv1/utils.go]:
```suggestion
// heaviestSpend returns the largest Spend from the given Spends.
```

File: pkg/protocol/engine/mempool/spenddag/spenddagv1/utils.go [hunk 17]
```diff
@@ -0,0 +1,19 @@
...
+func heaviestConflict[SpendID, ResourceID spenddag.IDType, VoterPower spenddag.VoteRankType[VoterPower]](conflicts ds.Set[*Spend[SpendID, ResourceID, VoterPower]]) *Spend[SpendID, ResourceID, VoterPower] {
```
Comment (piotrm50) [inline pkg/protocol/engine/mempool/spenddag/spenddagv1/utils.go]:
```suggestion
func heaviestSpend[SpendID, ResourceID spenddag.IDType, VoterPower spenddag.VoteRankType[VoterPower]](spends ds.Set[*Spend[SpendID, ResourceID, VoterPower]]) *Spend[SpendID, ResourceID, VoterPower] {
```

Comment (piotrm50) [reply pkg/protocol/engine/mempool/spenddag/spenddagv1/utils.go]: Fix other occurrences in this file

File: pkg/protocol/engine/mempool/spenddag/tests/assertions.go [hunk 18]
```diff
@@ -0,0 +1,87 @@
+package tests
+
+import (
+	"github.com/stretchr/testify/require"
+)
+
+// Assertions provides a set of assertions for the ConflictDAG.
```
Comment (piotrm50) [inline pkg/protocol/engine/mempool/spenddag/tests/assertions.go]:
```suggestion
// Assertions provides a set of assertions for the SpendDAG.
```

File: pkg/protocol/engine/mempool/spenddag/tests/assertions.go [hunk 19]
```diff
@@ -0,0 +1,87 @@
...
+type Assertions struct {
+	f *Framework
+}
+
+// Children asserts that the given spend has the given children.
+func (a *Assertions) Children(spendAlias string, childAliases ...string) {
+	childIDs, exists := a.f.Instance.SpendChildren(a.f.SpendID(spendAlias))
+	require.True(a.f.test, exists, "Conflict %s does not exist", spendAlias)
+
+	require.Equal(a.f.test, len(childAliases), childIDs.Size(), "Conflict %s has wrong number of children", spendAlias)
```
Comment (piotrm50) [inline pkg/protocol/engine/mempool/spenddag/tests/assertions.go]:
```suggestion
	require.Equal(a.f.test, len(childAliases), childIDs.Size(), "Spend %s has wrong number of children", spendAlias)
```

File: pkg/protocol/engine/mempool/spenddag/tests/assertions.go [hunk 20]
```diff
@@ -0,0 +1,87 @@
...
+	for _, childAlias := range childAliases {
+		require.True(a.f.test, childIDs.Has(a.f.SpendID(childAlias)), "Conflict %s does not have child %s", spendAlias, childAlias)
```
Comment (piotrm50) [inline pkg/protocol/engine/mempool/spenddag/tests/assertions.go]:
```suggestion
		require.True(a.f.test, childIDs.Has(a.f.SpendID(childAlias)), "Spend %s does not have child %s", spendAlias, childAlias)
```

File: pkg/protocol/engine/mempool/spenddag/tests/assertions.go [hunk 21]
```diff
@@ -0,0 +1,87 @@
...
+	}
+}
+
+// Parents asserts that the given spend has the given parents.
+func (a *Assertions) Parents(spendAlias string, parentAliases ...string) {
+	parents, exists := a.f.Instance.SpendParents(a.f.SpendID(spendAlias))
+	require.True(a.f.test, exists, "Conflict %s does not exist", spendAlias)
```
Comment (piotrm50) [inline pkg/protocol/engine/mempool/spenddag/tests/assertions.go]:
```suggestion
	require.True(a.f.test, exists, "Spend %s does not exist", spendAlias)
```

File: pkg/protocol/engine/mempool/spenddag/tests/assertions.go [hunk 22]
```diff
@@ -0,0 +1,87 @@
...
+
+	require.Equal(a.f.test, len(parentAliases), parents.Size(), "Conflict %s has wrong number of parents", spendAlias)
```
Comment (piotrm50) [inline pkg/protocol/engine/mempool/spenddag/tests/assertions.go]:
```suggestion
	require.Equal(a.f.test, len(parentAliases), parents.Size(), "Spend %s has wrong number of parents", spendAlias)
```

File: pkg/protocol/engine/mempool/spenddag/tests/assertions.go [hunk 23]
```diff
@@ -0,0 +1,87 @@
...
+	for _, parentAlias := range parentAliases {
+		require.True(a.f.test, parents.Has(a.f.SpendID(parentAlias)), "Conflict %s does not have parent %s", spendAlias, parentAlias)
```
Comment (piotrm50) [inline pkg/protocol/engine/mempool/spenddag/tests/assertions.go]:
```suggestion
		require.True(a.f.test, parents.Has(a.f.SpendID(parentAlias)), "Spend %s does not have parent %s", spendAlias, parentAlias)
```

File: pkg/protocol/engine/mempool/spenddag/tests/assertions.go [hunk 24]
```diff
@@ -0,0 +1,87 @@
...
+	}
+}
+
+// LikedInstead asserts that the given spends return the given LikedInstead spends.
+func (a *Assertions) LikedInstead(spendAliases []string, likedInsteadAliases ...string) {
+	likedInsteadConflicts := a.f.LikedInstead(spendAliases...)
+
+	require.Equal(a.f.test, len(likedInsteadAliases), likedInsteadConflicts.Size(), "LikedInstead returns wrong number of spends %d instead of %d", likedInsteadConflicts.Size(), len(likedInsteadAliases))
```
Comment (piotrm50) [inline pkg/protocol/engine/mempool/spenddag/tests/assertions.go]:
```suggestion
	likedInsteadSpends := a.f.LikedInstead(spendAliases...)

	require.Equal(a.f.test, len(likedInsteadAliases), likedInsteadSpends.Size(), "LikedInstead returns wrong number of spends %d instead of %d", likedInsteadSpends.Size(), len(likedInsteadAliases))
```

File: pkg/protocol/engine/mempool/spenddag/tests/assertions.go [hunk 25]
```diff
@@ -0,0 +1,87 @@
...
+}
+
+// ConflictSets asserts that the given spend has the given conflict sets.
+func (a *Assertions) ConflictSets(spendAlias string, resourceAliases ...string) {
+	conflictSets, exists := a.f.Instance.ConflictSets(a.f.SpendID(spendAlias))
+	require.True(a.f.test, exists, "Conflict %s does not exist", spendAlias)
+
+	require.Equal(a.f.test, len(resourceAliases), conflictSets.Size(), "Conflict %s has wrong number of conflict sets", spendAlias)
+	for _, resourceAlias := range resourceAliases {
+		require.True(a.f.test, conflictSets.Has(a.f.ResourceID(resourceAlias)), "Conflict %s does not have conflict set %s", spendAlias, resourceAlias)
```
Comment (piotrm50) [inline pkg/protocol/engine/mempool/spenddag/tests/assertions.go]:
```suggestion
		require.True(a.f.test, conflictSets.Has(a.f.ResourceID(resourceAlias)), "Spend %s does not have conflict set %s", spendAlias, resourceAlias)
```

File: pkg/protocol/engine/mempool/spenddag/tests/assertions.go [hunk 26]
```diff
@@ -0,0 +1,87 @@
...
+	}
+}
+
+// Pending asserts that the given spends are pending.
+func (a *Assertions) Pending(aliases ...string) {
+	for _, alias := range aliases {
+		require.True(a.f.test, a.f.Instance.AcceptanceState(a.f.SpendIDs(alias)).IsPending(), "Conflict %s is not pending", alias)
```
Comment (piotrm50) [inline pkg/protocol/engine/mempool/spenddag/tests/assertions.go]:
```suggestion
		require.True(a.f.test, a.f.Instance.AcceptanceState(a.f.SpendIDs(alias)).IsPending(), "Spend %s is not pending", alias)
```

File: pkg/protocol/engine/mempool/spenddag/tests/assertions.go [hunk 27]
```diff
@@ -0,0 +1,87 @@
...
+	}
+}
+
+// Accepted asserts that the given spends are accepted.
+func (a *Assertions) Accepted(aliases ...string) {
+	for _, alias := range aliases {
+		require.True(a.f.test, a.f.Instance.AcceptanceState(a.f.SpendIDs(alias)).IsAccepted(), "Conflict %s is not accepted", alias)
```
Comment (piotrm50) [inline pkg/protocol/engine/mempool/spenddag/tests/assertions.go]:
```suggestion
		require.True(a.f.test, a.f.Instance.AcceptanceState(a.f.SpendIDs(alias)).IsAccepted(), "Spend %s is not accepted", alias)
```

File: pkg/protocol/engine/mempool/spenddag/tests/assertions.go [hunk 28]
```diff
@@ -0,0 +1,87 @@
...
+	}
+}
+
+// Rejected asserts that the given spends are rejected.
+func (a *Assertions) Rejected(aliases ...string) {
+	for _, alias := range aliases {
+		require.True(a.f.test, a.f.Instance.AcceptanceState(a.f.SpendIDs(alias)).IsRejected(), "Conflict %s is not rejected", alias)
```
Comment (piotrm50) [inline pkg/protocol/engine/mempool/spenddag/tests/assertions.go]:
```suggestion
		require.True(a.f.test, a.f.Instance.AcceptanceState(a.f.SpendIDs(alias)).IsRejected(), "Spend %s is not rejected", alias)
```

File: pkg/protocol/engine/mempool/tests/tests.go [hunk 29]
```diff
@@ -18,22 +18,6 @@ const (
...
 )
 
-func TestAllWithoutForkingEverything(t *testing.T, frameworkProvider func(*testing.T) *TestFramework) {
-	for testName, testCase := range map[string]func(*testing.T, *TestFramework){
-		"TestProcessTransaction":                   TestProcessTransaction,
-		"TestProcessTransactionsOutOfOrder":        TestProcessTransactionsOutOfOrder,
-		"TestSetInclusionSlot":                     TestSetInclusionSlot,
-		"TestSetTransactionOrphanage":              TestSetTransactionOrphanage,
-		"TestStateDiff":                            TestStateDiff,
-		"TestMemoryRelease":                        TestMemoryRelease,
```
Comment (piotrm50) [inline pkg/protocol/engine/mempool/tests/tests.go:28]: It seems like some tests are not used anymore after removing `TestAllWithoutForkingEverything` but were not deleted from the code (e.g. `TestConflictPropagationForkOnDoubleSpend`).

File: pkg/protocol/engine/mempool/spenddag/spenddagv1/spend.go [hunk 30]
```diff
@@ -16,70 +16,70 @@ import (
...
 
-	// likedInsteadSources is a mapping of liked instead Conflicts to the set of parents that inherited them.
-	likedInsteadSources *shrinkingmap.ShrinkingMap[ConflictID, ds.Set[*Conflict[ConflictID, ResourceID, VoteRank]]]
+	// likedInsteadSources is a mapping of liked instead Spends to the set of parents that inherited them.
+	likedInsteadSources *shrinkingmap.ShrinkingMap[SpendID, ds.Set[*Spend[SpendID, ResourceID, VoteRank]]]
 
 	// likedInsteadMutex and structureMutex are sometimes locked in different order by different goroutines, which could result in a deadlock
 	//  however, it's impossible to deadlock if we fork all transactions upon booking
 	//  deadlock happens when the likedInstead conflict changes and parents are updated at the same time, which is impossible in the current setup
 	//  because we won't process votes on a conflict we're just creating.
```
Comment (piotrm50) [inline pkg/protocol/engine/mempool/spenddag/spenddagv1/spend.go]:
```suggestion
	//  because we won't process votes on a spend we're just creating.
```

File: pkg/protocol/engine/mempool/spenddag/spenddagv1/spend.go [hunk 31]
```diff
@@ -16,70 +16,70 @@ import (
...
+	likedInstead ds.Set[*Spend[SpendID, ResourceID, VoteRank]]
 
-	// likedInsteadSources is a mapping of liked instead Conflicts to the set of parents that inherited them.
-	likedInsteadSources *shrinkingmap.ShrinkingMap[ConflictID, ds.Set[*Conflict[ConflictID, ResourceID, VoteRank]]]
+	// likedInsteadSources is a mapping of liked instead Spends to the set of parents that inherited them.
+	likedInsteadSources *shrinkingmap.ShrinkingMap[SpendID, ds.Set[*Spend[SpendID, ResourceID, VoteRank]]]
 
 	// likedInsteadMutex and structureMutex are sometimes locked in different order by different goroutines, which could result in a deadlock
 	//  however, it's impossible to deadlock if we fork all transactions upon booking
 	//  deadlock happens when the likedInstead conflict changes and parents are updated at the same time, which is impossible in the current setup
```
Comment (piotrm50) [inline pkg/protocol/engine/mempool/spenddag/spenddagv1/spend.go]:
```suggestion
	//  deadlock happens when the likedInstead spend changes and parents are updated at the same time, which is impossible in the current setup
```

File: pkg/protocol/engine/mempool/spenddag/spenddagv1/spend.go [hunk 32]
```diff
@@ -230,60 +230,60 @@ func (c *Conflict[ConflictID, ResourceID, VoteRank]) ApplyVote(vote *vote.Vote[V
...
 
-// Shutdown shuts down the Conflict.
-func (c *Conflict[ConflictID, ResourceID, VoteRank]) Shutdown() {
-	c.ConflictingConflicts.Shutdown()
+// Shutdown shuts down the Spend.
+func (c *Spend[SpendID, ResourceID, VoteRank]) Shutdown() {
+	c.ConflictingSpends.Shutdown()
 }
 
 // Evict cleans up the sortedConflict.
```
Comment (piotrm50) [inline pkg/protocol/engine/mempool/spenddag/spenddagv1/spend.go]:
```suggestion
// Evict cleans up the sortedSpend.
```

File: pkg/protocol/engine/mempool/spenddag/spenddagv1/spend.go [hunk 33]
```diff
@@ -292,13 +292,13 @@ func (c *Conflict[ConflictID, ResourceID, VoteRank]) Evict() (evictedConflicts [
 
 	switch c.Weight.AcceptanceState() {
 	case acceptance.Rejected:
-		// evict the entire future cone of rejected conflicts
-		c.Children.Range(func(childConflict *Conflict[ConflictID, ResourceID, VoteRank]) {
+		// evict the entire future cone of rejected spends
+		c.Children.Range(func(childConflict *Spend[SpendID, ResourceID, VoteRank]) {
```
Comment (piotrm50) [inline pkg/protocol/engine/mempool/spenddag/spenddagv1/spend.go]: `childConflict` -> `childSpend`

File: pkg/protocol/engine/mempool/spenddag/spenddagv1/spend_test.go [hunk 34]
```diff
@@ -0,0 +1,622 @@
...
+	"github.com/iotaledger/iota-core/pkg/core/vote"
+	"github.com/iotaledger/iota-core/pkg/core/weight"
+	iotago "github.com/iotaledger/iota.go/v4"
+)
+
+type TestSpend = *Spend[iotago.TransactionID, iotago.OutputID, vote.MockedRank]
+
+//var NewTestSpend = NewSpend[iotago.TransactionID, iotago.OutputID, vote.MockedRank]
+
+func NewTestSpend(id iotago.TransactionID, parentConflicts ds.Set[*Spend[iotago.TransactionID, iotago.OutputID, vote.MockedRank]], SpendSets ds.Set[*ConflictSet[iotago.TransactionID, iotago.OutputID, vote.MockedRank]], initialWeight *weight.Weight, pendingTasksCounter *syncutils.Counter, acceptanceThresholdProvider func() int64) *Spend[iotago.TransactionID, iotago.OutputID, vote.MockedRank] {
```
Comment (piotrm50) [inline pkg/protocol/engine/mempool/spenddag/spenddagv1/spend_test.go]:
```suggestion
func NewTestSpend(id iotago.TransactionID, parentSpends ds.Set[*Spend[iotago.TransactionID, iotago.OutputID, vote.MockedRank]], SpendSets ds.Set[*ConflictSet[iotago.TransactionID, iotago.OutputID, vote.MockedRank]], initialWeight *weight.Weight, pendingTasksCounter *syncutils.Counter, acceptanceThresholdProvider func() int64) *Spend[iotago.TransactionID, iotago.OutputID, vote.MockedRank] {
```

File: pkg/protocol/engine/mempool/spenddag/spenddagv1/spend_test.go [hunk 35]
```diff
@@ -0,0 +1,622 @@
...
+	spend := NewSpend[iotago.TransactionID, iotago.OutputID, vote.MockedRank](id, initialWeight, pendingTasksCounter, acceptanceThresholdProvider)
+	_, err := spend.JoinSpendSets(SpendSets)
+	if err != nil {
+		// TODO: change this
+		panic(err)
+	}
+	spend.UpdateParents(parentConflicts, ds.NewSet[*Spend[iotago.TransactionID, iotago.OutputID, vote.MockedRank]]())
```
Comment (piotrm50) [inline pkg/protocol/engine/mempool/spenddag/spenddagv1/spend_test.go]:
```suggestion
	spend.UpdateParents(parentSpends, ds.NewSet[*Spend[iotago.TransactionID, iotago.OutputID, vote.MockedRank]]())
```

File: pkg/protocol/engine/mempool/spenddag/spenddagv1/spend_test.go [hunk 36]
```diff
@@ -0,0 +1,622 @@
...
+
+	return spend
+}
+
+func TestConflict_SetRejected(t *testing.T) {
```
Comment (piotrm50) [inline pkg/protocol/engine/mempool/spenddag/spenddagv1/spend_test.go]:
```suggestion
func TestSpend_SetRejected(t *testing.T) {
```

File: pkg/protocol/engine/mempool/spenddag/spenddagv1/spend_test.go [hunk 37]
```diff
@@ -0,0 +1,622 @@
...
+	weights := account.NewSeatedAccounts(account.NewAccounts())
+	pendingTasks := syncutils.NewCounter()
+
+	thresholdProvider := acceptance.ThresholdProvider(func() int64 {
+		return int64(weights.SeatCount())
+	})
+
+	Spend1 := NewTestSpend(transactionID("Conflict1"), nil, nil, weight.New(), pendingTasks, thresholdProvider)
```
Comment (piotrm50) [inline pkg/protocol/engine/mempool/spenddag/spenddagv1/spend_test.go]:
```suggestion
	Spend1 := NewTestSpend(transactionID("Spend1"), nil, nil, weight.New(), pendingTasks, thresholdProvider)
```

Comment (piotrm50) [reply pkg/protocol/engine/mempool/spenddag/spenddagv1/spend_test.go]: Rename the remaining aliases.

File: pkg/protocol/engine/mempool/spenddag/spenddagv1/spend_test.go [hunk 38]
```diff
@@ -0,0 +1,622 @@
...
+	assertPreferredInstead(t, lo.MergeMaps(preferredInsteadMap, map[TestSpend]TestSpend{
+		SpendD: SpendF,
+		SpendE: SpendF,
+		SpendF: SpendF,
+	}))
+
+	assertCorrectOrder(t, SpendA, SpendB, SpendC, SpendD, SpendE, SpendF)
+}
+
+func TestConflictParallel(t *testing.T) {
```
Comment (piotrm50) [inline pkg/protocol/engine/mempool/spenddag/spenddagv1/spend_test.go]:
```suggestion
func TestSpendsParallel(t *testing.T) {
```

File: pkg/protocol/engine/mempool/spenddag/spenddagv1/spend_test.go [hunk 39]
```diff
@@ -0,0 +1,622 @@
...
+	sequentialPendingTasks := syncutils.NewCounter()
+	parallelPendingTasks := syncutils.NewCounter()
+
+	sequentialConflicts := createConflicts(sequentialPendingTasks)
```
Comment (piotrm50) [inline pkg/protocol/engine/mempool/spenddag/spenddagv1/spend_test.go]: Rename to `createSpends`.

File: pkg/protocol/engine/mempool/spenddag/spenddagv1/spend_test.go [hunk 40]
```diff
@@ -0,0 +1,622 @@
...
+	sequentialPendingTasks.WaitIsZero()
+
+	parallelConflicts := createConflicts(parallelPendingTasks)
+	parallelPendingTasks.WaitIsZero()
+
+	const updateCount = 100000
+
+	permutations := make([]func(Spend TestSpend), 0)
+	for i := 0; i < updateCount; i++ {
+		permutations = append(permutations, generateRandomConflictPermutation())
```
Comment (piotrm50) [inline pkg/protocol/engine/mempool/spenddag/spenddagv1/spend_test.go]: Rename to `generateRandomSpendPermutation`.

File: pkg/protocol/engine/mempool/spenddag/spenddagv1/spend_test.go [hunk 41]
```diff
@@ -0,0 +1,622 @@
...
+}
+
+func TestConflictParallel(t *testing.T) {
+	sequentialPendingTasks := syncutils.NewCounter()
+	parallelPendingTasks := syncutils.NewCounter()
+
+	sequentialConflicts := createConflicts(sequentialPendingTasks)
+	sequentialPendingTasks.WaitIsZero()
+
+	parallelConflicts := createConflicts(parallelPendingTasks)
```
Comment (piotrm50) [inline pkg/protocol/engine/mempool/spenddag/spenddagv1/spend_test.go]: `parallelConflicts` -> `parallelSpends`

File: pkg/protocol/engine/mempool/spenddag/spenddagv1/spend_test.go [hunk 42]
```diff
@@ -0,0 +1,622 @@
...
+	permutations := make([]func(Spend TestSpend), 0)
+	for i := 0; i < updateCount; i++ {
+		permutations = append(permutations, generateRandomConflictPermutation())
+	}
+
+	var wg sync.WaitGroup
+	for _, permutation := range permutations {
+		targetAlias := lo.Keys(parallelConflicts)[rand.Intn(len(parallelConflicts))]
+
+		permutation(sequentialConflicts[targetAlias])
```
Comment (piotrm50) [inline pkg/protocol/engine/mempool/spenddag/spenddagv1/spend_test.go]: `sequentialConflicts` -> `sequentialSpends`

File: pkg/protocol/engine/mempool/spenddag/spenddagv1/spend_test.go [hunk 43]
```diff
@@ -0,0 +1,622 @@
...
+	pendingTasks.WaitIsZero()
+	require.True(t, Spend3.LikedInstead().IsEmpty())
+}
+
+func assertCorrectOrder(t *testing.T, spends ...TestSpend) {
+	sort.Slice(spends, func(i, j int) bool {
+		return spends[i].Compare(spends[j]) == weight.Heavier
+	})
+
+	preferredConflicts := ds.NewSet[TestSpend]()
```
Comment (piotrm50) [inline pkg/protocol/engine/mempool/spenddag/spenddagv1/spend_test.go]: preferredSpends
unPreferredSpends

File: pkg/protocol/engine/mempool/spenddag/spenddagv1/spend_test.go [hunk 44]
```diff
@@ -0,0 +1,622 @@
...
+		"SpendB": SpendB,
+		"SpendC": SpendC,
+		"SpendD": SpendD,
+		"SpendE": SpendE,
+	}
+}
+
+func assertPreferredInstead(t *testing.T, preferredInsteadMap map[TestSpend]TestSpend) {
+	for Spend, preferredInsteadConflict := range preferredInsteadMap {
+		assert.Equalf(t, preferredInsteadConflict.ID, Spend.PreferredInstead().ID, "Spend %s should prefer %s instead of %s", Spend.ID, preferredInsteadConflict.ID, Spend.PreferredInstead().ID)
```
Comment (piotrm50) [inline pkg/protocol/engine/mempool/spenddag/spenddagv1/spend_test.go]:
```suggestion
	for Spend, preferredInsteadSpend := range preferredInsteadMap {
		assert.Equalf(t, preferredInsteadSpend.ID, Spend.PreferredInstead().ID, "Spend %s should prefer %s instead of %s", Spend.ID, preferredInsteadConflict.ID, Spend.PreferredInstead().ID)
```

File: pkg/protocol/engine/mempool/spenddag/spenddagv1/spenddag.go [hunk 45]
```diff
@@ -0,0 +1,509 @@
...
+
+		removedParents, err := c.spends(removedParentIDs, !currentSpend.IsRejected())
+		if err != nil {
+			return false, ierrors.Errorf("failed to update spend parents: %w", err)
+		}
+
+		updated := currentSpend.UpdateParents(addedParents, removedParents)
+		if updated {
+			_ = currentSpend.Parents.ForEach(func(parentConflict *Spend[SpendID, ResourceID, VoteRank]) (err error) {
+				newParents.Add(parentConflict.ID)
```
Comment (piotrm50) [inline pkg/protocol/engine/mempool/spenddag/spenddagv1/spenddag.go]:
```suggestion
			_ = currentSpend.Parents.ForEach(func(parentSpend *Spend[SpendID, ResourceID, VoteRank]) (err error) {
				newParents.Add(parentSpend.ID)
```

File: pkg/protocol/engine/mempool/spenddag/spenddagv1/spenddag.go [hunk 46]
```diff
@@ -0,0 +1,509 @@
...
+	return nil
+}
+
+// LikedInstead returns the SpendIDs of the Spends that are liked instead of the Spends.
+func (c *SpendDAG[SpendID, ResourceID, VoteRank]) LikedInstead(spendIDs ds.Set[SpendID]) ds.Set[SpendID] {
+	likedInstead := ds.NewSet[SpendID]()
+	spendIDs.Range(func(spendID SpendID) {
+		if currentConflict, exists := c.spendsByID.Get(spendID); exists {
+			if likedConflict := heaviestConflict(currentConflict.LikedInstead()); likedConflict != nil {
+				likedInstead.Add(likedConflict.ID)
```
Comment (piotrm50) [inline pkg/protocol/engine/mempool/spenddag/spenddagv1/spenddag.go]:
```suggestion
		if currentSpend, exists := c.spendsByID.Get(spendID); exists {
			if likedSpend := heaviestConflict(currentSpend.LikedInstead()); likedConflict != nil {
				likedInstead.Add(likedSpend.ID)
```

File: pkg/protocol/engine/mempool/spenddag/spenddagv1/spenddag.go [hunk 47]
```diff
@@ -0,0 +1,509 @@
...
+
+func (c *SpendDAG[SpendID, ResourceID, VoteRank]) AllSpendsSupported(seat account.SeatIndex, spendIDs ds.Set[SpendID]) bool {
+	return lo.Return1(c.spends(spendIDs, true)).ForEach(func(spend *Spend[SpendID, ResourceID, VoteRank]) (err error) {
+		lastVote, exists := spend.LatestVotes.Get(seat)
+
+		return lo.Cond(exists && lastVote.IsLiked(), nil, ierrors.Errorf("spend with %s is not supported by seat %d", spend.ID, seat))
+	}) == nil
+}
+
+func (c *SpendDAG[SpendID, ResourceID, VoteRank]) SpendVoters(spendID SpendID) (conflictVoters ds.Set[account.SeatIndex]) {
```
Comment (piotrm50) [inline pkg/protocol/engine/mempool/spenddag/spenddagv1/spenddag.go]:
```suggestion
func (c *SpendDAG[SpendID, ResourceID, VoteRank]) SpendVoters(spendID SpendID) (spendVoters ds.Set[account.SeatIndex]) {
```

File: pkg/protocol/engine/mempool/spenddag/spenddagv1/spenddag.go [hunk 48]
```diff
@@ -0,0 +1,509 @@
...
+	spendChildren = ds.NewSet[SpendID]()
+	_ = spend.Children.ForEach(func(parent *Spend[SpendID, ResourceID, VoteRank]) error {
+		spendChildren.Add(parent.ID)
+		return nil
+	})
+
+	return spendChildren, true
+}
+
+func (c *SpendDAG[SpendID, ResourceID, VoteRank]) ConflictSetMembers(conflictSetID ResourceID) (conflicts ds.Set[SpendID], exists bool) {
```
Comment (piotrm50) [inline pkg/protocol/engine/mempool/spenddag/spenddagv1/spenddag.go]: `conflicts` -> `spends`

File: pkg/protocol/engine/mempool/spenddag/spenddagv1/spenddag.go [hunk 49]
```diff
@@ -0,0 +1,509 @@
...
+	spendIDs.Range(func(currentSpendID SpendID) {
+		if spend, exists := c.spendsByID.Get(currentSpendID); exists && !spend.IsAccepted() {
+			pendingSpendIDs.Add(currentSpendID)
+		}
+	})
+
+	return pendingSpendIDs
+}
+
+// EvictConflict removes spend with given SpendID from spenddag.
```
Comment (piotrm50) [inline pkg/protocol/engine/mempool/spenddag/spenddagv1/spenddag.go]:
```suggestion
// EvictSpend removes spend with given SpendID from spenddag.
```

File: pkg/protocol/engine/mempool/spenddag/spenddagv1/spenddag.go [hunk 50]
```diff
@@ -0,0 +1,509 @@
...
+func (c *SpendDAG[SpendID, ResourceID, VoteRank]) evictSpend(spendID SpendID) []SpendID {
+	// evicting an already evicted spend is fine
+	spend, exists := c.spendsByID.Get(spendID)
+	if !exists {
+		return nil
+	}
+
+	evictedSpendIDs := spend.Evict()
+
+	// remove the conflicts from the spenddag dictionary
```
Comment (piotrm50) [inline pkg/protocol/engine/mempool/spenddag/spenddagv1/spenddag.go]:
```suggestion
	// remove the spends from the spenddag dictionary
```

File: pkg/protocol/engine/mempool/spenddag/spenddagv1/spenddag.go [hunk 51]
```diff
@@ -0,0 +1,509 @@
...
+
+	resourceIDs.Range(func(resourceID ResourceID) {
+		conflictSets.Add(lo.Return1(c.conflictSetsByID.GetOrCreate(resourceID, c.conflictSetFactory(resourceID))))
+	})
+
+	return conflictSets
+}
+
+// determineVotes determines the Spends that are supported and revoked by the given SpendIDs.
+func (c *SpendDAG[SpendID, ResourceID, VoteRank]) determineVotes(spendIDs ds.Set[SpendID]) (supportedSpends ds.Set[*Spend[SpendID, ResourceID, VoteRank]], revokedSpends ds.Set[*Spend[SpendID, ResourceID, VoteRank]], err error) {
```
Comment (piotrm50) [inline pkg/protocol/engine/mempool/spenddag/spenddagv1/spenddag.go]: Replace conflict with spend in this entire method.

**Review by piotrm50 — CHANGES_REQUESTED** [review]
Please run a search through the whole codebase again as there seems to be a lot `conflicts` left.

File: pkg/protocol/engine/mempool/spenddag/events.go (hunk 5 above)
Comment (jkrvivian) [reply pkg/protocol/engine/mempool/spenddag/events.go]: Yes, a set of conflicting spends is still called ConflictSet.

File: pkg/protocol/engine/booker/inmemorybooker/booker.go [hunk 52]
```diff
@@ -198,30 +198,30 @@ func (b *Booker) inheritConflicts(block *blocks.Block) (conflictIDs ds.Set[iotag
...
+			for _, spendID := range parentBlock.PayloadSpendIDs().ToSlice() {
+				if conflictingSpends, exists := b.spendDAG.ConflictingSpends(spendID); exists {
+					spendIDsToInherit.DeleteAll(b.spendDAG.FutureCone(conflictingSpends))
 				}
 			}
 		}
 	}
 
-	// Add all conflicts from the block's payload itself.
-	// Forking on booking: we determine the block's PayloadConflictIDs by treating each TX as a conflict.
```
Comment (cyberphysic4l) [inline pkg/protocol/engine/booker/inmemorybooker/booker.go:222]: Is this still the case? In our terminology we are not longer treating each TX as a conflict, but as a separate spend.

File: pkg/protocol/engine/booker/inmemorybooker/booker.go [hunk 53]
```diff
@@ -198,30 +198,30 @@ func (b *Booker) inheritConflicts(block *blocks.Block) (conflictIDs ds.Set[iotag
...
-	conflictIDsToInherit.AddAll(block.PayloadConflictIDs())
+	// Add all spends from the block's payload itself.
+	// Forking on booking: we determine the block's PayloadSpendIDs by treating each TX as a conflict.
```
Comment (cyberphysic4l) [inline pkg/protocol/engine/booker/inmemorybooker/booker.go]: Is this still the case? I think we don't treat all TX as a conflict anymore, but as a spend.

**Comment by cyberphysic4l** [comment]
- A spendable resource is identified by an` iotago.OutputID`, we don't need a generic `ResourceID`  just for the spend DAG because we are always talking about about utxos which are just `iotago.Output` . We should drop the generic "resource" because it's not actually generic in how we use it so it is just unhelpful. resources should be referred to as utxos.

- A Transaction contains one or more spends, each of different outputs. A spend can be therefore be identified by a tuple `(iotago.TransactionID, iotago.OutputID)` . What we previously called `SpendID`  or `ConflictID ` was actually just a `iotago.TransactionID` . This is incorrect because a spend != transaction, it is a spend of a specific utxo within a transaction, so it needs a transaction ID and output ID to identify it uniquely. We should get rid of `ConflictID/SpendID`  altogether.

- What we previously called a `ConflictSet`  should now be a called a `SpendSet` . Each `SpendSet` corresponds to a single utxo. If the `SpendSet`  contains more than one spend for that utxo, then we say that it contains a conflict. There will be no object called a conflict anymore, but a conflict can be identified by a spend set containing more than one spend or by a spend with a set of `ConflictingSpends` associated to it that is not empty.

File: components/dashboard/frontend/src/app/components/ExplorerAddressResult.tsx [hunk 54]
```diff
@@ -222,10 +222,10 @@ class OutputMeta extends React.Component<omProps, any> {
         let pendingMana = this.props.pendingMana;
         return (
             <ListGroup>
-                ConflictIDs: 
+                spendIDs:
```
Comment (piotrm50) [inline components/dashboard/frontend/src/app/components/ExplorerAddressResult.tsx]: Missing capital letter in `Spend` here and in other .tsx files.

File: pkg/protocol/engine/mempool/spenddag/spenddagv1/spend_set.go [hunk 55]
```diff
@@ -0,0 +1,73 @@
...
+func NewSpendSet[SpendID, ResourceID spenddag.IDType, VoteRank spenddag.VoteRankType[VoteRank]](id ResourceID) *SpendSet[SpendID, ResourceID, VoteRank] {
+	return &SpendSet[SpendID, ResourceID, VoteRank]{
+		ID:                id,
+		allMembersEvicted: reactive.NewVariable[bool](),
+		members:           ds.NewSet[*Spend[SpendID, ResourceID, VoteRank]](),
+	}
+}
+
+// Add adds a Spend to the SpendSet and returns all other members of the set.
+func (c *SpendSet[SpendID, ResourceID, VoteRank]) Add(addedConflict *Spend[SpendID, ResourceID, VoteRank]) (otherMembers ds.Set[*Spend[SpendID, ResourceID, VoteRank]], err error) {
```
Comment (piotrm50) [inline pkg/protocol/engine/mempool/spenddag/spenddagv1/spend_set.go]:
```suggestion
func (c *SpendSet[SpendID, ResourceID, VoteRank]) Add(addedSpend *Spend[SpendID, ResourceID, VoteRank]) (otherMembers ds.Set[*Spend[SpendID, ResourceID, VoteRank]], err error) {
```

File: pkg/protocol/engine/mempool/spenddag/spenddagv1/spend_set.go [hunk 56]
```diff
@@ -0,0 +1,73 @@
...
+	c.mutex.Lock()
+	defer c.mutex.Unlock()
+
+	if c.allMembersEvicted.Get() {
+		return nil, ierrors.New("cannot join a SpendSet whose all members are evicted")
+	}
+
+	if otherMembers = c.members.Clone(); !c.members.Add(addedConflict) {
```
Comment (piotrm50) [inline pkg/protocol/engine/mempool/spenddag/spenddagv1/spend_set.go]:
```suggestion
	if otherMembers = c.members.Clone(); !c.members.Add(addedSpend) {
```

File: pkg/protocol/engine/mempool/spenddag/spenddagv1/spend_set.go [hunk 57]
```diff
@@ -0,0 +1,73 @@
...
+	return otherMembers, nil
+
+}
+
+// Remove removes a Spend from the SpendSet and returns all remaining members of the set.
+func (c *SpendSet[SpendID, ResourceID, VoteRank]) Remove(removedConflict *Spend[SpendID, ResourceID, VoteRank]) (removed bool) {
+	c.mutex.Lock()
+	defer c.mutex.Unlock()
+
+	if removed = c.members.Delete(removedConflict); removed && c.members.IsEmpty() {
```
Comment (piotrm50) [inline pkg/protocol/engine/mempool/spenddag/spenddagv1/spend_set.go]:
```suggestion
	if removed = c.members.Delete(removedSpend); removed && c.members.IsEmpty() {
```

File: pkg/protocol/engine/mempool/spenddag/spenddagv1/spend_set.go [hunk 58]
```diff
@@ -0,0 +1,73 @@
...
+	if otherMembers = c.members.Clone(); !c.members.Add(addedConflict) {
+		return nil, spenddag.ErrAlreadyPartOfSpendSet
+	}
+
+	return otherMembers, nil
+
+}
+
+// Remove removes a Spend from the SpendSet and returns all remaining members of the set.
+func (c *SpendSet[SpendID, ResourceID, VoteRank]) Remove(removedConflict *Spend[SpendID, ResourceID, VoteRank]) (removed bool) {
```
Comment (piotrm50) [inline pkg/protocol/engine/mempool/spenddag/spenddagv1/spend_set.go]:
```suggestion
func (c *SpendSet[SpendID, ResourceID, VoteRank]) Remove(removedSpend *Spend[SpendID, ResourceID, VoteRank]) (removed bool) {
```

File: pkg/protocol/engine/mempool/spenddag/tests/assertions.go [hunk 59]
```diff
@@ -4,80 +4,80 @@ import (
...
-		require.True(a.f.test, conflictSetMembers.Has(a.f.SpendID(spendAlias)), "Resource %s does not have parent %s", resourceAlias, spendAlias)
+		require.True(a.f.test, spendSetMembers.Has(a.f.SpendID(spendAlias)), "Resource %s does not have parent %s", resourceAlias, spendAlias)
 	}
 }
 
-// ConflictSets asserts that the given spend has the given conflict sets.
-func (a *Assertions) ConflictSets(spendAlias string, resourceAliases ...string) {
-	conflictSets, exists := a.f.Instance.ConflictSets(a.f.SpendID(spendAlias))
-	require.True(a.f.test, exists, "Conflict %s does not exist", spendAlias)
+// SpendSets asserts that the given spend has the given conflict sets.
```
Comment (piotrm50) [inline pkg/protocol/engine/mempool/spenddag/tests/assertions.go]:
```suggestion
// SpendSets asserts that the given spend has the given spend sets.
```

File: pkg/protocol/engine/mempool/spenddag/tests/assertions.go [hunk 60]
```diff
@@ -4,80 +4,80 @@ import (
...
+func (a *Assertions) SpendSets(spendAlias string, resourceAliases ...string) {
+	spendSets, exists := a.f.Instance.SpendSets(a.f.SpendID(spendAlias))
+	require.True(a.f.test, exists, "Spend %s does not exist", spendAlias)
 
-	require.Equal(a.f.test, len(resourceAliases), conflictSets.Size(), "Conflict %s has wrong number of conflict sets", spendAlias)
+	require.Equal(a.f.test, len(resourceAliases), spendSets.Size(), "Spend %s has wrong number of conflict sets", spendAlias)
```
Comment (piotrm50) [inline pkg/protocol/engine/mempool/spenddag/tests/assertions.go]:
```suggestion
	require.Equal(a.f.test, len(resourceAliases), spendSets.Size(), "Spend %s has wrong number of spend sets", spendAlias)
```

File: pkg/protocol/engine/mempool/spenddag/tests/assertions.go [hunk 61]
```diff
@@ -4,80 +4,80 @@ import (
...
 	for _, resourceAlias := range resourceAliases {
-		require.True(a.f.test, conflictSets.Has(a.f.ResourceID(resourceAlias)), "Conflict %s does not have conflict set %s", spendAlias, resourceAlias)
+		require.True(a.f.test, spendSets.Has(a.f.ResourceID(resourceAlias)), "Spend %s does not have conflict set %s", spendAlias, resourceAlias)
```
Comment (piotrm50) [inline pkg/protocol/engine/mempool/spenddag/tests/assertions.go]:
```suggestion
		require.True(a.f.test, spendSets.Has(a.f.ResourceID(resourceAlias)), "Spend %s does not have spend set %s", spendAlias, resourceAlias)
```

Comment (piotrm50) [inline pkg/protocol/engine/mempool/spenddag/tests/assertions.go]:
```suggestion
		require.True(a.f.test, spendSets.Has(a.f.ResourceID(resourceAlias)), "Spend %s does not have spend set %s", spendAlias, resourceAlias)
```

File: pkg/protocol/engine/mempool/spenddag/tests/tests.go [hunk 62]
```diff
@@ -14,38 +14,38 @@ import (
...
+		"EvictAcceptedSpend":          EvictAcceptedSpend,
+		"EvictRejectedSpend":          EvictRejectedSpend,
 	} {
 		t.Run(testName, func(t *testing.T) { testCase(t, frameworkProvider(t)) })
 	}
 }
 
-func ExistingSpendJoinsConflictSets(t *testing.T, tf *Framework) {
+func ExistingSpendJoinsSpendSets(t *testing.T, tf *Framework) {
 	require.NoError(t, tf.CreateOrUpdateSpend("conflict1", []string{"resource1"}))
```
Comment (piotrm50) [inline pkg/protocol/engine/mempool/spenddag/tests/tests.go]: Rename aliases to `spendX`

File: pkg/protocol/engine/mempool/tests/tests.go [hunk 63]
```diff
@@ -311,47 +248,16 @@ func TestSetTxOrphanageMultipleAttachments(t *testing.T, tf *TestFramework) {
 	require.True(t, lo.Return2(tx3Metadata.OrphanedSlot()))
 
 	// All conflicts still exist, as they are kept around until MCA
```
Comment (piotrm50) [inline pkg/protocol/engine/mempool/tests/tests.go:250]:
```suggestion
	// All spends still exist, as they are kept around until MCA
```

File: pkg/protocol/engine/mempool/spenddag/spenddagv1/spenddag_test.go [hunk 64]
```diff
@@ -53,28 +53,28 @@ func TestMemoryRelease(t *testing.T) {
...
-		for ; slot < startSlot+conflictSetCount; slot++ {
-			conflictSetAlias := fmt.Sprintf("conflictSet-%d", slot)
-			for conflictIndex := 0; conflictIndex < spendsInConflictSet; conflictIndex++ {
-				conflictAlias := fmt.Sprintf("conflictSet-%d:%d", slot, conflictIndex)
-				require.NoError(t, tf.CreateOrUpdateSpend(conflictAlias, []string{conflictSetAlias}))
-				if prevConflictSetAlias != "" {
-					require.NoError(t, tf.UpdateSpendParents(conflictAlias, []string{fmt.Sprintf("%s:%d", prevConflictSetAlias, 0)}, []string{}))
+		for ; slot < startSlot+spendSetCount; slot++ {
+			spendSetAlias := fmt.Sprintf("spendSet-%d", slot)
+			for conflictIndex := 0; conflictIndex < spendsInSpendSet; conflictIndex++ {
```
Comment (piotrm50) [inline pkg/protocol/engine/mempool/spenddag/spenddagv1/spenddag_test.go]: `conflictIndex` -> `spendIndex`

File: pkg/protocol/engine/mempool/spenddag/spenddagv1/spenddag_test.go [hunk 65]
```diff
@@ -53,28 +53,28 @@ func TestMemoryRelease(t *testing.T) {
...
+					require.NoError(t, tf.UpdateSpendParents(conflictAlias, []string{fmt.Sprintf("%s:%d", prevSpendSetAlias, 0)}, []string{}))
 				}
 			}
-			prevConflictSetAlias = conflictSetAlias
+			prevSpendSetAlias = spendSetAlias
 
 			if slotToEvict := slot - evictionDelay; slotToEvict >= 0 {
-				for conflictIndex := 0; conflictIndex < spendsInConflictSet; conflictIndex++ {
-					conflictAlias := fmt.Sprintf("conflictSet-%d:%d", slotToEvict, conflictIndex)
+				for conflictIndex := 0; conflictIndex < spendsInSpendSet; conflictIndex++ {
```
Comment (piotrm50) [inline pkg/protocol/engine/mempool/spenddag/spenddagv1/spenddag_test.go]: `conflictIndex` -> `spendIndex`

**Review by piotrm50 — CHANGES_REQUESTED** [review]
Another batch of missed conflict renames.

File: components/dashboard/frontend/src/app/components/ExplorerAddressResult.tsx (hunk 54 above)
Comment (muXxer) [reply components/dashboard/frontend/src/app/components/ExplorerAddressResult.tsx]: Why was that resolved without a comment? Because I also don't get the change...

File: components/dashboard/frontend/src/app/components/ExplorerBlockQueryResult.tsx [hunk 66]
```diff
@@ -124,15 +124,15 @@ export class ExplorerBlockQueryResult extends React.Component<Props, any> {
                                         Sequence Number: {blk.sequenceNumber}
                                     </ListGroup.Item>
                                     <ListGroup.Item>
-                                        ConflictIDs:
+                                        spendIDs:
```
Comment (muXxer) [inline components/dashboard/frontend/src/app/components/ExplorerBlockQueryResult.tsx]: Capital letter?

File: components/dashboard/frontend/src/app/components/ExplorerOutputQueryResult.tsx [hunk 67]
```diff
@@ -76,14 +76,14 @@ export class ExplorerOutputQueryResult extends React.Component<Props, any> {
                 {outputMetadata && <div className={"mb-2"}>
                     <ListGroup>
                         <ListGroup.Item>Transaction ID: <a href={`/explorer/transaction/${outputMetadata.outputID.transactionID}`}>{outputMetadata.outputID.transactionID}</a> </ListGroup.Item>
-                        ConflictIDs: 
+                        spendIDs:
```
Comment (muXxer) [inline components/dashboard/frontend/src/app/components/ExplorerOutputQueryResult.tsx]: Capital letter?

File: components/dashboard/frontend/src/app/stores/ExplorerStore.tsx [hunk 68]
```diff
@@ -121,35 +121,35 @@ class PendingMana {
...
 
-class ConflictChild {
-    conflictID: string;
+class SpendChild {
+    spendID: string;
     type: string;
 }
 
-class ConflictConflict {
+class SpendSpend {
```
Comment (muXxer) [inline components/dashboard/frontend/src/app/stores/ExplorerStore.tsx]: I wonder if this here actually isn't about conflicts?

File: components/dashboard/frontend/src/app/stores/ExplorerStore.tsx [hunk 69]
```diff
@@ -121,35 +121,35 @@ class PendingMana {
...
     outputID: OutputID;
-    conflictIDs: Array<string>;
+    spendIDs: Array<string>;
 }
 
-class ConflictConflicts {
-    conflictID: string;
-    conflicts: Array<ConflictConflict>
+class SpendSpends {
```
Comment (muXxer) [inline components/dashboard/frontend/src/app/stores/ExplorerStore.tsx]: I wonder if this here actually isn't about conflicts?

File: components/dashboard/frontend/src/app/stores/ExplorerStore.tsx [hunk 70]
```diff
@@ -121,35 +121,35 @@ class PendingMana {
...
+    spendID: string;
+    spends: Array<SpendSpend>
 }
 
-class ConflictVoters {
-    conflictID: string;
+class SpendVoters {
```
Comment (muXxer) [inline components/dashboard/frontend/src/app/stores/ExplorerStore.tsx]: I wonder if this here actually isn't about conflicts?

**Review by muXxer — COMMENTED** [review]
This is such a massive "renaming PR".... I don't like that it also includes logic changes at the same time.

For the next time you do such a refactor,  it would be much better to split it up into several PRs.

For example, use the rename capability of the IDE only, no "find & replace" (I see that you used that because uncommented code also changed). And then create commits per single "rename". This is much easier to check, because we all can simply trust your IDE.

The logic changes should be part of another PR next time.


Regarding the new naming and the logic, I totally agree with @cyberphysic4l 's comment.
Maybe we should create another type for the tuple of `(iotago.TransactionID, iotago.OutputID)` in another PR and fix the logic.

I also think the usage of "transactionID" instead of "spendID" in some places makes more sense.


Should we merge this PR or will this heavily conflict with the react branches?

File: components/dashboard/frontend/src/app/stores/ExplorerStore.tsx (hunk 70 above)
Comment (jkrvivian) [reply components/dashboard/frontend/src/app/stores/ExplorerStore.tsx]: I removed those conflict stores and classes instead, bc it's not even implemented and enabled.

**Review by muXxer — APPROVED** [review]

**Review by piotrm50 — APPROVED** [review]
