### PR TITLE
Fix panic when payload is nil

### LINKED ISSUE #978: invalid memory address or nil pointer dereference (2)
Got another one (different). On **1.0.0-beta.5**

---

iota-core3      | } roots =Roots(0x0aabb6888726a036b3fee7e352c84d64280d6aaea198a656472b674552f6b69b): TangleRoot: 0x90574a25f6c56e9f7975bf2c141a07c5df1f03f792f78f12dcb0ae747191f086, StateMutationRoot: 0x0000000000000000000000000000000000000000000000000000000000000000, StateRoot: 0x501dd5efada3a0efd259a775729d4531bf9086d2bab7e237167c5046f4f04e01, AccountRoot: 0xce28cba3d449b042319f190bf1de6c7f7a49ffbbd8dea071e96c5f12214688ee, AttestationsRoot: 0x1829cf9c91d85c93e302fe6edefd5976cc58b8e411a3523851403732421c4b0c, CommitteeRoot: 0x4b3392bb055664da742254f3c5b221bacf9290b8426e9ffb1a1a968531e48260, RewardsRoot: 0x5da4bf984b4050d12b507b5c060b1ab33dce1ad6af5834f3c70b3dec56a04eda, ProtocolParametersHash: 0x9786d0ead851be3d740e0956a2c8e2dd7eec59a2fb3e608834ca8a57ee1eede8)
iota-core3      | panic: runtime error: invalid memory address or nil pointer dereference
iota-core3      | [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x14126bf]
iota-core3      | 
iota-core3      | goroutine 211 [running]:
iota-core3      | github.com/iotaledger/iota-core/pkg/protocol/sybilprotection/sybilprotectionv1.(*SybilProtection).TrackBlock(0xc00014f560, 0xc00aad01c0)
iota-core3      |       /scratch/pkg/protocol/sybilprotection/sybilprotectionv1/sybilprotection.go:116 +0x11f
iota-core3      | github.com/iotaledger/iota-core/pkg/protocol/engine.(*Engine).acceptanceHandler.func1(0xc00aad01c0)
iota-core3      |       /scratch/pkg/protocol/engine/engine.go:538 +0x5e
iota-core3      | github.com/iotaledger/hive.go/runtime/event.(*Event1[...]).Trigger.func1.1()
iota-core3      |       /go/pkg/mod/github.com/iotaledger/hive.go/runtime@v0.0.0-20240425095808-113b21573349/event/events.go:86 +0x1f
iota-core3      | github.com/iotaledger/hive.go/runtime/workerpool.(*Task).run(0xc003e77140)
iota-core3      |       /go/pkg/mod/github.com/iotaledger/hive.go/runtime@v0.0.0-20240425095808-113b21573349/workerpool/task.go:48 +0x72
iota-core3      | github.com/iotaledger/hive.go/runtime/workerpool.(*WorkerPool).workerReadLoop(0xc000553340)
iota-core3      |       /go/pkg/mod/github.com/iotaledger/hive.go/runtime@v0.0.0-20240425095808-113b21573349/workerpool/workerpool.go:226 +0x25
iota-core3      | github.com/iotaledger/hive.go/runtime/workerpool.(*WorkerPool).worker(0xc000553340)
iota-core3      |       /go/pkg/mod/github.com/iotaledger/hive.go/runtime@v0.0.0-20240425095808-113b21573349/workerpool/workerpool.go:206 +0x50
iota-core3      | created by github.com/iotaledger/hive.go/runtime/workerpool.(*WorkerPool).startWorkers in goroutine 179
iota-core3      |       /go/pkg/mod/github.com/iotaledger/hive.go/runtime@v0.0.0-20240425095808-113b21573349/workerpool/workerpool.go:198 +0x26

### PR DESCRIPTION
**Pull request by PhilippGackstatter**
Fix panic when payload is nil and add a test for it.

### CODE REVIEW

**Review by piotrm50 — APPROVED** [review]

File: tools/docker-network/run.sh [hunk 1]
```diff
@@ -94,14 +97,15 @@ if [ $MONITORING -ne 0 ]; then
...
 if [ $MINIMAL -ne 0 ]; then
-  PROFILES+=("minimal")
   echo "Minimal profile active"
 else
   PROFILES+=("full")
   echo "Full profile active"
 fi
 
 export COMPOSE_PROFILES=$(join , ${PROFILES[@]})
+echo $COMPOSE_PROFILES
```
Comment (piotrm50) [inline tools/docker-network/run.sh]:
```suggestion
```

**Review by piotrm50 — APPROVED** [review]
